-- NOTE: This file is auto generated by ./sql-generator

-- AccessRepository.activity.checkOwnerAccess
select
  "activity"."id"
from
  "activity"
where
  "activity"."id" in ($1)
  and "activity"."userId" = $2

-- AccessRepository.activity.checkAlbumOwnerAccess
select
  "activity"."id"
from
  "activity"
  inner join "album" on "activity"."albumId" = "album"."id"
  and "album"."deletedAt" is null
  inner join "album_user" on "album"."id" = "album_user"."albumId"
  and "album_user"."role" = 'owner'
  and "album_user"."userId" = $1::uuid
where
  "activity"."id" in ($2)

-- AccessRepository.activity.checkCreateAccess
select
  "album"."id"
from
  "album"
  inner join "album_user" as "albumUsers" on "albumUsers"."albumId" = "album"."id"
  inner join "user" on "user"."id" = "albumUsers"."userId"
  and "user"."deletedAt" is null
where
  "album"."id" in ($1)
  and "album"."isActivityEnabled" = $2
  and "user"."id" = $3
  and "album"."deletedAt" is null

-- AccessRepository.album.checkOwnerAccess
select
  "album"."id"
from
  "album"
  inner join "album_user" on "album"."id" = "album_user"."albumId"
  and "album_user"."role" = 'owner'
  and "album_user"."userId" = $1
where
  "album"."id" in ($2)
  and "album"."deletedAt" is null

-- AccessRepository.album.checkSharedAlbumAccess
select
  "album"."id"
from
  "album"
  inner join "album_user" on "album_user"."albumId" = "album"."id"
  inner join "user" on "user"."id" = "album_user"."userId"
  and "user"."deletedAt" is null
where
  "album"."id" in ($1)
  and "album"."deletedAt" is null
  and "user"."id" = $2
  and "album_user"."role" in ($3, $4)

-- AccessRepository.album.checkSharedLinkAccess
select
  "shared_link"."albumId"
from
  "shared_link"
where
  "shared_link"."id" = $1
  and "shared_link"."albumId" in ($2)

-- AccessRepository.album.checkSpaceLinkedAlbumAccess
select distinct
  "album"."id"
from
  "album"
  inner join "shared_space_album" on "shared_space_album"."albumId" = "album"."id"
  inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_album"."spaceId"
where
  "album"."id" in ($1)
  and "album"."deletedAt" is null
  and "shared_space_member"."userId" = $2
  and "shared_space_member"."role" in ($3, $4)

-- AccessRepository.album.checkSpaceLinkedAlbumReadAccess
select distinct
  "album"."id"
from
  "album"
  inner join "shared_space_album" on "shared_space_album"."albumId" = "album"."id"
  inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_album"."spaceId"
where
  "album"."id" in ($1)
  and "album"."deletedAt" is null
  and "shared_space_member"."userId" = $2

-- AccessRepository.asset.checkAlbumAccess
with
  "target" as (
    select
      array[$1]::uuid[] as "ids"
  )
select
  "asset"."id",
  "asset"."livePhotoVideoId"
from
  "album"
  inner join "album_asset" as "albumAssets" on "album"."id" = "albumAssets"."albumId"
  inner join "asset" on "asset"."id" = "albumAssets"."assetId"
  and "asset"."deletedAt" is null
  left join "album_user" as "albumUsers" on "albumUsers"."albumId" = "album"."id"
  left join "user" on "user"."id" = "albumUsers"."userId"
  and "user"."deletedAt" is null
  cross join "target"
where
  (
    "asset"."id" = any (target.ids)
    or "asset"."livePhotoVideoId" = any (target.ids)
  )
  and "user"."id" = $2
  and "album"."deletedAt" is null

-- AccessRepository.asset.checkOwnerAccess
select
  "asset"."id"
from
  "asset"
where
  "asset"."id" in ($1)
  and "asset"."ownerId" = $2
  and "asset"."visibility" != $3

-- AccessRepository.asset.checkPartnerAccess
select
  "asset"."id"
from
  "partner"
  inner join "user" as "sharedBy" on "sharedBy"."id" = "partner"."sharedById"
  and "sharedBy"."deletedAt" is null
  inner join "asset" on "asset"."ownerId" = "sharedBy"."id"
  and "asset"."deletedAt" is null
where
  "partner"."sharedWithId" = $1
  and (
    "asset"."visibility" = 'timeline'
    or "asset"."visibility" = 'hidden'
  )
  and "asset"."id" in ($2)

-- AccessRepository.asset.checkSpaceAccess
select
  "combined"."id",
  "combined"."livePhotoVideoId"
from
  (
    select
      "asset"."id",
      "asset"."livePhotoVideoId"
    from
      "shared_space_asset"
      inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_asset"."spaceId"
      inner join "asset" on "asset"."id" = "shared_space_asset"."assetId"
      and "asset"."deletedAt" is null
    where
      "shared_space_member"."userId" = $1
      and "asset"."visibility" in ($2, $3)
      and (
        "asset"."id" in ($4)
        or "asset"."livePhotoVideoId" in ($5)
      )
    union
    select
      "asset"."id",
      "asset"."livePhotoVideoId"
    from
      "shared_space_library"
      inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_library"."spaceId"
      inner join "asset" on "asset"."libraryId" = "shared_space_library"."libraryId"
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $6
    where
      "shared_space_member"."userId" = $7
      and "asset"."visibility" in ($8, $9)
      and (
        "asset"."id" in ($10)
        or "asset"."livePhotoVideoId" in ($11)
      )
    union
    select
      "asset"."id",
      "asset"."livePhotoVideoId"
    from
      "shared_space_album"
      inner join "album" on "album"."id" = "shared_space_album"."albumId"
      and "album"."deletedAt" is null
      inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_album"."spaceId"
      inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
      inner join "asset" on "asset"."id" = "album_asset"."assetId"
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $12
    where
      "shared_space_member"."userId" = $13
      and "asset"."visibility" in ($14, $15)
      and (
        "asset"."id" in ($16)
        or "asset"."livePhotoVideoId" in ($17)
      )
    union
    select
      "asset"."id",
      "asset"."livePhotoVideoId"
    from
      "shared_space_album"
      inner join "album" on "album"."id" = "shared_space_album"."albumId"
      and "album"."deletedAt" is null
      inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_album"."spaceId"
      inner join "album_space_asset" on "album_space_asset"."albumId" = "shared_space_album"."albumId"
      and "album_space_asset"."spaceId" = "shared_space_album"."spaceId"
      inner join "asset" on "asset"."id" = "album_space_asset"."assetId"
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $18
    where
      "shared_space_member"."userId" = $19
      and "asset"."visibility" in ($20, $21)
      and (
        "asset"."id" in ($22)
        or "asset"."livePhotoVideoId" in ($23)
      )
  ) as "combined"

-- AccessRepository.asset.checkSpaceAccessForSpace
select
  "combined"."id",
  "combined"."livePhotoVideoId"
from
  (
    select
      "asset"."id",
      "asset"."livePhotoVideoId"
    from
      "shared_space_asset"
      inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_asset"."spaceId"
      inner join "asset" on "asset"."id" = "shared_space_asset"."assetId"
      and "asset"."deletedAt" is null
    where
      "shared_space_member"."userId" = $1
      and "shared_space_asset"."spaceId" = $2
      and "asset"."visibility" in ($3, $4)
      and (
        "asset"."id" in ($5)
        or "asset"."livePhotoVideoId" in ($6)
      )
    union
    select
      "asset"."id",
      "asset"."livePhotoVideoId"
    from
      "shared_space_library"
      inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_library"."spaceId"
      inner join "asset" on "asset"."libraryId" = "shared_space_library"."libraryId"
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $7
    where
      "shared_space_member"."userId" = $8
      and "shared_space_library"."spaceId" = $9
      and "asset"."visibility" in ($10, $11)
      and (
        "asset"."id" in ($12)
        or "asset"."livePhotoVideoId" in ($13)
      )
    union
    select
      "asset"."id",
      "asset"."livePhotoVideoId"
    from
      "shared_space_album"
      inner join "album" on "album"."id" = "shared_space_album"."albumId"
      and "album"."deletedAt" is null
      inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_album"."spaceId"
      inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
      inner join "asset" on "asset"."id" = "album_asset"."assetId"
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $14
    where
      "shared_space_member"."userId" = $15
      and "shared_space_album"."spaceId" = $16
      and "asset"."visibility" in ($17, $18)
      and (
        "asset"."id" in ($19)
        or "asset"."livePhotoVideoId" in ($20)
      )
    union
    select
      "asset"."id",
      "asset"."livePhotoVideoId"
    from
      "shared_space_album"
      inner join "album" on "album"."id" = "shared_space_album"."albumId"
      and "album"."deletedAt" is null
      inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_album"."spaceId"
      inner join "album_space_asset" on "album_space_asset"."albumId" = "shared_space_album"."albumId"
      and "album_space_asset"."spaceId" = "shared_space_album"."spaceId"
      inner join "asset" on "asset"."id" = "album_space_asset"."assetId"
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $21
    where
      "shared_space_member"."userId" = $22
      and "shared_space_album"."spaceId" = $23
      and "asset"."visibility" in ($24, $25)
      and (
        "asset"."id" in ($26)
        or "asset"."livePhotoVideoId" in ($27)
      )
  ) as "combined"

-- AccessRepository.asset.checkSpaceEditAccess
select
  "combined"."id",
  "combined"."livePhotoVideoId"
from
  (
    select
      "asset"."id",
      "asset"."livePhotoVideoId"
    from
      "shared_space_asset"
      inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_asset"."spaceId"
      inner join "asset" on "asset"."id" = "shared_space_asset"."assetId"
      and "asset"."deletedAt" is null
    where
      "shared_space_member"."userId" = $1
      and "asset"."visibility" in ($2, $3)
      and (
        "asset"."id" in ($4)
        or "asset"."livePhotoVideoId" in ($5)
      )
      and "shared_space_member"."role" in ($6, $7)
    union
    select
      "asset"."id",
      "asset"."livePhotoVideoId"
    from
      "shared_space_library"
      inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_library"."spaceId"
      inner join "asset" on "asset"."libraryId" = "shared_space_library"."libraryId"
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $8
    where
      "shared_space_member"."userId" = $9
      and "asset"."visibility" in ($10, $11)
      and (
        "asset"."id" in ($12)
        or "asset"."livePhotoVideoId" in ($13)
      )
      and "shared_space_member"."role" in ($14, $15)
  ) as "combined"

-- AccessRepository.asset.checkSharedLinkAccess
select
  "asset"."id" as "assetId",
  "asset"."livePhotoVideoId" as "assetLivePhotoVideoId",
  "albumAssets"."id" as "albumAssetId",
  "albumAssets"."livePhotoVideoId" as "albumAssetLivePhotoVideoId"
from
  "shared_link"
  left join "album" on "album"."id" = "shared_link"."albumId"
  and "album"."deletedAt" is null
  left join "shared_link_asset" on "shared_link_asset"."sharedLinkId" = "shared_link"."id"
  left join "asset" on "asset"."id" = "shared_link_asset"."assetId"
  and "asset"."deletedAt" is null
  left join "album_asset" on "album_asset"."albumId" = "album"."id"
  left join "asset" as "albumAssets" on "albumAssets"."id" = "album_asset"."assetId"
  and "albumAssets"."deletedAt" is null
where
  "shared_link"."id" = $1
  and array[
    "asset"."id",
    "asset"."livePhotoVideoId",
    "albumAssets"."id",
    "albumAssets"."livePhotoVideoId"
  ] && array[$2]::uuid[]

-- AccessRepository.assetFile.checkOwnerAccess
select
  "asset_file"."id"
from
  "asset_file"
  inner join "asset" on "asset"."id" = "asset_file"."assetId"
where
  "asset"."visibility" != $1
  and "asset"."ownerId" = $2
  and "asset_file"."id" in ($3)

-- AccessRepository.authDevice.checkOwnerAccess
select
  "session"."id"
from
  "session"
where
  "session"."userId" = $1
  and "session"."id" in ($2)

-- AccessRepository.duplicate.checkOwnerAccess
select
  "asset"."duplicateId"
from
  "asset"
where
  "asset"."duplicateId" in ($1)
  and "asset"."ownerId" = $2
  and "asset"."deletedAt" is null

-- AccessRepository.memory.checkOwnerAccess
select
  "memory"."id"
from
  "memory"
where
  "memory"."id" in ($1)
  and "memory"."ownerId" = $2
  and "memory"."deletedAt" is null

-- AccessRepository.notification.checkOwnerAccess
select
  "notification"."id"
from
  "notification"
where
  "notification"."id" in ($1)
  and "notification"."userId" = $2

-- AccessRepository.clusterGroup.checkInviteAccess
select
  "cluster_group_request"."clusterGroupId"
from
  "cluster_group_request"
where
  "cluster_group_request"."clusterGroupId" in ($1)
  and "cluster_group_request"."userId" = $2

-- AccessRepository.clusterGroup.checkOwnerAccess
select
  "user"."clusterGroupId"
from
  "user"
where
  "user"."clusterGroupId" in ($1)
  and "user"."id" = $2

-- AccessRepository.clusterGroupRequest.checkOwnerAccess
select
  "cluster_group_request"."id"
from
  "cluster_group_request"
where
  "cluster_group_request"."id" in ($1)
  and "cluster_group_request"."userId" = $2

-- AccessRepository.clusterGroupRequest.checkGroupAccess
select
  "cluster_group_request"."id"
from
  "cluster_group_request"
where
  "cluster_group_request"."id" in ($1)
  and "cluster_group_request"."clusterGroupId" = (
    select
      "user"."clusterGroupId"
    from
      "user"
    where
      "user"."id" = $2
  )

-- AccessRepository.person.checkOwnerAccess
select
  "person"."personGroupId"
from
  "person"
where
  "person"."personGroupId" in ($1)
  and "person"."ownerId" = $2

-- AccessRepository.person.checkSharedSpaceAccess
select
  "person"."id"
from
  "person"
where
  "person"."id" in ($1)
  and exists (
    select
    from
      "asset_face"
      inner join "asset" on "asset"."id" = "asset_face"."assetId"
      and "asset"."deletedAt" is null
      and "asset"."visibility" in ($2, $3)
    where
      "asset_face"."personId" = "person"."id"
      and "asset_face"."deletedAt" is null
      and "asset_face"."isVisible" is true
      and (
        exists (
          select
            1 as "exists"
          from
            "shared_space_asset"
            inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_asset"."spaceId"
          where
            "shared_space_member"."userId" = $4::uuid
            and "shared_space_asset"."assetId" = "asset"."id"
        )
        or exists (
          select
            1 as "exists"
          from
            "shared_space_library"
            inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_library"."spaceId"
          where
            "shared_space_member"."userId" = $5::uuid
            and "shared_space_library"."libraryId" = "asset"."libraryId"
        )
        or (
          exists (
            select
              1 as "exists"
            from
              "shared_space_album"
              inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
              inner join "album" on "album"."id" = "shared_space_album"."albumId"
              and "album"."deletedAt" is null
              inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_album"."spaceId"
            where
              "shared_space_member"."userId" = $6::uuid
              and "album_asset"."assetId" = "asset"."id"
          )
          or exists (
            select
              1 as "exists"
            from
              "shared_space_album"
              inner join "album_space_asset" on "album_space_asset"."albumId" = "shared_space_album"."albumId"
              and "album_space_asset"."spaceId" = "shared_space_album"."spaceId"
              inner join "album" on "album"."id" = "shared_space_album"."albumId"
              and "album"."deletedAt" is null
              inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_album"."spaceId"
            where
              "shared_space_member"."userId" = $7::uuid
              and "album_space_asset"."assetId" = "asset"."id"
          )
        )
      )
  )

-- AccessRepository.person.checkSharedSpaceEditAccess
select
  "person"."id"
from
  "person"
where
  "person"."id" in ($1)
  and exists (
    select
    from
      "asset_face"
      inner join "asset" on "asset"."id" = "asset_face"."assetId"
      and "asset"."deletedAt" is null
      and "asset"."visibility" in ($2, $3)
    where
      "asset_face"."personId" = "person"."id"
      and "asset_face"."deletedAt" is null
      and "asset_face"."isVisible" is true
      and (
        exists (
          select
            1 as "exists"
          from
            "shared_space_asset"
            inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_asset"."spaceId"
          where
            "shared_space_member"."userId" = $4::uuid
            and "shared_space_member"."role" in ($5, $6)
            and "shared_space_asset"."assetId" = "asset"."id"
        )
        or exists (
          select
            1 as "exists"
          from
            "shared_space_library"
            inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_library"."spaceId"
          where
            "shared_space_member"."userId" = $7::uuid
            and "shared_space_member"."role" in ($8, $9)
            and "shared_space_library"."libraryId" = "asset"."libraryId"
        )
        or (
          exists (
            select
              1 as "exists"
            from
              "shared_space_album"
              inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
              inner join "album" on "album"."id" = "shared_space_album"."albumId"
              and "album"."deletedAt" is null
              inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_album"."spaceId"
            where
              "shared_space_member"."userId" = $10::uuid
              and "shared_space_member"."role" in ($11, $12)
              and "album_asset"."assetId" = "asset"."id"
          )
          or exists (
            select
              1 as "exists"
            from
              "shared_space_album"
              inner join "album_space_asset" on "album_space_asset"."albumId" = "shared_space_album"."albumId"
              and "album_space_asset"."spaceId" = "shared_space_album"."spaceId"
              inner join "album" on "album"."id" = "shared_space_album"."albumId"
              and "album"."deletedAt" is null
              inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_album"."spaceId"
            where
              "shared_space_member"."userId" = $13::uuid
              and "shared_space_member"."role" in ($14, $15)
              and "album_space_asset"."assetId" = "asset"."id"
          )
        )
      )
  )

-- AccessRepository.person.checkFaceOwnerAccess
select
  "asset_face"."id"
from
  "asset_face"
  left join "asset" on "asset"."id" = "asset_face"."assetId"
  and "asset"."deletedAt" is null
where
  "asset_face"."id" in ($1)
  and "asset"."ownerId" = $2

-- AccessRepository.sharedSpace.checkMemberAccess
select
  "shared_space_member"."spaceId"
from
  "shared_space_member"
where
  "shared_space_member"."spaceId" in ($1)
  and "shared_space_member"."userId" = $2

-- AccessRepository.partner.checkUpdateAccess
select
  "partner"."sharedById"
from
  "partner"
where
  "partner"."sharedById" in ($1)
  and "partner"."sharedWithId" = $2

-- AccessRepository.session.checkOwnerAccess
select
  "session"."id"
from
  "session"
where
  "session"."id" in ($1)
  and "session"."userId" = $2

-- AccessRepository.stack.checkOwnerAccess
select
  "stack"."id"
from
  "stack"
where
  "stack"."id" in ($1)
  and "stack"."ownerId" = $2

-- AccessRepository.tag.checkOwnerAccess
select
  "tag"."id"
from
  "tag"
where
  "tag"."id" in ($1)
  and "tag"."userId" = $2

-- AccessRepository.timeline.checkPartnerAccess
select
  "partner"."sharedById"
from
  "partner"
where
  "partner"."sharedById" in ($1)
  and "partner"."sharedWithId" = $2

-- AccessRepository.workflow.checkOwnerAccess
select
  "workflow"."id"
from
  "workflow"
where
  "workflow"."id" in ($1)
  and "workflow"."ownerId" = $2
