-- NOTE: This file is auto generated by ./sql-generator

-- AgentToolCallRepository.getBySessionId
select
  "id",
  "sessionId",
  "toolName",
  "status",
  "approvalDecision",
  "requestSummary",
  "responseSummary",
  "redactedRequestMetadata",
  "redactedResponseMetadata",
  "dataClass",
  "assetCount",
  "albumCount",
  "providerSnapshot",
  "startedAt",
  "completedAt",
  "error"
from
  "agent_tool_call"
where
  "sessionId" = $1::uuid
order by
  "startedAt" desc,
  "id" desc

-- AgentToolCallRepository.getByIdForSession
select
  "id",
  "sessionId",
  "toolName",
  "status",
  "approvalDecision",
  "requestSummary",
  "responseSummary",
  "redactedRequestMetadata",
  "redactedResponseMetadata",
  "dataClass",
  "assetCount",
  "albumCount",
  "providerSnapshot",
  "startedAt",
  "completedAt",
  "error"
from
  "agent_tool_call"
where
  "sessionId" = $1::uuid
  and "id" = $2::uuid

-- AgentToolCallRepository.getCountedAssetCountBySession (including all)
select
  coalesce(sum("assetCount"), 0)::int as "assetCount"
from
  "agent_tool_call"
where
  "sessionId" = $1::uuid
  and "dataClass" = $2
  and "status" in ($3, $4, $5, $6)

-- AgentToolCallRepository.getCountedAssetCountBySession (excluding tool call)
select
  coalesce(sum("assetCount"), 0)::int as "assetCount"
from
  "agent_tool_call"
where
  "sessionId" = $1::uuid
  and "dataClass" = $2
  and "status" in ($3, $4, $5, $6)
  and "id" != $7::uuid

-- AgentToolCallRepository.getCountedAssetCountBySessionAndDataClass (including all)
select
  coalesce(sum("assetCount"), 0)::int as "assetCount"
from
  "agent_tool_call"
where
  "sessionId" = $1::uuid
  and "dataClass" = $2
  and "status" in ($3, $4, $5, $6)

-- AgentToolCallRepository.getCountedAssetCountBySessionAndDataClass (excluding tool call)
select
  coalesce(sum("assetCount"), 0)::int as "assetCount"
from
  "agent_tool_call"
where
  "sessionId" = $1::uuid
  and "dataClass" = $2
  and "status" in ($3, $4, $5, $6)
  and "id" != $7::uuid
