-- NOTE: This file is auto generated by ./sql-generator

-- AgentSessionRepository.getByUserId
select
  "id",
  "userId",
  "providerCredentialId",
  "credentialSnapshot",
  "modelSnapshot",
  "permissionPreset",
  "permissionPlanSnapshot",
  "approvalMode",
  "runnerEndpoint",
  "runnerSessionId",
  "runnerCapabilitiesSnapshot",
  "workflowState",
  "status",
  "initialContextSnapshot",
  "title",
  "createdAt",
  "updatedAt",
  "endedAt",
  "updateId"
from
  "agent_session"
where
  "userId" = $1
order by
  "createdAt" desc,
  "id" desc

-- AgentSessionRepository.getById
select
  "id",
  "userId",
  "providerCredentialId",
  "credentialSnapshot",
  "modelSnapshot",
  "permissionPreset",
  "permissionPlanSnapshot",
  "approvalMode",
  "runnerEndpoint",
  "runnerSessionId",
  "runnerCapabilitiesSnapshot",
  "workflowState",
  "status",
  "initialContextSnapshot",
  "title",
  "createdAt",
  "updatedAt",
  "endedAt",
  "updateId"
from
  "agent_session"
where
  "userId" = $1
  and "id" = $2::uuid

-- AgentSessionRepository.markRunningFromCreated
update "agent_session"
set
  "status" = $1,
  "runnerEndpoint" = $2,
  "runnerSessionId" = $3,
  "runnerCapabilitiesSnapshot" = $4
where
  "userId" = $5
  and "id" = $6::uuid
  and "status" = $7
returning
  "id",
  "userId",
  "providerCredentialId",
  "credentialSnapshot",
  "modelSnapshot",
  "permissionPreset",
  "permissionPlanSnapshot",
  "approvalMode",
  "runnerEndpoint",
  "runnerSessionId",
  "runnerCapabilitiesSnapshot",
  "workflowState",
  "status",
  "initialContextSnapshot",
  "title",
  "createdAt",
  "updatedAt",
  "endedAt",
  "updateId"

-- AgentSessionRepository.markFailedFromCreated
update "agent_session"
set
  "status" = $1,
  "endedAt" = $2
where
  "userId" = $3
  and "id" = $4::uuid
  and "status" = $5
returning
  "id",
  "userId",
  "providerCredentialId",
  "credentialSnapshot",
  "modelSnapshot",
  "permissionPreset",
  "permissionPlanSnapshot",
  "approvalMode",
  "runnerEndpoint",
  "runnerSessionId",
  "runnerCapabilitiesSnapshot",
  "workflowState",
  "status",
  "initialContextSnapshot",
  "title",
  "createdAt",
  "updatedAt",
  "endedAt",
  "updateId"

-- AgentSessionRepository.markInterruptedFromActive
update "agent_session"
set
  "status" = $1
where
  "userId" = $2
  and "id" = $3::uuid
  and "status" in ($4, $5, $6, $7)
returning
  "id",
  "userId",
  "providerCredentialId",
  "credentialSnapshot",
  "modelSnapshot",
  "permissionPreset",
  "permissionPlanSnapshot",
  "approvalMode",
  "runnerEndpoint",
  "runnerSessionId",
  "runnerCapabilitiesSnapshot",
  "workflowState",
  "status",
  "initialContextSnapshot",
  "title",
  "createdAt",
  "updatedAt",
  "endedAt",
  "updateId"

-- AgentSessionRepository.cancel
update "agent_session"
set
  "status" = $1,
  "endedAt" = $2
where
  "userId" = $3
  and "id" = $4::uuid
  and "status" in ($5, $6, $7, $8, $9)
returning
  "id",
  "userId",
  "providerCredentialId",
  "credentialSnapshot",
  "modelSnapshot",
  "permissionPreset",
  "permissionPlanSnapshot",
  "approvalMode",
  "runnerEndpoint",
  "runnerSessionId",
  "runnerCapabilitiesSnapshot",
  "workflowState",
  "status",
  "initialContextSnapshot",
  "title",
  "createdAt",
  "updatedAt",
  "endedAt",
  "updateId"
