-- NOTE: This file is auto generated by ./sql-generator

-- AgentSessionActivityEventRepository.getBySessionId
select
  "id",
  "sessionId",
  "kind",
  "status",
  "source",
  "summary",
  "counts",
  "createdAt"
from
  "agent_session_activity_event"
where
  "sessionId" = $1::uuid
order by
  "createdAt" asc,
  "id" asc
