-- NOTE: This file is auto generated by ./sql-generator

-- AgentOperationPlanRepository.getNextRevision
select
  coalesce(max("revision"), 0)::int + 1 as "revision"
from
  "agent_operation_plan"
where
  "sessionId" = $1::uuid

-- AgentOperationPlanRepository.getByIdForSession
select
  "id",
  "sessionId",
  "revision",
  "status",
  "summary",
  "createdAt",
  "updatedAt"
from
  "agent_operation_plan"
where
  "sessionId" = $1::uuid
  and "id" = $2::uuid

-- AgentOperationPlanRepository.getCurrentBySessionId
select
  "id",
  "sessionId",
  "revision",
  "status",
  "summary",
  "createdAt",
  "updatedAt"
from
  "agent_operation_plan"
where
  "sessionId" = $1::uuid
  and "status" = $2
order by
  "revision" desc

-- AgentOperationPlanRepository.getAppliedBySessionId
select
  "id",
  "sessionId",
  "revision",
  "status",
  "summary",
  "createdAt",
  "updatedAt"
from
  "agent_operation_plan"
where
  "sessionId" = $1::uuid
  and "status" = $2
order by
  "updatedAt" asc,
  "revision" asc,
  "id" asc
