-- NOTE: This file is auto generated by ./sql-generator

-- AgentSelectionHandleRepository.getValidForPlanning
select
  "id",
  "sessionId",
  "userId",
  "sourceToolCallId",
  "assetIds",
  "assetCount",
  "sampleAssetIds",
  "expiresAt",
  "createdAt",
  "updateId"
from
  "agent_selection_handle"
where
  "id" = $1::uuid
  and "sessionId" = $2::uuid
  and "userId" = $3::uuid
  and "expiresAt" > $4
