-- NOTE: This file is auto generated by ./sql-generator

-- AgentProviderCredentialRepository.getByUserId
select
  "id",
  "userId",
  "providerType",
  "label",
  "baseUrl",
  "encryptedSecret",
  "secretVersion",
  "models",
  "defaultModel",
  "lastUsedAt",
  "createdAt",
  "updatedAt",
  "updateId"
from
  "agent_provider_credential"
where
  "userId" = $1
order by
  "createdAt" desc

-- AgentProviderCredentialRepository.getById
select
  "id",
  "userId",
  "providerType",
  "label",
  "baseUrl",
  "encryptedSecret",
  "secretVersion",
  "models",
  "defaultModel",
  "lastUsedAt",
  "createdAt",
  "updatedAt",
  "updateId"
from
  "agent_provider_credential"
where
  "userId" = $1
  and "id" = $2::uuid

-- AgentProviderCredentialRepository.delete
delete from "agent_provider_credential"
where
  "userId" = $1
  and "id" = $2::uuid
