-- NOTE: This file is auto generated by ./sql-generator

-- AgentMessageRepository.getBySessionId
select
  "id",
  "sessionId",
  "role",
  "content",
  "providerMessageId",
  "toolCallId",
  "createdAt"
from
  "agent_message"
where
  "sessionId" = $1::uuid
order by
  "createdAt" asc,
  "id" asc
