-- NOTE: This file is auto generated by ./sql-generator

-- AssetFavoriteRepository.addAll
insert into
  "asset_favorite" ("userId", "assetId")
values
  ($1, $2)
on conflict do nothing

-- AssetFavoriteRepository.removeAll
delete from "asset_favorite"
where
  "userId" = $1
  and "assetId" in ($2)

-- AssetFavoriteRepository.mergeOnto
insert into
  "asset_favorite"
select distinct
  "asset_favorite"."userId",
  $1::uuid as "assetId"
from
  "asset_favorite"
where
  "asset_favorite"."assetId" in ($2)
on conflict do nothing
