-- NOTE: This file is auto generated by ./sql-generator

-- CleanupRepository.upsertQuality
begin
insert into
  "asset_quality" (
    "assetId",
    "ownerId",
    "sharpness",
    "brightness",
    "clippedDark",
    "clippedBright",
    "isScreenshot",
    "version"
  )
values
  ($1, $2, $3, $4, $5, $6, $7, $8)
on conflict ("assetId") do update
set
  "sharpness" = $9,
  "brightness" = $10,
  "clippedDark" = $11,
  "clippedBright" = $12,
  "isScreenshot" = $13,
  "version" = $14
rollback

-- CleanupRepository.getForQualityAnalysis
select
  "asset"."id",
  "asset"."ownerId",
  "asset"."type",
  "asset"."originalFileName",
  "asset"."libraryId",
  "asset"."visibility",
  "asset"."deletedAt",
  (
    select
      "asset_file"."path"
    from
      "asset_file"
    where
      "asset_file"."assetId" = "asset"."id"
      and "asset_file"."type" = 'preview'
      and "asset_file"."isEdited" = false
  ) as "previewPath",
  "asset_exif"."make",
  "asset_exif"."model",
  "asset"."width",
  "asset"."height"
from
  "asset"
  left join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
where
  "asset"."id" = $1

-- CleanupRepository.resetQualityAnalyzedAt
update "asset_job_status"
set
  "qualityAnalyzedAt" = $1
where
  "qualityAnalyzedAt" is not null

-- CleanupRepository.getCalendarCounts
select
  (
    (
      extract(
        month
        from
          ("asset"."localDateTime" at time zone 'UTC')
      ) * 100 + extract(
        day
        from
          ("asset"."localDateTime" at time zone 'UTC')
      )
    )::smallint
  ) as "monthDay",
  count(*) as "assetCount"
from
  "asset"
where
  "asset"."deletedAt" is null
  and "asset"."visibility" in ('timeline', 'archive')
  and "asset"."isOffline" = false
  and "asset"."libraryId" is null
  and "asset"."ownerId" = $1
group by
  1

-- CleanupRepository.getDayReviews
select
  "monthDay",
  "reviewedAt"
from
  "cleanup_day_review"
where
  "userId" = $1

-- CleanupRepository.upsertDayReview
insert into
  "cleanup_day_review" ("userId", "monthDay", "reviewedAt")
values
  ($1, $2, $3)
on conflict ("userId", "monthDay") do update
set
  "reviewedAt" = $4

-- CleanupRepository.getRewindYears
select
  extract(
    year
    from
      ("asset"."localDateTime" at time zone 'UTC')
  )::int as "year",
  count(*) as "count"
from
  "asset"
where
  (
    (
      extract(
        month
        from
          ("asset"."localDateTime" at time zone 'UTC')
      ) * 100 + extract(
        day
        from
          ("asset"."localDateTime" at time zone 'UTC')
      )
    )::smallint
  ) = 50
  and "asset"."deletedAt" is null
  and "asset"."visibility" in ('timeline', 'archive')
  and "asset"."isOffline" = false
  and "asset"."libraryId" is null
  and "asset"."ownerId" = $1
group by
  1
order by
  1 desc

-- CleanupRepository.getRewindAssets
select
  "asset"."id",
  "asset"."type",
  "asset"."originalFileName",
  "asset"."localDateTime",
  encode("asset"."thumbhash", 'base64') as "thumbhash",
  coalesce("asset"."width", "asset_exif"."exifImageWidth") as "width",
  coalesce("asset"."height", "asset_exif"."exifImageHeight") as "height",
  "asset"."duration",
  coalesce("asset_exif"."fileSizeInByte", 0) + coalesce(
    (
      select
        e2."fileSizeInByte"
      from
        asset_exif e2
      where
        e2."assetId" = asset."livePhotoVideoId"
    ),
    0
  ) as "fileSize",
  "asset"."isFavorite",
  exists (
    select
      1 as "one"
    from
      "album_asset"
      inner join "album" on "album"."id" = "album_asset"."albumId"
    where
      "album_asset"."assetId" = "asset"."id"
      and "album"."deletedAt" is null
  ) as "inAlbum",
  "asset_exif"."city",
  exists (
    select
      1 as "one"
    from
      "cleanup_decision"
    where
      "cleanup_decision"."assetId" = "asset"."id"
      and "cleanup_decision"."userId" = $1
      and "cleanup_decision"."queue" = 'rewind'
  ) as "kept"
from
  "asset"
  left join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
where
  (
    (
      extract(
        month
        from
          ("asset"."localDateTime" at time zone 'UTC')
      ) * 100 + extract(
        day
        from
          ("asset"."localDateTime" at time zone 'UTC')
      )
    )::smallint
  ) = 50
  and extract(
    year
    from
      ("asset"."localDateTime" at time zone 'UTC')
  ) = $2
  and "asset"."deletedAt" is null
  and "asset"."visibility" in ('timeline', 'archive')
  and "asset"."isOffline" = false
  and "asset"."libraryId" is null
  and "asset"."ownerId" = $3
order by
  "asset"."localDateTime",
  "asset"."id"

-- CleanupRepository.upsertDecisions
insert into
  "cleanup_decision" ("userId", "queue", "assetId", "decision")
values
  ($1, $2, $3, $4)
on conflict ("userId", "queue", "assetId") do nothing

-- CleanupRepository.applyCommitDecisions
begin
update "asset"
set
  "isFavorite" = $1
where
  "id" in ($2)
insert into
  "cleanup_decision" ("userId", "queue", "assetId", "decision")
values
  ($1, $2, $3, $4)
on conflict ("userId", "queue", "assetId") do nothing
rollback

-- CleanupRepository.deleteDecisions
delete from "cleanup_decision"
where
  "userId" = $1
  and "queue" = $2
  and "assetId" in ($3)

-- CleanupRepository.getCommitCandidates
select
  "asset"."id",
  "asset"."ownerId",
  "asset"."deletedAt",
  "asset"."visibility",
  "asset"."isOffline",
  "asset"."libraryId"
from
  "asset"
where
  "asset"."id" in ($1)

-- CleanupRepository.getTrashTotals
select
  count(*) as "count",
  coalesce(sum("asset_exif"."fileSizeInByte"), 0) as "bytes"
from
  "asset"
  left join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
where
  "asset"."ownerId" = $1
  and "asset"."deletedAt" is not null
  and "asset"."status" = $2
  and "asset"."libraryId" is null

-- CleanupRepository.getAssetIdsInSpaces
select
  "asset"."id"
from
  "asset"
where
  "asset"."id" = any ($1::uuid[])
  and "asset"."ownerId" = $2
  and (
    exists (
      select
        1 as "one"
      from
        "shared_space_asset"
      where
        "shared_space_asset"."assetId" = "asset"."id"
    )
    or exists (
      select
        1 as "one"
      from
        "shared_space_album"
        inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
        inner join "album" on "album"."id" = "shared_space_album"."albumId"
      where
        "album_asset"."assetId" = "asset"."id"
        and "album"."deletedAt" is null
    )
  )

-- CleanupRepository.getAnalysedPercent
select
  count(*) as "total",
  count("asset"."id") filter (
    where
      (
        "asset_job_status"."qualityAnalyzedAt" is not null
        and "asset_quality"."version" >= $1
      )
  ) as "analysed"
from
  "asset"
  left join "asset_job_status" on "asset_job_status"."assetId" = "asset"."id"
  left join "asset_quality" on "asset_quality"."assetId" = "asset"."id"
where
  "asset"."deletedAt" is null
  and "asset"."visibility" in ('timeline', 'archive')
  and "asset"."isOffline" = false
  and "asset"."libraryId" is null
  and "asset"."ownerId" = $2

-- CleanupRepository.getSpaceHogs
select
  "asset"."id",
  "asset"."type",
  "asset"."originalFileName",
  "asset"."localDateTime",
  encode("asset"."thumbhash", 'base64') as "thumbhash",
  coalesce("asset"."width", "asset_exif"."exifImageWidth") as "width",
  coalesce("asset"."height", "asset_exif"."exifImageHeight") as "height",
  "asset"."duration",
  coalesce("asset_exif"."fileSizeInByte", 0) + coalesce(
    (
      select
        e2."fileSizeInByte"
      from
        asset_exif e2
      where
        e2."assetId" = asset."livePhotoVideoId"
    ),
    0
  ) as "fileSize",
  "asset"."isFavorite",
  exists (
    select
      1 as "one"
    from
      "album_asset"
      inner join "album" on "album"."id" = "album_asset"."albumId"
    where
      "album_asset"."assetId" = "asset"."id"
      and "album"."deletedAt" is null
  ) as "inAlbum",
  "asset_exif"."city",
  false as "kept",
  "asset_exif"."fileSizeInByte" as "sortKey"
from
  "asset"
  left join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
where
  "asset_exif"."fileSizeInByte" is not null
  and "asset_exif"."fileSizeInByte" >= $1
  and "asset"."deletedAt" is null
  and "asset"."visibility" in ('timeline', 'archive')
  and "asset"."isOffline" = false
  and "asset"."libraryId" is null
  and "asset"."ownerId" = $2
  and (
    "asset"."stackId" is null
    or exists (
      select
        1 as "one"
      from
        "stack"
      where
        "stack"."id" = "asset"."stackId"
        and "stack"."primaryAssetId" = "asset"."id"
    )
  )
  and not exists (
    select
      1 as "one"
    from
      "cleanup_decision"
    where
      "cleanup_decision"."assetId" = "asset"."id"
      and "cleanup_decision"."userId" = $3
      and "cleanup_decision"."queue" = 'space_hogs'
  )
order by
  "asset_exif"."fileSizeInByte" desc,
  "asset"."id" desc
limit
  $4

-- CleanupRepository.getScreenshots
select
  "asset"."id",
  "asset"."type",
  "asset"."originalFileName",
  "asset"."localDateTime",
  encode("asset"."thumbhash", 'base64') as "thumbhash",
  coalesce("asset"."width", "asset_exif"."exifImageWidth") as "width",
  coalesce("asset"."height", "asset_exif"."exifImageHeight") as "height",
  "asset"."duration",
  coalesce("asset_exif"."fileSizeInByte", 0) + coalesce(
    (
      select
        e2."fileSizeInByte"
      from
        asset_exif e2
      where
        e2."assetId" = asset."livePhotoVideoId"
    ),
    0
  ) as "fileSize",
  "asset"."isFavorite",
  exists (
    select
      1 as "one"
    from
      "album_asset"
      inner join "album" on "album"."id" = "album_asset"."albumId"
    where
      "album_asset"."assetId" = "asset"."id"
      and "album"."deletedAt" is null
  ) as "inAlbum",
  "asset_exif"."city",
  false as "kept"
from
  "asset"
  inner join "asset_quality" on "asset_quality"."assetId" = "asset"."id"
  left join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
where
  "asset_quality"."isScreenshot" = true
  and "asset"."deletedAt" is null
  and "asset"."visibility" in ('timeline', 'archive')
  and "asset"."isOffline" = false
  and "asset"."libraryId" is null
  and "asset"."ownerId" = $1
  and (
    "asset"."stackId" is null
    or exists (
      select
        1 as "one"
      from
        "stack"
      where
        "stack"."id" = "asset"."stackId"
        and "stack"."primaryAssetId" = "asset"."id"
    )
  )
  and not exists (
    select
      1 as "one"
    from
      "cleanup_decision"
    where
      "cleanup_decision"."assetId" = "asset"."id"
      and "cleanup_decision"."userId" = $2
      and "cleanup_decision"."queue" = 'screenshots'
  )
order by
  "asset"."localDateTime" desc,
  "asset"."id" desc
limit
  $3

-- CleanupRepository.getBlurry
select
  "asset"."id",
  "asset"."type",
  "asset"."originalFileName",
  "asset"."localDateTime",
  encode("asset"."thumbhash", 'base64') as "thumbhash",
  coalesce("asset"."width", "asset_exif"."exifImageWidth") as "width",
  coalesce("asset"."height", "asset_exif"."exifImageHeight") as "height",
  "asset"."duration",
  coalesce("asset_exif"."fileSizeInByte", 0) + coalesce(
    (
      select
        e2."fileSizeInByte"
      from
        asset_exif e2
      where
        e2."assetId" = asset."livePhotoVideoId"
    ),
    0
  ) as "fileSize",
  "asset"."isFavorite",
  exists (
    select
      1 as "one"
    from
      "album_asset"
      inner join "album" on "album"."id" = "album_asset"."albumId"
    where
      "album_asset"."assetId" = "asset"."id"
      and "album"."deletedAt" is null
  ) as "inAlbum",
  "asset_exif"."city",
  false as "kept",
  "asset_quality"."sharpness",
  case
    when asset_quality.sharpness < $1 then 'blurry'
    when (
      asset_quality.brightness < $2
      and asset_quality."clippedDark" > $3
    ) then 'dark'
    when asset_quality."clippedBright" > $4 then 'bright'
    else null
  end as "reason"
from
  "asset"
  inner join "asset_quality" on "asset_quality"."assetId" = "asset"."id"
  left join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
where
  "asset"."type" = 'IMAGE'
  and (
    asset_quality.sharpness < $5
    or (
      asset_quality.brightness < $6
      and asset_quality."clippedDark" > $7
    )
    or asset_quality."clippedBright" > $8
  )
  and "asset"."deletedAt" is null
  and "asset"."visibility" in ('timeline', 'archive')
  and "asset"."isOffline" = false
  and "asset"."libraryId" is null
  and "asset"."ownerId" = $9
  and (
    "asset"."stackId" is null
    or exists (
      select
        1 as "one"
      from
        "stack"
      where
        "stack"."id" = "asset"."stackId"
        and "stack"."primaryAssetId" = "asset"."id"
    )
  )
  and not exists (
    select
      1 as "one"
    from
      "cleanup_decision"
    where
      "cleanup_decision"."assetId" = "asset"."id"
      and "cleanup_decision"."userId" = $10
      and "cleanup_decision"."queue" = 'blurry'
  )
  and not exists (
    select
      1 as "one"
    from
      "asset_face"
    where
      "asset_face"."assetId" = "asset"."id"
      and "asset_face"."deletedAt" is null
      and "asset_face"."isVisible" is true
  )
order by
  "asset"."localDateTime" desc,
  "asset"."id" desc
limit
  $11

-- CleanupRepository.countQueue
select
  count(*) as "count",
  coalesce(
    sum(
      coalesce("asset_exif"."fileSizeInByte", 0) + coalesce(
        (
          select
            e2."fileSizeInByte"
          from
            asset_exif e2
          where
            e2."assetId" = asset."livePhotoVideoId"
        ),
        0
      )
    ),
    0
  ) as "bytes"
from
  "asset"
  left join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
where
  "asset_exif"."fileSizeInByte" is not null
  and "asset_exif"."fileSizeInByte" >= $1
  and "asset"."deletedAt" is null
  and "asset"."visibility" in ('timeline', 'archive')
  and "asset"."isOffline" = false
  and "asset"."libraryId" is null
  and "asset"."ownerId" = $2
  and (
    "asset"."stackId" is null
    or exists (
      select
        1 as "one"
      from
        "stack"
      where
        "stack"."id" = "asset"."stackId"
        and "stack"."primaryAssetId" = "asset"."id"
    )
  )
  and not exists (
    select
      1 as "one"
    from
      "cleanup_decision"
    where
      "cleanup_decision"."assetId" = "asset"."id"
      and "cleanup_decision"."userId" = $3
      and "cleanup_decision"."queue" = 'space_hogs'
  )

-- CleanupRepository.countDuplicates
with
  "g" as (
    select
      "asset"."duplicateId",
      sum(coalesce("asset_exif"."fileSizeInByte", 0)) - max(coalesce("asset_exif"."fileSizeInByte", 0)) as "reclaim"
    from
      "asset"
      left join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
    where
      "asset"."ownerId" = $1
      and "asset"."duplicateId" is not null
      and "asset"."deletedAt" is null
      and "asset"."visibility" in ('archive', 'timeline')
      and "asset"."stackId" is null
    group by
      "asset"."duplicateId"
    having
      count("asset"."id") > $2
  )
select
  count(*) as "count",
  coalesce(sum("reclaim"), 0) as "bytes"
from
  "g"

-- CleanupRepository.getBurstWindow
select
  "asset"."id",
  "asset"."localDateTime",
  "asset_exif"."autoStackId",
  "asset_quality"."sharpness",
  coalesce("asset_exif"."fileSizeInByte", 0) as "fileSize"
from
  "asset"
  left join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
  left join "asset_quality" on "asset_quality"."assetId" = "asset"."id"
where
  "asset"."type" = 'IMAGE'
  and "asset"."stackId" is null
  and "asset"."deletedAt" is null
  and "asset"."visibility" in ('timeline', 'archive')
  and "asset"."isOffline" = false
  and "asset"."libraryId" is null
  and "asset"."ownerId" = $1
  and not exists (
    select
      1 as "one"
    from
      "cleanup_decision"
    where
      "cleanup_decision"."assetId" = "asset"."id"
      and "cleanup_decision"."userId" = $2
      and "cleanup_decision"."queue" = 'bursts'
  )
order by
  "asset"."localDateTime" asc,
  "asset"."id" asc
limit
  $3

-- CleanupRepository.getBurstClipDistances
select
  p.id,
  (a.embedding <=> b.embedding) as d
from
  unnest($1::uuid[], $2::uuid[]) as p (id, first)
  join smart_search a on a."assetId" = p.id
  join smart_search b on b."assetId" = p.first

-- CleanupRepository.countBursts
with
  "ordered" as (
    select
      "asset"."id" as "id",
      "asset"."localDateTime" as "t",
      "asset_exif"."autoStackId" as "s",
      coalesce("asset_exif"."fileSizeInByte", 0) as "size",
      lag("asset"."localDateTime") over (
        order by
          "asset"."localDateTime",
          "asset"."id"
      ) as "prevT",
      lag("asset_exif"."autoStackId") over (
        order by
          "asset"."localDateTime",
          "asset"."id"
      ) as "prevS"
    from
      "asset"
      left join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
    where
      "asset"."type" = 'IMAGE'
      and "asset"."stackId" is null
      and not exists (
        select
          1 as "one"
        from
          "cleanup_decision"
        where
          "cleanup_decision"."assetId" = "asset"."id"
          and "cleanup_decision"."userId" = $1
          and "cleanup_decision"."queue" = 'bursts'
      )
      and "asset"."deletedAt" is null
      and "asset"."visibility" in ('timeline', 'archive')
      and "asset"."isOffline" = false
      and "asset"."libraryId" is null
      and "asset"."ownerId" = $2
  ),
  "flagged" as (
    select
      "ordered"."id",
      "ordered"."t",
      "ordered"."size",
      case
        when "prevT" is null
        or "t" - "prevT" > interval '2 seconds'
        or "prevS" is distinct from "s" then 1
        else 0
      end as "brk"
    from
      "ordered"
  ),
  "grouped" as (
    select
      "flagged"."id",
      "flagged"."size",
      sum("brk") over (
        order by
          "t",
          "id"
      ) as "grp"
    from
      "flagged"
  ),
  "sized" as (
    select
      "grouped"."grp",
      count("grouped"."id") as "n",
      sum("grouped"."size") as "total",
      max("grouped"."size") as "mx"
    from
      "grouped"
    group by
      "grouped"."grp"
    having
      count("grouped"."id") >= $3
  )
select
  count(*) as "count",
  coalesce(sum("total" - "mx"), 0) as "bytes"
from
  "sized"

-- CleanupRepository.getCleanupAssets
select
  "asset"."id",
  "asset"."type",
  "asset"."originalFileName",
  "asset"."localDateTime",
  encode("asset"."thumbhash", 'base64') as "thumbhash",
  coalesce("asset"."width", "asset_exif"."exifImageWidth") as "width",
  coalesce("asset"."height", "asset_exif"."exifImageHeight") as "height",
  "asset"."duration",
  coalesce("asset_exif"."fileSizeInByte", 0) + coalesce(
    (
      select
        e2."fileSizeInByte"
      from
        asset_exif e2
      where
        e2."assetId" = asset."livePhotoVideoId"
    ),
    0
  ) as "fileSize",
  "asset"."isFavorite",
  exists (
    select
      1 as "one"
    from
      "album_asset"
      inner join "album" on "album"."id" = "album_asset"."albumId"
    where
      "album_asset"."assetId" = "asset"."id"
      and "album"."deletedAt" is null
  ) as "inAlbum",
  "asset_exif"."city",
  exists (
    select
      1 as "one"
    from
      "cleanup_decision"
    where
      "cleanup_decision"."assetId" = "asset"."id"
      and "cleanup_decision"."userId" = $1
      and "cleanup_decision"."queue" = 'bursts'
  ) as "kept"
from
  "asset"
  left join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
where
  "asset"."id" in ($2)
  and "asset"."deletedAt" is null
  and "asset"."visibility" in ('timeline', 'archive')
  and "asset"."isOffline" = false
  and "asset"."libraryId" is null
  and "asset"."ownerId" = $3
  and (
    "asset"."stackId" is null
    or exists (
      select
        1 as "one"
      from
        "stack"
      where
        "stack"."id" = "asset"."stackId"
        and "stack"."primaryAssetId" = "asset"."id"
    )
  )
