-- NOTE: This file is auto generated by ./sql-generator

-- FacePersonVerdictRepository.upsertPending
insert into
  "face_person_verdict" ("personGroupId", "assetFaceId", "distance")
values
  ($1, $2, $3)
on conflict ("personGroupId", "assetFaceId")
where
  "personGroupId" is not null do update
set
  "distance" = "excluded"."distance",
  "updatedAt" = now()
where
  "face_person_verdict"."status" = $4

-- FacePersonVerdictRepository.resolveAssignedFace
delete from "face_person_verdict"
where
  "assetFaceId" = $1
  and "status" = $2

-- FacePersonVerdictRepository.drainPendingForFaces
delete from "face_person_verdict"
where
  "assetFaceId" in ($1)
  and "status" = $2

-- FacePersonVerdictRepository.upsertPendingForSpacePerson
insert into
  "face_person_verdict" ("spacePersonId", "assetFaceId", "distance")
values
  ($1, $2, $3)
on conflict ("spacePersonId", "assetFaceId")
where
  "spacePersonId" is not null do update
set
  "distance" = "excluded"."distance",
  "updatedAt" = now()
where
  "face_person_verdict"."status" = $4

-- FacePersonVerdictRepository.claimPending
delete from "face_person_verdict"
where
  "id" in (
    select
      "fpv"."id" as "id"
    from
      "face_person_verdict" as "fpv"
      inner join "asset_face" as "af" on "af"."id" = "fpv"."assetFaceId"
      inner join "asset" on "asset"."id" = "af"."assetId"
      left join "person" on "person"."personGroupId" = "fpv"."personGroupId"
    where
      "fpv"."personGroupId" = $1
      and "fpv"."assetFaceId" = $2
      and "fpv"."status" = $3
      and "fpv"."distance" > $4
      and "fpv"."distance" <= $5
      and "af"."personGroupId" is null
      and "af"."deletedAt" is null
      and "af"."isVisible" is true
      and "asset"."deletedAt" is null
      and "asset"."isOffline" is false
      and "asset"."visibility" in ($6, $7)
      and not exists (
        select
        from
          "face_identity_face" as "fif"
        where
          "fif"."assetFaceId" = "fpv"."assetFaceId"
          and "fif"."source" = $8
      )
      and not exists (
        select
        from
          "face_person_verdict" as "neg"
        where
          "neg"."assetFaceId" = "fpv"."assetFaceId"
          and "neg"."status" in ($9, $10)
          and (
            "neg"."personGroupId" = $11
            or "neg"."identityId" = "person"."identityId"
          )
      )
  )

-- FacePersonVerdictRepository.claimPendingForSpacePerson
delete from "face_person_verdict"
where
  "id" in (
    select
      "fpv"."id" as "id"
    from
      "face_person_verdict" as "fpv"
      inner join "asset_face" as "af" on "af"."id" = "fpv"."assetFaceId"
      inner join "asset" on "asset"."id" = "af"."assetId"
      left join "shared_space_person" on "shared_space_person"."id" = "fpv"."spacePersonId"
    where
      "fpv"."spacePersonId" = $1
      and "fpv"."assetFaceId" = $2
      and "fpv"."status" = $3
      and "fpv"."distance" > $4
      and "fpv"."distance" <= $5
      and "af"."personGroupId" is null
      and "af"."deletedAt" is null
      and "af"."isVisible" is true
      and "asset"."deletedAt" is null
      and "asset"."isOffline" is false
      and "asset"."visibility" in ($6, $7)
      and not exists (
        select
        from
          "face_identity_face" as "fif"
        where
          "fif"."assetFaceId" = "fpv"."assetFaceId"
          and "fif"."source" = $8
      )
      and not exists (
        select
        from
          "face_person_verdict" as "neg"
        where
          "neg"."assetFaceId" = "fpv"."assetFaceId"
          and "neg"."status" in ($9, $10)
          and (
            "neg"."spacePersonId" = $11
            or "neg"."identityId" = "shared_space_person"."identityId"
          )
      )
  )

-- FacePersonVerdictRepository.markRejected
insert into
  "face_person_verdict" (
    "personGroupId",
    "assetFaceId",
    "identityId",
    "status",
    "source",
    "actorId",
    "distance"
  )
values
  ($1, $2, $3, $4, $5, $6, $7)
on conflict ("personGroupId", "assetFaceId")
where
  "personGroupId" is not null do update
set
  "status" = $8,
  "identityId" = coalesce(
    excluded."identityId",
    "face_person_verdict"."identityId"
  ),
  "source" = $9,
  "actorId" = $10,
  "updatedAt" = now()

-- FacePersonVerdictRepository.markRejectedMany
insert into
  "face_person_verdict" (
    "personGroupId",
    "assetFaceId",
    "identityId",
    "status",
    "source",
    "actorId",
    "distance"
  )
values
  ($1, $2, $3, $4, $5, $6, $7)
on conflict ("personGroupId", "assetFaceId")
where
  "personGroupId" is not null do update
set
  "status" = $8,
  "identityId" = coalesce(
    excluded."identityId",
    "face_person_verdict"."identityId"
  ),
  "source" = $9,
  "actorId" = $10,
  "updatedAt" = now()

-- FacePersonVerdictRepository.markIgnored
insert into
  "face_person_verdict" (
    "personGroupId",
    "assetFaceId",
    "identityId",
    "status",
    "source",
    "actorId",
    "distance"
  )
values
  ($1, $2, $3, $4, $5, $6, $7)
on conflict ("personGroupId", "assetFaceId")
where
  "personGroupId" is not null do update
set
  "status" = $8,
  "identityId" = coalesce(
    excluded."identityId",
    "face_person_verdict"."identityId"
  ),
  "source" = $9,
  "actorId" = $10,
  "updatedAt" = now()

-- FacePersonVerdictRepository.markRejectedForSpacePerson
insert into
  "face_person_verdict" (
    "spacePersonId",
    "assetFaceId",
    "identityId",
    "status",
    "source",
    "actorId",
    "distance"
  )
values
  ($1, $2, $3, $4, $5, $6, $7)
on conflict ("spacePersonId", "assetFaceId")
where
  "spacePersonId" is not null do update
set
  "status" = $8,
  "identityId" = coalesce(
    excluded."identityId",
    "face_person_verdict"."identityId"
  ),
  "source" = $9,
  "actorId" = $10,
  "updatedAt" = now()

-- FacePersonVerdictRepository.markIgnoredForSpacePerson
insert into
  "face_person_verdict" (
    "spacePersonId",
    "assetFaceId",
    "identityId",
    "status",
    "source",
    "actorId",
    "distance"
  )
values
  ($1, $2, $3, $4, $5, $6, $7)
on conflict ("spacePersonId", "assetFaceId")
where
  "spacePersonId" is not null do update
set
  "status" = $8,
  "identityId" = coalesce(
    excluded."identityId",
    "face_person_verdict"."identityId"
  ),
  "source" = $9,
  "actorId" = $10,
  "updatedAt" = now()

-- FacePersonVerdictRepository.listNegativeVerdicts
select
  count(*) as "total"
from
  "face_person_verdict" as "fpv"
where
  "fpv"."status" in ($1, $2)
select
  "fpv"."id" as "id",
  "fpv"."assetFaceId" as "assetFaceId",
  "fpv"."status" as "status",
  "fpv"."source" as "source",
  "fpv"."createdAt" as "createdAt",
  "fpv"."personGroupId" as "personId",
  "person"."name" as "personName",
  "person"."faceAssetId" as "personThumbnailFaceId",
  "fpv"."spacePersonId" as "spacePersonId",
  "ssp"."name" as "spacePersonName",
  "ssp"."representativeFaceId" as "spacePersonThumbnailFaceId",
  "shared_space"."name" as "spaceName",
  "fpv"."actorId" as "actorId",
  "actor"."name" as "actorName"
from
  "face_person_verdict" as "fpv"
  left join "person" on "person"."personGroupId" = "fpv"."personGroupId"
  left join "shared_space_person" as "ssp" on "ssp"."id" = "fpv"."spacePersonId"
  left join "shared_space" on "shared_space"."id" = "ssp"."spaceId"
  left join "user" as "actor" on "actor"."id" = "fpv"."actorId"
where
  "fpv"."status" in ($1, $2)
order by
  "fpv"."createdAt" desc,
  "fpv"."id" desc
limit
  $3
offset
  $4

-- FacePersonVerdictRepository.clearNegativeForTarget
delete from "face_person_verdict"
where
  "assetFaceId" in ($1)
  and "status" in ($2, $3)
  and "face_person_verdict"."personGroupId" = $4

-- FacePersonVerdictRepository.deleteOrphanedVerdicts
delete from "face_person_verdict"
where
  "id" in (
    select
      "id"
    from
      "face_person_verdict"
    where
      "personGroupId" is null
      and "spacePersonId" is null
      and "identityId" is null
    limit
      $1
  )
returning
  "id"

-- FacePersonVerdictRepository.removeVerdicts
delete from "face_person_verdict"
where
  "id" in ($1)
  and "status" in ($2, $3)
returning
  "id"

-- FacePersonVerdictRepository.getNegativeVerdictTokens
select
  "assetFaceId",
  "personGroupId",
  "spacePersonId",
  "identityId"
from
  "face_person_verdict"
where
  "assetFaceId" in ($1)
  and "status" in ($2, $3)

-- FacePersonVerdictRepository.getPendingForPerson
select
  "person"."personGroupId",
  "person"."identityId"
from
  "person"
where
  "person"."personGroupId" = $1
  and "person"."name" != $2
  and "person"."isHidden" = $3
  and "person"."type" = $4

-- FacePersonVerdictRepository.getPendingForSpacePerson
select
  "shared_space_person"."id",
  "shared_space_person"."identityId"
from
  "shared_space_person"
  inner join "shared_space" on "shared_space"."id" = "shared_space_person"."spaceId"
where
  "shared_space_person"."id" = $1
  and "shared_space_person"."spaceId" = $2
  and BTRIM("shared_space_person"."name") <> $3
  and "shared_space_person"."isHidden" is false
  and "shared_space_person"."type" = $4
  and "shared_space"."faceRecognitionEnabled" is true

-- FacePersonVerdictRepository.hasPendingForSpacePerson
select
  "fpv"."assetFaceId"
from
  "face_person_verdict" as "fpv"
  inner join "shared_space_person" on "shared_space_person"."id" = "fpv"."spacePersonId"
  inner join "shared_space" on "shared_space"."id" = "shared_space_person"."spaceId"
  inner join "asset_face" as "af" on "af"."id" = "fpv"."assetFaceId"
  inner join "asset" on "asset"."id" = "af"."assetId"
where
  "fpv"."spacePersonId" = $1
  and "fpv"."assetFaceId" = $2
  and "fpv"."status" = $3
  and "shared_space_person"."spaceId" = $4
  and BTRIM("shared_space_person"."name") <> $5
  and "shared_space_person"."isHidden" is false
  and "shared_space_person"."type" = $6
  and "shared_space"."faceRecognitionEnabled" is true
  and (
    exists (
      select
        1 as "exists"
      from
        "shared_space_asset"
      where
        "shared_space_asset"."assetId" = "asset"."id"
        and "shared_space_asset"."spaceId" = $7::uuid
    )
    or exists (
      select
        1 as "exists"
      from
        "shared_space_library"
      where
        "shared_space_library"."libraryId" = "asset"."libraryId"
        and "shared_space_library"."spaceId" = $8::uuid
    )
    or (
      exists (
        select
          1 as "exists"
        from
          "shared_space_album"
          inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
          inner join "album" on "album"."id" = "shared_space_album"."albumId"
          and "album"."deletedAt" is null
        where
          "album_asset"."assetId" = "asset"."id"
          and "shared_space_album"."spaceId" = $9::uuid
      )
      or exists (
        select
          1 as "exists"
        from
          "shared_space_album"
          inner join "album_space_asset" on "album_space_asset"."albumId" = "shared_space_album"."albumId"
          and "album_space_asset"."spaceId" = "shared_space_album"."spaceId"
          inner join "album" on "album"."id" = "shared_space_album"."albumId"
          and "album"."deletedAt" is null
        where
          "album_space_asset"."assetId" = "asset"."id"
          and "shared_space_album"."spaceId" = $10::uuid
      )
    )
  )
  and "fpv"."distance" > $11
  and "fpv"."distance" <= $12
  and "af"."personGroupId" is null
  and "af"."deletedAt" is null
  and "af"."isVisible" is true
  and "asset"."deletedAt" is null
  and "asset"."isOffline" is false
  and "asset"."visibility" in ($13, $14)
  and not exists (
    select
    from
      "face_identity_face" as "fif"
    where
      "fif"."assetFaceId" = "fpv"."assetFaceId"
      and "fif"."source" = $15
  )
  and not exists (
    select
    from
      "face_person_verdict" as "neg"
    where
      "neg"."assetFaceId" = "fpv"."assetFaceId"
      and "neg"."status" in ($16, $17)
      and (
        "neg"."spacePersonId" = $18
        or "neg"."identityId" = "shared_space_person"."identityId"
      )
  )

-- FacePersonVerdictRepository.isFaceReachableInSpace
select
  "asset_face"."id"
from
  "asset_face"
  inner join "asset" on "asset"."id" = "asset_face"."assetId"
where
  "asset_face"."id" = $1
  and "asset_face"."deletedAt" is null
  and "asset_face"."isVisible" is true
  and "asset"."deletedAt" is null
  and "asset"."isOffline" is false
  and "asset"."visibility" in ($2, $3)
  and (
    exists (
      select
        1 as "exists"
      from
        "shared_space_asset"
      where
        "shared_space_asset"."assetId" = "asset"."id"
        and "shared_space_asset"."spaceId" = $4::uuid
    )
    or exists (
      select
        1 as "exists"
      from
        "shared_space_library"
      where
        "shared_space_library"."libraryId" = "asset"."libraryId"
        and "shared_space_library"."spaceId" = $5::uuid
    )
    or (
      exists (
        select
          1 as "exists"
        from
          "shared_space_album"
          inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
          inner join "album" on "album"."id" = "shared_space_album"."albumId"
          and "album"."deletedAt" is null
        where
          "album_asset"."assetId" = "asset"."id"
          and "shared_space_album"."spaceId" = $6::uuid
      )
      or exists (
        select
          1 as "exists"
        from
          "shared_space_album"
          inner join "album_space_asset" on "album_space_asset"."albumId" = "shared_space_album"."albumId"
          and "album_space_asset"."spaceId" = "shared_space_album"."spaceId"
          inner join "album" on "album"."id" = "shared_space_album"."albumId"
          and "album"."deletedAt" is null
        where
          "album_space_asset"."assetId" = "asset"."id"
          and "shared_space_album"."spaceId" = $7::uuid
      )
    )
  )
