-- NOTE: This file is auto generated by ./sql-generator

-- FaceDissolveRepository.clearFacesRecognizedAt
update "asset_job_status"
set
  "facesRecognizedAt" = $1
where
  "assetId" in (
    select distinct
      "asset_face"."assetId"
    from
      "asset_face"
    where
      "asset_face"."personId" = $2
      and not (
        exists (
          select
            1 as "one"
          from
            "pet_search"
          where
            "pet_search"."faceId" = "asset_face"."id"
        )
        or exists (
          select
            1 as "one"
          from
            "person"
          where
            "person"."id" = "asset_face"."personId"
            and "person"."type" = $3
        )
      )
  )
