-- NOTE: This file is auto generated by ./sql-generator

-- FamilyRepository.getUnion
select
  *
from
  "family_union"
where
  "id" = $1

-- FamilyRepository.deleteUnion
delete from "family_union"
where
  "id" = $1

-- FamilyRepository.getPartnerIds
select
  "identityId"
from
  "family_union_partner"
where
  "unionId" = $1

-- FamilyRepository.getChildIds
select
  "identityId"
from
  "family_union_child"
where
  "unionId" = $1

-- FamilyRepository.addChild
insert into
  "family_union_child" ("unionId", "identityId")
values
  ($1, $2)

-- FamilyRepository.getIdentityType
select
  "type"
from
  "face_identity"
where
  "id" = $1

-- FamilyRepository.isAncestor
WITH RECURSIVE
  ancestors AS (
    SELECT
      partner."identityId" AS id
    FROM
      family_union_child child
      INNER JOIN family_union_partner partner ON partner."unionId" = child."unionId"
    WHERE
      child."identityId" = $1
    UNION
    SELECT
      partner."identityId" AS id
    FROM
      ancestors
      INNER JOIN family_union_child child ON child."identityId" = ancestors.id
      INNER JOIN family_union_partner partner ON partner."unionId" = child."unionId"
  )
SELECT
  EXISTS (
    SELECT
      1
    FROM
      ancestors
    WHERE
      id = $2
  ) AS "exists"
