-- NOTE: This file is auto generated by ./sql-generator

-- FamilyRepository.getAllAccess
select
  *
from
  "family_access"

-- FamilyRepository.setAccess
insert into
  "family_access" ("userId", "level", "grantedById", "grantedAt")
values
  ($1, $2, $3, $4)
on conflict ("userId") do update
set
  "level" = $5,
  "grantedById" = $6,
  "grantedAt" = $7
returning
  *

-- FamilyRepository.deleteAccess
delete from "family_access"
where
  "userId" = $1

-- FamilyRepository.getUnion
select
  *
from
  "family_union"
where
  "id" = $1

-- FamilyRepository.getAllUnionsWithParticipants
SELECT
  family_union.id,
  family_union.status,
  family_union."startDate",
  family_union."endDate",
  COALESCE(partners.ids, ARRAY[]::uuid[]) AS "partnerIds",
  COALESCE(children.ids, ARRAY[]::uuid[]) AS "childIds"
FROM
  family_union
  LEFT JOIN LATERAL (
    SELECT
      array_agg(
        family_union_partner."identityId"
        ORDER BY
          family_union_partner."identityId"
      ) AS ids
    FROM
      family_union_partner
    WHERE
      family_union_partner."unionId" = family_union.id
  ) partners ON true
  LEFT JOIN LATERAL (
    SELECT
      array_agg(
        family_union_child."identityId"
        ORDER BY
          family_union_child."identityId"
      ) AS ids
    FROM
      family_union_child
    WHERE
      family_union_child."unionId" = family_union.id
  ) children ON true
ORDER BY
  family_union.id

-- FamilyRepository.deleteUnion
delete from "family_union"
where
  "id" = $1

-- FamilyRepository.getPartnerIds
select
  "identityId"
from
  "family_union_partner"
where
  "unionId" = $1

-- FamilyRepository.getChildIds
select
  "identityId"
from
  "family_union_child"
where
  "unionId" = $1

-- FamilyRepository.addChild
insert into
  "family_union_child" ("unionId", "identityId")
values
  ($1, $2)

-- FamilyRepository.getIdentityType
select
  "type"
from
  "face_identity"
where
  "id" = $1

-- FamilyRepository.getGenders
select
  "id",
  "gender"
from
  "face_identity"
where
  "id" in ($1)

-- FamilyRepository.setGender
update "face_identity"
set
  "gender" = $1
where
  "id" = $2

-- FamilyRepository.isAncestor
WITH RECURSIVE
  ancestors AS (
    SELECT
      partner."identityId" AS id
    FROM
      family_union_child child
      INNER JOIN family_union_partner partner ON partner."unionId" = child."unionId"
    WHERE
      child."identityId" = $1
    UNION
    SELECT
      partner."identityId" AS id
    FROM
      ancestors
      INNER JOIN family_union_child child ON child."identityId" = ancestors.id
      INNER JOIN family_union_partner partner ON partner."unionId" = child."unionId"
  )
SELECT
  EXISTS (
    SELECT
      1
    FROM
      ancestors
    WHERE
      id = $2
  ) AS "exists"
