-- NOTE: This file is auto generated by ./sql-generator

-- GameRepository.getLocationCandidates
with
  "sample" as (
    select
      "asset"."id" as "assetId",
      "asset_exif"."latitude" as "lat",
      "asset_exif"."longitude" as "lon",
      "asset"."localDateTime" as "takenAt",
      "asset_exif"."country" as "country"
    from
      "asset"
      inner join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
      inner join (
        select
          "shared_space_asset"."assetId" as "assetId"
        from
          "shared_space_asset"
        where
          "shared_space_asset"."spaceId" = $1::uuid
        union
        select
          "asset"."id" as "assetId"
        from
          "asset"
          inner join "shared_space_library" on "shared_space_library"."libraryId" = "asset"."libraryId"
          and "shared_space_library"."spaceId" = $2::uuid
        union
        select
          "album_asset"."assetId" as "assetId"
        from
          "shared_space_album"
          inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
          inner join "album" on "album"."id" = "shared_space_album"."albumId"
          and "album"."deletedAt" is null
        where
          "shared_space_album"."spaceId" = $3::uuid
          and "shared_space_album"."showInTimeline" = $4
        union
        select
          "album_space_asset"."assetId" as "assetId"
        from
          "shared_space_album"
          inner join "album_space_asset" on "album_space_asset"."albumId" = "shared_space_album"."albumId"
          and "album_space_asset"."spaceId" = "shared_space_album"."spaceId"
          inner join "album" on "album"."id" = "shared_space_album"."albumId"
          and "album"."deletedAt" is null
        where
          "shared_space_album"."spaceId" = $5::uuid
          and "shared_space_album"."showInTimeline" = $6
      ) as "space_asset" on "space_asset"."assetId" = "asset"."id"
    where
      "asset"."deletedAt" is null
      and "asset"."type" = $7
      and "asset"."visibility" = $8
      and "asset_exif"."latitude" is not null
      and "asset_exif"."longitude" is not null
    order by
      md5("asset"."id"::text || $9)
    limit
      $10
  )
select
  "sample".*
from
  "sample"
  left join "smart_search" on "smart_search"."assetId" = "sample"."assetId"
where
  not exists (
    select
      1 as "one"
    from
      "asset_face" as "f"
    where
      "f"."assetId" = "sample"."assetId"
      and "f"."deletedAt" is null
      and "f"."isVisible" = $11
    group by
      "f"."assetId"
    having
      sum(
        ("f"."boundingBoxX2" - "f"."boundingBoxX1") * ("f"."boundingBoxY2" - "f"."boundingBoxY1")
      )::double precision / nullif(
        max("f"."imageWidth")::double precision * max("f"."imageHeight"),
        0
      ) > $12
  )
order by
  (smart_search.embedding <=> $13::vector) - (smart_search.embedding <=> $14::vector) desc nulls last,
  md5("sample"."assetId"::text || $15)
limit
  $16

-- GameRepository.getDateCandidates
select
  "asset"."id" as "assetId",
  "asset"."localDateTime" as "takenAt"
from
  "asset"
  inner join (
    select
      "shared_space_asset"."assetId" as "assetId"
    from
      "shared_space_asset"
    where
      "shared_space_asset"."spaceId" = $1::uuid
    union
    select
      "asset"."id" as "assetId"
    from
      "asset"
      inner join "shared_space_library" on "shared_space_library"."libraryId" = "asset"."libraryId"
      and "shared_space_library"."spaceId" = $2::uuid
    union
    select
      "album_asset"."assetId" as "assetId"
    from
      "shared_space_album"
      inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
      inner join "album" on "album"."id" = "shared_space_album"."albumId"
      and "album"."deletedAt" is null
    where
      "shared_space_album"."spaceId" = $3::uuid
      and "shared_space_album"."showInTimeline" = $4
    union
    select
      "album_space_asset"."assetId" as "assetId"
    from
      "shared_space_album"
      inner join "album_space_asset" on "album_space_asset"."albumId" = "shared_space_album"."albumId"
      and "album_space_asset"."spaceId" = "shared_space_album"."spaceId"
      inner join "album" on "album"."id" = "shared_space_album"."albumId"
      and "album"."deletedAt" is null
    where
      "shared_space_album"."spaceId" = $5::uuid
      and "shared_space_album"."showInTimeline" = $6
  ) as "space_asset" on "space_asset"."assetId" = "asset"."id"
where
  "asset"."deletedAt" is null
  and "asset"."type" = $7
  and "asset"."visibility" = $8
  and "asset"."localDateTime" is not null
order by
  md5("asset"."id"::text || $9)
limit
  $10

-- GameRepository.getEligibleRoundAsset
select
  "asset_file"."path" as "previewPath"
from
  "asset"
  inner join "asset_file" on "asset_file"."assetId" = "asset"."id"
  and "asset_file"."type" = $1
where
  "asset"."id" = $2::uuid
  and (
    (
      exists (
        select
          1 as "exists"
        from
          "shared_space_asset"
        where
          "shared_space_asset"."assetId" = "asset"."id"
          and "shared_space_asset"."spaceId" = $3::uuid
      )
      or exists (
        select
          1 as "exists"
        from
          "shared_space_library"
        where
          "shared_space_library"."libraryId" = "asset"."libraryId"
          and "shared_space_library"."spaceId" = $4::uuid
      )
      or (
        exists (
          select
            1 as "exists"
          from
            "shared_space_album"
            inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
            inner join "album" on "album"."id" = "shared_space_album"."albumId"
            and "album"."deletedAt" is null
          where
            "album_asset"."assetId" = "asset"."id"
            and "shared_space_album"."spaceId" = $5::uuid
            and "shared_space_album"."showInTimeline" = $6
        )
        or exists (
          select
            1 as "exists"
          from
            "shared_space_album"
            inner join "album_space_asset" on "album_space_asset"."albumId" = "shared_space_album"."albumId"
            and "album_space_asset"."spaceId" = "shared_space_album"."spaceId"
            inner join "album" on "album"."id" = "shared_space_album"."albumId"
            and "album"."deletedAt" is null
          where
            "album_space_asset"."assetId" = "asset"."id"
            and "shared_space_album"."spaceId" = $7::uuid
            and "shared_space_album"."showInTimeline" = $8
        )
      )
    )
    and "asset"."deletedAt" is null
    and "asset"."type" = $9
    and "asset"."visibility" = $10
  )
order by
  "asset_file"."isEdited" asc
limit
  $11

-- GameRepository.getRecentlyUsedAssetIds
select distinct
  "game_round"."assetId" as "assetId"
from
  "game_round"
where
  "game_round"."challengeId" in (
    select
      "game_challenge"."id"
    from
      "game_challenge"
    where
      "game_challenge"."spaceId" = $1
    order by
      "game_challenge"."createdAt" desc
    limit
      $2
  )
  and "game_round"."assetId" is not null

-- GameRepository.getSoloLocationCandidates (own library only)
with
  "sample" as (
    select
      "asset"."id" as "assetId",
      "asset_exif"."latitude" as "lat",
      "asset_exif"."longitude" as "lon",
      "asset"."localDateTime" as "takenAt",
      "asset_exif"."country" as "country"
    from
      "asset"
      inner join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
      inner join (
        select
          "asset"."id" as "assetId"
        from
          "asset"
        where
          "asset"."ownerId" = $1::uuid
      ) as "pool_asset" on "pool_asset"."assetId" = "asset"."id"
    where
      "asset"."deletedAt" is null
      and "asset"."type" = $2
      and "asset"."visibility" = $3
      and "asset_exif"."latitude" is not null
      and "asset_exif"."longitude" is not null
    order by
      md5("asset"."id"::text || $4)
    limit
      $5
  )
select
  "sample".*
from
  "sample"
  left join "smart_search" on "smart_search"."assetId" = "sample"."assetId"
where
  not exists (
    select
      1 as "one"
    from
      "asset_face" as "f"
    where
      "f"."assetId" = "sample"."assetId"
      and "f"."deletedAt" is null
      and "f"."isVisible" = $6
    group by
      "f"."assetId"
    having
      sum(
        ("f"."boundingBoxX2" - "f"."boundingBoxX1") * ("f"."boundingBoxY2" - "f"."boundingBoxY1")
      )::double precision / nullif(
        max("f"."imageWidth")::double precision * max("f"."imageHeight"),
        0
      ) > $7
  )
order by
  (smart_search.embedding <=> $8::vector) - (smart_search.embedding <=> $9::vector) desc nulls last,
  md5("sample"."assetId"::text || $10)
limit
  $11

-- GameRepository.getSoloLocationCandidates (partners only)
with
  "sample" as (
    select
      "asset"."id" as "assetId",
      "asset_exif"."latitude" as "lat",
      "asset_exif"."longitude" as "lon",
      "asset"."localDateTime" as "takenAt",
      "asset_exif"."country" as "country"
    from
      "asset"
      inner join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
      inner join (
        select
          "asset"."id" as "assetId"
        from
          "asset"
        where
          "asset"."ownerId" = $1::uuid
        union
        select
          "asset"."id" as "assetId"
        from
          "asset"
          inner join "partner" on "partner"."sharedById" = "asset"."ownerId"
          and "partner"."sharedWithId" = $2::uuid
          and "partner"."inTimeline" = $3
      ) as "pool_asset" on "pool_asset"."assetId" = "asset"."id"
    where
      "asset"."deletedAt" is null
      and "asset"."type" = $4
      and "asset"."visibility" = $5
      and "asset_exif"."latitude" is not null
      and "asset_exif"."longitude" is not null
    order by
      md5("asset"."id"::text || $6)
    limit
      $7
  )
select
  "sample".*
from
  "sample"
  left join "smart_search" on "smart_search"."assetId" = "sample"."assetId"
where
  not exists (
    select
      1 as "one"
    from
      "asset_face" as "f"
    where
      "f"."assetId" = "sample"."assetId"
      and "f"."deletedAt" is null
      and "f"."isVisible" = $8
    group by
      "f"."assetId"
    having
      sum(
        ("f"."boundingBoxX2" - "f"."boundingBoxX1") * ("f"."boundingBoxY2" - "f"."boundingBoxY1")
      )::double precision / nullif(
        max("f"."imageWidth")::double precision * max("f"."imageHeight"),
        0
      ) > $9
  )
order by
  (smart_search.embedding <=> $10::vector) - (smart_search.embedding <=> $11::vector) desc nulls last,
  md5("sample"."assetId"::text || $12)
limit
  $13

-- GameRepository.getSoloLocationCandidates (spaces only)
with
  "sample" as (
    select
      "asset"."id" as "assetId",
      "asset_exif"."latitude" as "lat",
      "asset_exif"."longitude" as "lon",
      "asset"."localDateTime" as "takenAt",
      "asset_exif"."country" as "country"
    from
      "asset"
      inner join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
      inner join (
        select
          "asset"."id" as "assetId"
        from
          "asset"
        where
          "asset"."ownerId" = $1::uuid
        union
        select
          "shared_space_asset"."assetId" as "assetId"
        from
          "shared_space_asset"
          inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_asset"."spaceId"
        where
          "shared_space_member"."userId" = $2::uuid
          and "shared_space_member"."showInTimeline" = $3
        union
        select
          "asset"."id" as "assetId"
        from
          "asset"
          inner join "shared_space_library" on "shared_space_library"."libraryId" = "asset"."libraryId"
          inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_library"."spaceId"
        where
          "shared_space_member"."userId" = $4::uuid
          and "shared_space_member"."showInTimeline" = $5
        union
        select
          "album_asset"."assetId" as "assetId"
        from
          "shared_space_album"
          inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
          inner join "album" on "album"."id" = "shared_space_album"."albumId"
          and "album"."deletedAt" is null
          inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_album"."spaceId"
        where
          "shared_space_member"."userId" = $6::uuid
          and "shared_space_member"."showInTimeline" = $7
          and "shared_space_album"."showInTimeline" = $8
        union
        select
          "album_space_asset"."assetId" as "assetId"
        from
          "shared_space_album"
          inner join "album_space_asset" on "album_space_asset"."albumId" = "shared_space_album"."albumId"
          and "album_space_asset"."spaceId" = "shared_space_album"."spaceId"
          inner join "album" on "album"."id" = "shared_space_album"."albumId"
          and "album"."deletedAt" is null
          inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_album"."spaceId"
        where
          "shared_space_member"."userId" = $9::uuid
          and "shared_space_member"."showInTimeline" = $10
          and "shared_space_album"."showInTimeline" = $11
      ) as "pool_asset" on "pool_asset"."assetId" = "asset"."id"
    where
      "asset"."deletedAt" is null
      and "asset"."type" = $12
      and "asset"."visibility" = $13
      and "asset_exif"."latitude" is not null
      and "asset_exif"."longitude" is not null
    order by
      md5("asset"."id"::text || $14)
    limit
      $15
  )
select
  "sample".*
from
  "sample"
  left join "smart_search" on "smart_search"."assetId" = "sample"."assetId"
where
  not exists (
    select
      1 as "one"
    from
      "asset_face" as "f"
    where
      "f"."assetId" = "sample"."assetId"
      and "f"."deletedAt" is null
      and "f"."isVisible" = $16
    group by
      "f"."assetId"
    having
      sum(
        ("f"."boundingBoxX2" - "f"."boundingBoxX1") * ("f"."boundingBoxY2" - "f"."boundingBoxY1")
      )::double precision / nullif(
        max("f"."imageWidth")::double precision * max("f"."imageHeight"),
        0
      ) > $17
  )
order by
  (smart_search.embedding <=> $18::vector) - (smart_search.embedding <=> $19::vector) desc nulls last,
  md5("sample"."assetId"::text || $20)
limit
  $21

-- GameRepository.getSoloLocationCandidates (all sources)
with
  "sample" as (
    select
      "asset"."id" as "assetId",
      "asset_exif"."latitude" as "lat",
      "asset_exif"."longitude" as "lon",
      "asset"."localDateTime" as "takenAt",
      "asset_exif"."country" as "country"
    from
      "asset"
      inner join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
      inner join (
        select
          "asset"."id" as "assetId"
        from
          "asset"
        where
          "asset"."ownerId" = $1::uuid
        union
        select
          "asset"."id" as "assetId"
        from
          "asset"
          inner join "partner" on "partner"."sharedById" = "asset"."ownerId"
          and "partner"."sharedWithId" = $2::uuid
          and "partner"."inTimeline" = $3
        union
        select
          "shared_space_asset"."assetId" as "assetId"
        from
          "shared_space_asset"
          inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_asset"."spaceId"
        where
          "shared_space_member"."userId" = $4::uuid
          and "shared_space_member"."showInTimeline" = $5
        union
        select
          "asset"."id" as "assetId"
        from
          "asset"
          inner join "shared_space_library" on "shared_space_library"."libraryId" = "asset"."libraryId"
          inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_library"."spaceId"
        where
          "shared_space_member"."userId" = $6::uuid
          and "shared_space_member"."showInTimeline" = $7
        union
        select
          "album_asset"."assetId" as "assetId"
        from
          "shared_space_album"
          inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
          inner join "album" on "album"."id" = "shared_space_album"."albumId"
          and "album"."deletedAt" is null
          inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_album"."spaceId"
        where
          "shared_space_member"."userId" = $8::uuid
          and "shared_space_member"."showInTimeline" = $9
          and "shared_space_album"."showInTimeline" = $10
        union
        select
          "album_space_asset"."assetId" as "assetId"
        from
          "shared_space_album"
          inner join "album_space_asset" on "album_space_asset"."albumId" = "shared_space_album"."albumId"
          and "album_space_asset"."spaceId" = "shared_space_album"."spaceId"
          inner join "album" on "album"."id" = "shared_space_album"."albumId"
          and "album"."deletedAt" is null
          inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_album"."spaceId"
        where
          "shared_space_member"."userId" = $11::uuid
          and "shared_space_member"."showInTimeline" = $12
          and "shared_space_album"."showInTimeline" = $13
      ) as "pool_asset" on "pool_asset"."assetId" = "asset"."id"
    where
      "asset"."deletedAt" is null
      and "asset"."type" = $14
      and "asset"."visibility" = $15
      and "asset_exif"."latitude" is not null
      and "asset_exif"."longitude" is not null
    order by
      md5("asset"."id"::text || $16)
    limit
      $17
  )
select
  "sample".*
from
  "sample"
  left join "smart_search" on "smart_search"."assetId" = "sample"."assetId"
where
  not exists (
    select
      1 as "one"
    from
      "asset_face" as "f"
    where
      "f"."assetId" = "sample"."assetId"
      and "f"."deletedAt" is null
      and "f"."isVisible" = $18
    group by
      "f"."assetId"
    having
      sum(
        ("f"."boundingBoxX2" - "f"."boundingBoxX1") * ("f"."boundingBoxY2" - "f"."boundingBoxY1")
      )::double precision / nullif(
        max("f"."imageWidth")::double precision * max("f"."imageHeight"),
        0
      ) > $19
  )
order by
  (smart_search.embedding <=> $20::vector) - (smart_search.embedding <=> $21::vector) desc nulls last,
  md5("sample"."assetId"::text || $22)
limit
  $23

-- GameRepository.getSoloDateCandidates (own library only)
select
  "asset"."id" as "assetId",
  "asset"."localDateTime" as "takenAt"
from
  "asset"
  inner join (
    select
      "asset"."id" as "assetId"
    from
      "asset"
    where
      "asset"."ownerId" = $1::uuid
  ) as "pool_asset" on "pool_asset"."assetId" = "asset"."id"
where
  "asset"."deletedAt" is null
  and "asset"."type" = $2
  and "asset"."visibility" = $3
  and "asset"."localDateTime" is not null
order by
  md5("asset"."id"::text || $4)
limit
  $5

-- GameRepository.getSoloDateCandidates (partners only)
select
  "asset"."id" as "assetId",
  "asset"."localDateTime" as "takenAt"
from
  "asset"
  inner join (
    select
      "asset"."id" as "assetId"
    from
      "asset"
    where
      "asset"."ownerId" = $1::uuid
    union
    select
      "asset"."id" as "assetId"
    from
      "asset"
      inner join "partner" on "partner"."sharedById" = "asset"."ownerId"
      and "partner"."sharedWithId" = $2::uuid
      and "partner"."inTimeline" = $3
  ) as "pool_asset" on "pool_asset"."assetId" = "asset"."id"
where
  "asset"."deletedAt" is null
  and "asset"."type" = $4
  and "asset"."visibility" = $5
  and "asset"."localDateTime" is not null
order by
  md5("asset"."id"::text || $6)
limit
  $7

-- GameRepository.getSoloDateCandidates (spaces only)
select
  "asset"."id" as "assetId",
  "asset"."localDateTime" as "takenAt"
from
  "asset"
  inner join (
    select
      "asset"."id" as "assetId"
    from
      "asset"
    where
      "asset"."ownerId" = $1::uuid
    union
    select
      "shared_space_asset"."assetId" as "assetId"
    from
      "shared_space_asset"
      inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_asset"."spaceId"
    where
      "shared_space_member"."userId" = $2::uuid
      and "shared_space_member"."showInTimeline" = $3
    union
    select
      "asset"."id" as "assetId"
    from
      "asset"
      inner join "shared_space_library" on "shared_space_library"."libraryId" = "asset"."libraryId"
      inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_library"."spaceId"
    where
      "shared_space_member"."userId" = $4::uuid
      and "shared_space_member"."showInTimeline" = $5
    union
    select
      "album_asset"."assetId" as "assetId"
    from
      "shared_space_album"
      inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
      inner join "album" on "album"."id" = "shared_space_album"."albumId"
      and "album"."deletedAt" is null
      inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_album"."spaceId"
    where
      "shared_space_member"."userId" = $6::uuid
      and "shared_space_member"."showInTimeline" = $7
      and "shared_space_album"."showInTimeline" = $8
    union
    select
      "album_space_asset"."assetId" as "assetId"
    from
      "shared_space_album"
      inner join "album_space_asset" on "album_space_asset"."albumId" = "shared_space_album"."albumId"
      and "album_space_asset"."spaceId" = "shared_space_album"."spaceId"
      inner join "album" on "album"."id" = "shared_space_album"."albumId"
      and "album"."deletedAt" is null
      inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_album"."spaceId"
    where
      "shared_space_member"."userId" = $9::uuid
      and "shared_space_member"."showInTimeline" = $10
      and "shared_space_album"."showInTimeline" = $11
  ) as "pool_asset" on "pool_asset"."assetId" = "asset"."id"
where
  "asset"."deletedAt" is null
  and "asset"."type" = $12
  and "asset"."visibility" = $13
  and "asset"."localDateTime" is not null
order by
  md5("asset"."id"::text || $14)
limit
  $15

-- GameRepository.getSoloDateCandidates (all sources)
select
  "asset"."id" as "assetId",
  "asset"."localDateTime" as "takenAt"
from
  "asset"
  inner join (
    select
      "asset"."id" as "assetId"
    from
      "asset"
    where
      "asset"."ownerId" = $1::uuid
    union
    select
      "asset"."id" as "assetId"
    from
      "asset"
      inner join "partner" on "partner"."sharedById" = "asset"."ownerId"
      and "partner"."sharedWithId" = $2::uuid
      and "partner"."inTimeline" = $3
    union
    select
      "shared_space_asset"."assetId" as "assetId"
    from
      "shared_space_asset"
      inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_asset"."spaceId"
    where
      "shared_space_member"."userId" = $4::uuid
      and "shared_space_member"."showInTimeline" = $5
    union
    select
      "asset"."id" as "assetId"
    from
      "asset"
      inner join "shared_space_library" on "shared_space_library"."libraryId" = "asset"."libraryId"
      inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_library"."spaceId"
    where
      "shared_space_member"."userId" = $6::uuid
      and "shared_space_member"."showInTimeline" = $7
    union
    select
      "album_asset"."assetId" as "assetId"
    from
      "shared_space_album"
      inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
      inner join "album" on "album"."id" = "shared_space_album"."albumId"
      and "album"."deletedAt" is null
      inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_album"."spaceId"
    where
      "shared_space_member"."userId" = $8::uuid
      and "shared_space_member"."showInTimeline" = $9
      and "shared_space_album"."showInTimeline" = $10
    union
    select
      "album_space_asset"."assetId" as "assetId"
    from
      "shared_space_album"
      inner join "album_space_asset" on "album_space_asset"."albumId" = "shared_space_album"."albumId"
      and "album_space_asset"."spaceId" = "shared_space_album"."spaceId"
      inner join "album" on "album"."id" = "shared_space_album"."albumId"
      and "album"."deletedAt" is null
      inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_album"."spaceId"
    where
      "shared_space_member"."userId" = $11::uuid
      and "shared_space_member"."showInTimeline" = $12
      and "shared_space_album"."showInTimeline" = $13
  ) as "pool_asset" on "pool_asset"."assetId" = "asset"."id"
where
  "asset"."deletedAt" is null
  and "asset"."type" = $14
  and "asset"."visibility" = $15
  and "asset"."localDateTime" is not null
order by
  md5("asset"."id"::text || $16)
limit
  $17

-- GameRepository.getSoloEligibleRoundAsset (own library only)
select
  "asset_file"."path" as "previewPath"
from
  "asset"
  inner join "asset_file" on "asset_file"."assetId" = "asset"."id"
  and "asset_file"."type" = $1
where
  "asset"."id" = $2::uuid
  and (
    "asset"."deletedAt" is null
    and "asset"."type" = $3
    and "asset"."visibility" = $4
    and "asset"."ownerId" = $5::uuid
  )
order by
  "asset_file"."isEdited" asc
limit
  $6

-- GameRepository.getSoloEligibleRoundAsset (partners only)
select
  "asset_file"."path" as "previewPath"
from
  "asset"
  inner join "asset_file" on "asset_file"."assetId" = "asset"."id"
  and "asset_file"."type" = $1
where
  "asset"."id" = $2::uuid
  and (
    "asset"."deletedAt" is null
    and "asset"."type" = $3
    and "asset"."visibility" = $4
    and (
      "asset"."ownerId" = $5::uuid
      or exists (
        select
          1 as "one"
        from
          "partner"
        where
          "partner"."sharedById" = "asset"."ownerId"
          and "partner"."sharedWithId" = $6::uuid
          and "partner"."inTimeline" = $7
      )
    )
  )
order by
  "asset_file"."isEdited" asc
limit
  $8

-- GameRepository.getSoloEligibleRoundAsset (spaces only)
select
  "asset_file"."path" as "previewPath"
from
  "asset"
  inner join "asset_file" on "asset_file"."assetId" = "asset"."id"
  and "asset_file"."type" = $1
where
  "asset"."id" = $2::uuid
  and (
    "asset"."deletedAt" is null
    and "asset"."type" = $3
    and "asset"."visibility" = $4
    and (
      "asset"."ownerId" = $5::uuid
      or (
        exists (
          select
            1 as "exists"
          from
            "shared_space_asset"
            inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_asset"."spaceId"
          where
            "shared_space_member"."userId" = $6::uuid
            and "shared_space_member"."showInTimeline" = $7
            and "shared_space_asset"."assetId" = "asset"."id"
        )
        or exists (
          select
            1 as "exists"
          from
            "shared_space_library"
            inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_library"."spaceId"
          where
            "shared_space_member"."userId" = $8::uuid
            and "shared_space_member"."showInTimeline" = $9
            and "shared_space_library"."libraryId" = "asset"."libraryId"
        )
        or (
          exists (
            select
              1 as "exists"
            from
              "shared_space_album"
              inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
              inner join "album" on "album"."id" = "shared_space_album"."albumId"
              and "album"."deletedAt" is null
              inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_album"."spaceId"
            where
              "shared_space_member"."userId" = $10::uuid
              and "shared_space_member"."showInTimeline" = $11
              and "album_asset"."assetId" = "asset"."id"
              and "shared_space_album"."showInTimeline" = $12
          )
          or exists (
            select
              1 as "exists"
            from
              "shared_space_album"
              inner join "album_space_asset" on "album_space_asset"."albumId" = "shared_space_album"."albumId"
              and "album_space_asset"."spaceId" = "shared_space_album"."spaceId"
              inner join "album" on "album"."id" = "shared_space_album"."albumId"
              and "album"."deletedAt" is null
              inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_album"."spaceId"
            where
              "shared_space_member"."userId" = $13::uuid
              and "shared_space_member"."showInTimeline" = $14
              and "album_space_asset"."assetId" = "asset"."id"
              and "shared_space_album"."showInTimeline" = $15
          )
        )
      )
    )
  )
order by
  "asset_file"."isEdited" asc
limit
  $16

-- GameRepository.getSoloEligibleRoundAsset (all sources)
select
  "asset_file"."path" as "previewPath"
from
  "asset"
  inner join "asset_file" on "asset_file"."assetId" = "asset"."id"
  and "asset_file"."type" = $1
where
  "asset"."id" = $2::uuid
  and (
    "asset"."deletedAt" is null
    and "asset"."type" = $3
    and "asset"."visibility" = $4
    and (
      "asset"."ownerId" = $5::uuid
      or exists (
        select
          1 as "one"
        from
          "partner"
        where
          "partner"."sharedById" = "asset"."ownerId"
          and "partner"."sharedWithId" = $6::uuid
          and "partner"."inTimeline" = $7
      )
      or (
        exists (
          select
            1 as "exists"
          from
            "shared_space_asset"
            inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_asset"."spaceId"
          where
            "shared_space_member"."userId" = $8::uuid
            and "shared_space_member"."showInTimeline" = $9
            and "shared_space_asset"."assetId" = "asset"."id"
        )
        or exists (
          select
            1 as "exists"
          from
            "shared_space_library"
            inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_library"."spaceId"
          where
            "shared_space_member"."userId" = $10::uuid
            and "shared_space_member"."showInTimeline" = $11
            and "shared_space_library"."libraryId" = "asset"."libraryId"
        )
        or (
          exists (
            select
              1 as "exists"
            from
              "shared_space_album"
              inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
              inner join "album" on "album"."id" = "shared_space_album"."albumId"
              and "album"."deletedAt" is null
              inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_album"."spaceId"
            where
              "shared_space_member"."userId" = $12::uuid
              and "shared_space_member"."showInTimeline" = $13
              and "album_asset"."assetId" = "asset"."id"
              and "shared_space_album"."showInTimeline" = $14
          )
          or exists (
            select
              1 as "exists"
            from
              "shared_space_album"
              inner join "album_space_asset" on "album_space_asset"."albumId" = "shared_space_album"."albumId"
              and "album_space_asset"."spaceId" = "shared_space_album"."spaceId"
              inner join "album" on "album"."id" = "shared_space_album"."albumId"
              and "album"."deletedAt" is null
              inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_album"."spaceId"
            where
              "shared_space_member"."userId" = $15::uuid
              and "shared_space_member"."showInTimeline" = $16
              and "album_space_asset"."assetId" = "asset"."id"
              and "shared_space_album"."showInTimeline" = $17
          )
        )
      )
    )
  )
order by
  "asset_file"."isEdited" asc
limit
  $18

-- GameRepository.getSoloRecentlyUsedAssetIds
select distinct
  "game_round"."assetId" as "assetId"
from
  "game_round"
where
  "game_round"."challengeId" in (
    select
      "game_challenge"."id"
    from
      "game_challenge"
    where
      "game_challenge"."ownerId" = $1
    order by
      "game_challenge"."createdAt" desc
    limit
      $2
  )
  and "game_round"."assetId" is not null

-- GameRepository.getSoloChallengeCount
select
  count(*) as "count"
from
  "game_challenge"
where
  "game_challenge"."ownerId" = $1
  and "game_challenge"."dailyOn" is null

-- GameRepository.createChallenge
begin
insert into
  "game_challenge" (
    "spaceId",
    "createdById",
    "name",
    "roundCount",
    "scaleKm",
    "scaleDays"
  )
values
  ($1, $2, $3, $4, $5, $6)
returning
  "id"
rollback

-- GameRepository.getChallenge
select
  *
from
  "game_challenge"
where
  "id" = $1

-- GameRepository.getChallengesForSpace
select
  *
from
  "game_challenge"
where
  "spaceId" = $1
  and "dailyOn" is null
order by
  "createdAt" desc

-- GameRepository.getDailyChallenge
select
  *
from
  "game_challenge"
where
  "spaceId" = $1
  and "dailyOn" = $2::date

-- GameRepository.getSoloDailyChallenge
select
  *
from
  "game_challenge"
where
  "ownerId" = $1
  and "dailyOn" = $2::date

-- GameRepository.getLocationRoundCounts
select
  "game_round"."challengeId",
  count(*) as "locationCount"
from
  "game_round"
  inner join "game_challenge" on "game_challenge"."id" = "game_round"."challengeId"
where
  "game_challenge"."spaceId" = $1
  and "game_round"."type" = $2
group by
  "game_round"."challengeId"

-- GameRepository.getRounds
select
  *
from
  "game_round"
where
  "challengeId" = $1
order by
  "index" asc

-- GameRepository.getRound
select
  *
from
  "game_round"
where
  "challengeId" = $1
  and "index" = $2

-- GameRepository.getGuessesForUser
select
  "game_guess".*
from
  "game_guess"
  inner join "game_round" on "game_round"."id" = "game_guess"."roundId"
where
  "game_round"."challengeId" = $1
  and "game_guess"."userId" = $2

-- GameRepository.createGuess
insert into
  "game_guess" (
    "roundId",
    "userId",
    "guessLat",
    "guessLon",
    "guessDate",
    "distanceKm",
    "offsetDays",
    "score"
  )
values
  ($1, $2, $3, $4, $5, $6, $7, $8)
returning
  *

-- GameRepository.getLeaderboard
select
  "game_guess"."userId" as "userId",
  sum("game_guess"."score") as "total",
  count("game_guess"."id") as "answered"
from
  "game_guess"
  inner join "game_round" on "game_round"."id" = "game_guess"."roundId"
where
  "game_round"."challengeId" = $1
group by
  "game_guess"."userId"
order by
  "total" desc

-- GameRepository.getMonthlyStandings
select
  "game_guess"."userId" as "userId",
  sum("game_guess"."score") as "total",
  count(distinct "game_round"."challengeId") as "daysPlayed"
from
  "game_guess"
  inner join "game_round" on "game_round"."id" = "game_guess"."roundId"
  inner join "game_challenge" on "game_challenge"."id" = "game_round"."challengeId"
where
  "game_challenge"."spaceId" = $1
  and "game_challenge"."dailyOn" is not null
  and "game_challenge"."dailyOn" >= $2::date
  and "game_challenge"."dailyOn" < $3::date
group by
  "game_guess"."userId"

-- GameRepository.getSoloCompletedDailyDates
select
  to_char("game_challenge"."dailyOn", 'YYYY-MM-DD') as "dailyOn"
from
  "game_challenge"
  inner join "game_round" on "game_round"."challengeId" = "game_challenge"."id"
  inner join "game_guess" on "game_guess"."roundId" = "game_round"."id"
  and "game_guess"."userId" = $1
where
  "game_challenge"."ownerId" = $2
  and "game_challenge"."dailyOn" is not null
group by
  "game_challenge"."id"
having
  count("game_guess"."id") = "game_challenge"."roundCount"

-- GameRepository.getSoloScoreSummary
select
  count(*) as "gamesPlayed",
  max("game_totals"."total") as "bestScore",
  avg("game_totals"."total") as "averageScore"
from
  (
    select
      sum("game_guess"."score") as "total"
    from
      "game_challenge"
      inner join "game_round" on "game_round"."challengeId" = "game_challenge"."id"
      inner join "game_guess" on "game_guess"."roundId" = "game_round"."id"
      and "game_guess"."userId" = $1
    where
      "game_challenge"."ownerId" = $2
    group by
      "game_challenge"."id"
  ) as "game_totals"

-- GameRepository.getSoloHistory
select
  "game_challenge"."id",
  "game_challenge"."name",
  "game_challenge"."roundCount",
  "game_challenge"."createdAt",
  to_char("game_challenge"."dailyOn", 'YYYY-MM-DD') as "dailyOn",
  count("game_guess"."id") as "answered",
  sum("game_guess"."score") as "total"
from
  "game_challenge"
  inner join "game_round" on "game_round"."challengeId" = "game_challenge"."id"
  inner join "game_guess" on "game_guess"."roundId" = "game_round"."id"
  and "game_guess"."userId" = $1
where
  "game_challenge"."ownerId" = $2
group by
  "game_challenge"."id"
order by
  "game_challenge"."createdAt" desc,
  "game_challenge"."id" desc
limit
  $3
offset
  $4

-- GameRepository.deleteChallenge
delete from "game_challenge"
where
  "id" = $1

-- GameRepository.deleteUnplayedChallenges
delete from "game_challenge"
where
  "createdAt" < $1
  and "id" not in (
    select
      "game_round"."challengeId"
    from
      "game_round"
      inner join "game_guess" on "game_guess"."roundId" = "game_round"."id"
  )
