-- NOTE: This file is auto generated by ./sql-generator

-- GameRepository.getLocationCandidates
select
  "asset"."id" as "assetId",
  "asset_exif"."latitude" as "lat",
  "asset_exif"."longitude" as "lon",
  "asset"."localDateTime" as "takenAt",
  "asset_exif"."country" as "country"
from
  "shared_space_asset"
  inner join "asset" on "asset"."id" = "shared_space_asset"."assetId"
  inner join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
  left join (
    select
      "asset_face"."assetId" as "assetId",
      sum(
        (
          "asset_face"."boundingBoxX2" - "asset_face"."boundingBoxX1"
        ) * (
          "asset_face"."boundingBoxY2" - "asset_face"."boundingBoxY1"
        )
      )::double precision / nullif(
        max("asset_face"."imageWidth")::double precision * max("asset_face"."imageHeight"),
        0
      ) as "faceAreaRatio"
    from
      "asset_face"
    where
      "asset_face"."deletedAt" is null
      and "asset_face"."isVisible" = $1
    group by
      "asset_face"."assetId"
  ) as "face_area" on "face_area"."assetId" = "asset"."id"
  left join "smart_search" on "smart_search"."assetId" = "asset"."id"
where
  "shared_space_asset"."spaceId" = $2
  and "asset"."deletedAt" is null
  and "asset"."type" = $3
  and "asset"."visibility" = $4
  and "asset_exif"."latitude" is not null
  and "asset_exif"."longitude" is not null
  and (
    "face_area"."faceAreaRatio" is null
    or "face_area"."faceAreaRatio" <= $5
  )
order by
  (smart_search.embedding <=> $6::vector) - (smart_search.embedding <=> $7::vector) desc nulls last
limit
  $8

-- GameRepository.getDateCandidates
select
  "asset"."id" as "assetId",
  "asset"."localDateTime" as "takenAt"
from
  "shared_space_asset"
  inner join "asset" on "asset"."id" = "shared_space_asset"."assetId"
where
  "shared_space_asset"."spaceId" = $1
  and "asset"."deletedAt" is null
  and "asset"."type" = $2
  and "asset"."visibility" = $3
  and "asset"."localDateTime" is not null
order by
  random()
limit
  $4

-- GameRepository.getRecentlyUsedAssetIds
select distinct
  "game_round"."assetId" as "assetId"
from
  "game_round"
where
  "game_round"."challengeId" in (
    select
      "game_challenge"."id"
    from
      "game_challenge"
    where
      "game_challenge"."spaceId" = $1
    order by
      "game_challenge"."createdAt" desc
    limit
      $2
  )
  and "game_round"."assetId" is not null

-- GameRepository.createChallenge
begin
insert into
  "game_challenge" (
    "spaceId",
    "createdById",
    "name",
    "roundCount",
    "scaleKm",
    "scaleDays"
  )
values
  ($1, $2, $3, $4, $5, $6)
returning
  "id"
rollback

-- GameRepository.getChallenge
select
  *
from
  "game_challenge"
where
  "id" = $1

-- GameRepository.getChallengesForSpace
select
  *
from
  "game_challenge"
where
  "spaceId" = $1
order by
  "createdAt" desc

-- GameRepository.getRounds
select
  *
from
  "game_round"
where
  "challengeId" = $1
order by
  "index" asc

-- GameRepository.getRound
select
  *
from
  "game_round"
where
  "challengeId" = $1
  and "index" = $2

-- GameRepository.getGuessesForUser
select
  "game_guess".*
from
  "game_guess"
  inner join "game_round" on "game_round"."id" = "game_guess"."roundId"
where
  "game_round"."challengeId" = $1
  and "game_guess"."userId" = $2

-- GameRepository.createGuess
insert into
  "game_guess" (
    "roundId",
    "userId",
    "guessLat",
    "guessLon",
    "guessDate",
    "distanceKm",
    "offsetDays",
    "score"
  )
values
  ($1, $2, $3, $4, $5, $6, $7, $8)
returning
  *

-- GameRepository.getLeaderboard
select
  "game_guess"."userId" as "userId",
  sum("game_guess"."score") as "total",
  count("game_guess"."id") as "answered"
from
  "game_guess"
  inner join "game_round" on "game_round"."id" = "game_guess"."roundId"
where
  "game_round"."challengeId" = $1
group by
  "game_guess"."userId"
order by
  "total" desc

-- GameRepository.deleteChallenge
delete from "game_challenge"
where
  "id" = $1
