-- NOTE: This file is auto generated by ./sql-generator

-- GameRepository.getLocationCandidates
with
  "sample" as (
    select
      "asset"."id" as "assetId",
      "asset_exif"."latitude" as "lat",
      "asset_exif"."longitude" as "lon",
      "asset"."localDateTime" as "takenAt",
      "asset_exif"."country" as "country"
    from
      "asset"
      inner join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
      inner join (
        select
          "shared_space_asset"."assetId" as "assetId"
        from
          "shared_space_asset"
        where
          "shared_space_asset"."spaceId" = $1::uuid
        union
        select
          "asset"."id" as "assetId"
        from
          "asset"
          inner join "shared_space_library" on "shared_space_library"."libraryId" = "asset"."libraryId"
          and "shared_space_library"."spaceId" = $2::uuid
        union
        select
          "album_asset"."assetId" as "assetId"
        from
          "shared_space_album"
          inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
          inner join "album" on "album"."id" = "shared_space_album"."albumId"
          and "album"."deletedAt" is null
        where
          "shared_space_album"."spaceId" = $3::uuid
          and "shared_space_album"."showInTimeline" = $4
        union
        select
          "album_space_asset"."assetId" as "assetId"
        from
          "shared_space_album"
          inner join "album_space_asset" on "album_space_asset"."albumId" = "shared_space_album"."albumId"
          and "album_space_asset"."spaceId" = "shared_space_album"."spaceId"
          inner join "album" on "album"."id" = "shared_space_album"."albumId"
          and "album"."deletedAt" is null
        where
          "shared_space_album"."spaceId" = $5::uuid
          and "shared_space_album"."showInTimeline" = $6
      ) as "space_asset" on "space_asset"."assetId" = "asset"."id"
    where
      "asset"."deletedAt" is null
      and "asset"."type" = $7
      and "asset"."visibility" = $8
      and "asset_exif"."latitude" is not null
      and "asset_exif"."longitude" is not null
    order by
      md5("asset"."id"::text || $9)
    limit
      $10
  )
select
  "sample".*
from
  "sample"
  left join "smart_search" on "smart_search"."assetId" = "sample"."assetId"
where
  not exists (
    select
      1 as "one"
    from
      "asset_face" as "f"
    where
      "f"."assetId" = "sample"."assetId"
      and "f"."deletedAt" is null
      and "f"."isVisible" = $11
    group by
      "f"."assetId"
    having
      sum(
        ("f"."boundingBoxX2" - "f"."boundingBoxX1") * ("f"."boundingBoxY2" - "f"."boundingBoxY1")
      )::double precision / nullif(
        max("f"."imageWidth")::double precision * max("f"."imageHeight"),
        0
      ) > $12
  )
order by
  (smart_search.embedding <=> $13::vector) - (smart_search.embedding <=> $14::vector) desc nulls last,
  md5("sample"."assetId"::text || $15)
limit
  $16

-- GameRepository.getDateCandidates
select
  "asset"."id" as "assetId",
  "asset"."localDateTime" as "takenAt"
from
  "asset"
  inner join (
    select
      "shared_space_asset"."assetId" as "assetId"
    from
      "shared_space_asset"
    where
      "shared_space_asset"."spaceId" = $1::uuid
    union
    select
      "asset"."id" as "assetId"
    from
      "asset"
      inner join "shared_space_library" on "shared_space_library"."libraryId" = "asset"."libraryId"
      and "shared_space_library"."spaceId" = $2::uuid
    union
    select
      "album_asset"."assetId" as "assetId"
    from
      "shared_space_album"
      inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
      inner join "album" on "album"."id" = "shared_space_album"."albumId"
      and "album"."deletedAt" is null
    where
      "shared_space_album"."spaceId" = $3::uuid
      and "shared_space_album"."showInTimeline" = $4
    union
    select
      "album_space_asset"."assetId" as "assetId"
    from
      "shared_space_album"
      inner join "album_space_asset" on "album_space_asset"."albumId" = "shared_space_album"."albumId"
      and "album_space_asset"."spaceId" = "shared_space_album"."spaceId"
      inner join "album" on "album"."id" = "shared_space_album"."albumId"
      and "album"."deletedAt" is null
    where
      "shared_space_album"."spaceId" = $5::uuid
      and "shared_space_album"."showInTimeline" = $6
  ) as "space_asset" on "space_asset"."assetId" = "asset"."id"
where
  "asset"."deletedAt" is null
  and "asset"."type" = $7
  and "asset"."visibility" = $8
  and "asset"."localDateTime" is not null
order by
  md5("asset"."id"::text || $9)
limit
  $10

-- GameRepository.getEligibleRoundAsset
select
  "asset_file"."path" as "previewPath"
from
  "asset"
  inner join "asset_file" on "asset_file"."assetId" = "asset"."id"
  and "asset_file"."type" = $1
where
  "asset"."id" = $2::uuid
  and (
    (
      exists (
        select
          1 as "exists"
        from
          "shared_space_asset"
        where
          "shared_space_asset"."assetId" = "asset"."id"
          and "shared_space_asset"."spaceId" = $3::uuid
      )
      or exists (
        select
          1 as "exists"
        from
          "shared_space_library"
        where
          "shared_space_library"."libraryId" = "asset"."libraryId"
          and "shared_space_library"."spaceId" = $4::uuid
      )
      or (
        exists (
          select
            1 as "exists"
          from
            "shared_space_album"
            inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
            inner join "album" on "album"."id" = "shared_space_album"."albumId"
            and "album"."deletedAt" is null
          where
            "album_asset"."assetId" = "asset"."id"
            and "shared_space_album"."spaceId" = $5::uuid
            and "shared_space_album"."showInTimeline" = $6
        )
        or exists (
          select
            1 as "exists"
          from
            "shared_space_album"
            inner join "album_space_asset" on "album_space_asset"."albumId" = "shared_space_album"."albumId"
            and "album_space_asset"."spaceId" = "shared_space_album"."spaceId"
            inner join "album" on "album"."id" = "shared_space_album"."albumId"
            and "album"."deletedAt" is null
          where
            "album_space_asset"."assetId" = "asset"."id"
            and "shared_space_album"."spaceId" = $7::uuid
            and "shared_space_album"."showInTimeline" = $8
        )
      )
    )
    and "asset"."deletedAt" is null
    and "asset"."type" = $9
    and "asset"."visibility" = $10
  )
order by
  "asset_file"."isEdited" asc
limit
  $11

-- GameRepository.getRecentlyUsedAssetIds
select distinct
  "game_round"."assetId" as "assetId"
from
  "game_round"
where
  "game_round"."challengeId" in (
    select
      "game_challenge"."id"
    from
      "game_challenge"
    where
      "game_challenge"."spaceId" = $1
    order by
      "game_challenge"."createdAt" desc
    limit
      $2
  )
  and "game_round"."assetId" is not null

-- GameRepository.createChallenge
begin
insert into
  "game_challenge" (
    "spaceId",
    "createdById",
    "name",
    "roundCount",
    "scaleKm",
    "scaleDays"
  )
values
  ($1, $2, $3, $4, $5, $6)
returning
  "id"
rollback

-- GameRepository.getChallenge
select
  *
from
  "game_challenge"
where
  "id" = $1

-- GameRepository.getChallengesForSpace
select
  *
from
  "game_challenge"
where
  "spaceId" = $1
  and "dailyOn" is null
order by
  "createdAt" desc

-- GameRepository.getDailyChallenge
select
  *
from
  "game_challenge"
where
  "spaceId" = $1
  and "dailyOn" = $2::date

-- GameRepository.getLocationRoundCounts
select
  "game_round"."challengeId",
  count(*) as "locationCount"
from
  "game_round"
  inner join "game_challenge" on "game_challenge"."id" = "game_round"."challengeId"
where
  "game_challenge"."spaceId" = $1
  and "game_round"."type" = $2
group by
  "game_round"."challengeId"

-- GameRepository.getRounds
select
  *
from
  "game_round"
where
  "challengeId" = $1
order by
  "index" asc

-- GameRepository.getRound
select
  *
from
  "game_round"
where
  "challengeId" = $1
  and "index" = $2

-- GameRepository.getGuessesForUser
select
  "game_guess".*
from
  "game_guess"
  inner join "game_round" on "game_round"."id" = "game_guess"."roundId"
where
  "game_round"."challengeId" = $1
  and "game_guess"."userId" = $2

-- GameRepository.createGuess
insert into
  "game_guess" (
    "roundId",
    "userId",
    "guessLat",
    "guessLon",
    "guessDate",
    "distanceKm",
    "offsetDays",
    "score"
  )
values
  ($1, $2, $3, $4, $5, $6, $7, $8)
returning
  *

-- GameRepository.getLeaderboard
select
  "game_guess"."userId" as "userId",
  sum("game_guess"."score") as "total",
  count("game_guess"."id") as "answered"
from
  "game_guess"
  inner join "game_round" on "game_round"."id" = "game_guess"."roundId"
where
  "game_round"."challengeId" = $1
group by
  "game_guess"."userId"
order by
  "total" desc

-- GameRepository.getMonthlyStandings
select
  "game_guess"."userId" as "userId",
  sum("game_guess"."score") as "total",
  count(distinct "game_round"."challengeId") as "daysPlayed"
from
  "game_guess"
  inner join "game_round" on "game_round"."id" = "game_guess"."roundId"
  inner join "game_challenge" on "game_challenge"."id" = "game_round"."challengeId"
where
  "game_challenge"."spaceId" = $1
  and "game_challenge"."dailyOn" is not null
  and "game_challenge"."dailyOn" >= $2::date
  and "game_challenge"."dailyOn" < $3::date
group by
  "game_guess"."userId"

-- GameRepository.deleteChallenge
delete from "game_challenge"
where
  "id" = $1
