-- NOTE: This file is auto generated by ./sql-generator

-- MemoryRuleAssetRepository.getMemoryAssetsForPerson
select distinct
  on ("asset"."id") "asset"."id",
  "asset"."localDateTime"
from
  "asset"
  inner join "asset_face" on "asset_face"."assetId" = "asset"."id"
  inner join "asset_job_status" on "asset_job_status"."assetId" = "asset"."id"
where
  "asset"."ownerId" = $1
  and "asset_face"."personGroupId" = $2
  and "asset_face"."deletedAt" is null
  and "asset_face"."isVisible" is true
  and "asset"."visibility" = $3
  and "asset"."deletedAt" is null
  and "asset"."localDateTime" <= $4
  and exists (
    select
      "asset_file"."assetId"
    from
      "asset_file"
    where
      "asset_file"."assetId" = "asset"."id"
      and "asset_file"."type" = $5
  )
order by
  "asset"."id",
  "asset"."localDateTime" desc
limit
  $6

-- MemoryRuleAssetRepository.getMemoryLocationClusters
select
  "asset_exif"."country" as "country",
  "asset_exif"."city" as "city",
  count(*)::int as "assetCount",
  count(
    distinct (asset."localDateTime" at time zone 'UTC')::date
  )::int as "dayCount",
  min(asset."localDateTime") as "firstDate",
  max(asset."localDateTime") as "lastDate"
from
  "asset"
  inner join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
where
  "asset"."ownerId" = $1
  and "asset"."visibility" = $2
  and "asset"."deletedAt" is null
  and "asset"."localDateTime" >= $3
  and "asset"."localDateTime" <= $4
  and "asset_exif"."country" is not null
  and exists (
    select
      "asset_file"."assetId"
    from
      "asset_file"
    where
      "asset_file"."assetId" = "asset"."id"
      and "asset_file"."type" = $5
  )
group by
  "asset_exif"."country",
  "asset_exif"."city"
order by
  "assetCount" desc

-- MemoryRuleAssetRepository.getMemoryAssetsForLocation
select
  "asset"."id",
  "asset"."localDateTime"
from
  "asset"
  inner join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
where
  "asset"."ownerId" = $1
  and "asset"."visibility" = $2
  and "asset"."deletedAt" is null
  and "asset"."localDateTime" >= $3
  and "asset"."localDateTime" <= $4
  and "asset_exif"."country" = $5
  and "asset_exif"."city" = $6
  and exists (
    select
      "asset_file"."assetId"
    from
      "asset_file"
    where
      "asset_file"."assetId" = "asset"."id"
      and "asset_file"."type" = $7
  )
order by
  "asset"."localDateTime" asc

-- MemoryRuleAssetRepository.getMemoryAssetsForPeriod
select
  "asset"."id",
  "asset"."localDateTime",
  "asset"."type",
  "asset"."duration",
  "asset_exif"."country" as "country",
  "asset_exif"."city" as "city",
  exists (
    select
      1 as "exists"
    from
      "asset_favorite"
    where
      "asset_favorite"."assetId" = "asset"."id"
      and "asset_favorite"."userId" = $1::uuid
  ) as "isFavorite",
  extract(
    year
    from
      (asset."localDateTime" at time zone 'UTC')
  )::int as "year"
from
  "asset"
  left join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
where
  "asset"."ownerId" = $2
  and "asset"."visibility" = $3
  and "asset"."deletedAt" is null
  and "asset"."localDateTime" <= $4
  and extract(
    month
    from
      (asset."localDateTime" at time zone 'UTC')
  )::int in ($5)
  and exists (
    select
      "asset_file"."assetId"
    from
      "asset_file"
    where
      "asset_file"."assetId" = "asset"."id"
      and "asset_file"."type" = $6
  )
order by
  "asset"."localDateTime" asc

-- MemoryRuleAssetRepository.getMemoryFacesForPeriod
select
  "asset"."id" as "assetId",
  "asset"."localDateTime",
  "person"."personGroupId" as "personId",
  "person"."name" as "personName",
  extract(
    year
    from
      (asset."localDateTime" at time zone 'UTC')
  )::int as "year"
from
  "asset"
  inner join "asset_face" on "asset_face"."assetId" = "asset"."id"
  inner join "person" on "person"."personGroupId" = "asset_face"."personGroupId"
where
  "asset"."ownerId" = $1
  and "asset"."visibility" = $2
  and "asset"."deletedAt" is null
  and "asset"."localDateTime" <= $3
  and extract(
    month
    from
      (asset."localDateTime" at time zone 'UTC')
  )::int in ($4)
  and "asset_face"."deletedAt" is null
  and "asset_face"."isVisible" = $5
  and "person"."ownerId" = $6
  and "person"."name" != $7
  and "person"."isHidden" = $8
  and exists (
    select
      "asset_file"."assetId"
    from
      "asset_file"
    where
      "asset_file"."assetId" = "asset"."id"
      and "asset_file"."type" = $9
  )
order by
  "asset"."localDateTime" asc

-- MemoryRuleAssetRepository.getMemoryPersonDailyCounts
select
  "asset_face"."personGroupId" as "personId",
  date_trunc('day', asset."localDateTime" at time zone 'UTC') as "day",
  count(distinct ("asset"."id")) as "count"
from
  "asset"
  inner join "asset_face" on "asset_face"."assetId" = "asset"."id"
where
  "asset"."ownerId" = $1
  and "asset"."visibility" = $2
  and "asset"."deletedAt" is null
  and "asset"."localDateTime" <= $3
  and "asset_face"."personGroupId" in ($4)
  and "asset_face"."deletedAt" is null
  and "asset_face"."isVisible" = $5
  and exists (
    select
      "asset_file"."assetId"
    from
      "asset_file"
    where
      "asset_file"."assetId" = "asset"."id"
      and "asset_file"."type" = $6
  )
group by
  "asset_face"."personGroupId",
  "day"
order by
  "asset_face"."personGroupId",
  "day" asc

-- MemoryRuleAssetRepository.getMemoryAssetsForPersonWindow
select distinct
  on ("asset"."id") "asset"."id",
  "asset"."localDateTime"
from
  "asset"
  inner join "asset_face" on "asset_face"."assetId" = "asset"."id"
where
  "asset"."ownerId" = $1
  and "asset_face"."personGroupId" = $2
  and "asset_face"."deletedAt" is null
  and "asset_face"."isVisible" = $3
  and "asset"."visibility" = $4
  and "asset"."deletedAt" is null
  and "asset"."localDateTime" >= $5
  and "asset"."localDateTime" < $6
  and exists (
    select
      "asset_file"."assetId"
    from
      "asset_file"
    where
      "asset_file"."assetId" = "asset"."id"
      and "asset_file"."type" = $7
  )
order by
  "asset"."id",
  "asset"."localDateTime" asc

-- MemoryRuleAssetRepository.getForOverlapReconcile
select
  "memory"."id",
  "memory"."type",
  "memory"."data",
  "memory"."isSaved",
  "memory"."showAt",
  "memory"."hideAt",
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "asset"."id"
        from
          "asset"
          inner join "memory_asset" on "asset"."id" = "memory_asset"."assetId"
        where
          "memory_asset"."memoriesId" = "memory"."id"
          and "asset"."visibility" = 'timeline'
          and "asset"."deletedAt" is null
          and not exists (
            select
              $1 as "one"
            from
              "asset_face"
              inner join "person" on "person"."personGroupId" = "asset_face"."personGroupId"
              and "person"."ownerId" = "asset"."ownerId"
            where
              "asset_face"."assetId" = "asset"."id"
              and "person"."isHidden" = $2
          )
        order by
          "asset"."localDateTime" asc
      ) as agg
  ) as "assets"
from
  "memory"
where
  "memory"."ownerId" = $3
  and "memory"."deletedAt" is null
  and (
    "memory"."showAt" is null
    or "memory"."showAt" <= $4
  )
  and (
    "memory"."hideAt" is null
    or "memory"."hideAt" >= $5
  )
order by
  "memory"."id"

-- MemoryRuleAssetRepository.getOldestMemoryDate
select
  min(coalesce("showAt", "createdAt")) as "oldest"
from
  "memory"
where
  "deletedAt" is null

-- MemoryRuleAssetRepository.deleteOnThisDay
delete from "memory"
where
  "ownerId" = $1
  and "type" = $2
  and "isSaved" = $3
  and "showAt" = $4
  and memory.data ->> 'year' = $5

-- MemoryRuleAssetRepository.hasRuleMemory
select
  "id"
from
  "memory"
where
  "ownerId" = $1
  and "type" = $2
  and memory.data ->> 'ruleId' = $3
  and memory.data ->> 'dedupeKey' = $4
  and "deletedAt" is null
