-- NOTE: This file is auto generated by ./sql-generator

-- PersonFaceSuggestionRepository.upsertPending
insert into
  "person_face_suggestion" ("personId", "assetFaceId", "distance")
values
  ($1, $2, $3)
on conflict ("personId", "assetFaceId")
where
  "personId" is not null do update
set
  "distance" = "excluded"."distance",
  "updatedAt" = now()
where
  "person_face_suggestion"."status" = $4

-- PersonFaceSuggestionRepository.resolveAssignedFace
delete from "person_face_suggestion"
where
  "assetFaceId" = $1
  and "status" = $2

-- PersonFaceSuggestionRepository.upsertPendingForSpacePerson
insert into
  "person_face_suggestion" ("spacePersonId", "assetFaceId", "distance")
values
  ($1, $2, $3)
on conflict ("spacePersonId", "assetFaceId")
where
  "spacePersonId" is not null do update
set
  "distance" = "excluded"."distance",
  "updatedAt" = now()
where
  "person_face_suggestion"."status" = $4

-- PersonFaceSuggestionRepository.markConfirmed
update "person_face_suggestion"
set
  "status" = $1
where
  "personId" = $2
  and "assetFaceId" = $3
  and "status" = $4

-- PersonFaceSuggestionRepository.markRejected
update "person_face_suggestion"
set
  "status" = $1
where
  "personId" = $2
  and "assetFaceId" = $3
  and "status" = $4

-- PersonFaceSuggestionRepository.markIgnored
update "person_face_suggestion"
set
  "status" = $1
where
  "personId" = $2
  and "assetFaceId" = $3
  and "status" = $4

-- PersonFaceSuggestionRepository.markConfirmedForSpacePerson
update "person_face_suggestion"
set
  "status" = $1
where
  "spacePersonId" = $2
  and "assetFaceId" = $3
  and "status" = $4

-- PersonFaceSuggestionRepository.markRejectedForSpacePerson
update "person_face_suggestion"
set
  "status" = $1
where
  "spacePersonId" = $2
  and "assetFaceId" = $3
  and "status" = $4

-- PersonFaceSuggestionRepository.markIgnoredForSpacePerson
update "person_face_suggestion"
set
  "status" = $1
where
  "spacePersonId" = $2
  and "assetFaceId" = $3
  and "status" = $4

-- PersonFaceSuggestionRepository.getPendingForPerson
select
  "person"."id"
from
  "person"
where
  "person"."id" = $1
  and "person"."name" != $2
  and "person"."isHidden" = $3
  and "person"."type" = $4

-- PersonFaceSuggestionRepository.getPendingForSpacePerson
select
  "shared_space_person"."id"
from
  "shared_space_person"
  inner join "shared_space" on "shared_space"."id" = "shared_space_person"."spaceId"
where
  "shared_space_person"."id" = $1
  and "shared_space_person"."spaceId" = $2
  and BTRIM("shared_space_person"."name") <> $3
  and "shared_space_person"."isHidden" is false
  and "shared_space_person"."type" = $4
  and "shared_space"."faceRecognitionEnabled" is true

-- PersonFaceSuggestionRepository.hasPendingForSpacePerson
select
  "pfs"."assetFaceId"
from
  "person_face_suggestion" as "pfs"
  inner join "shared_space_person" on "shared_space_person"."id" = "pfs"."spacePersonId"
  inner join "shared_space" on "shared_space"."id" = "shared_space_person"."spaceId"
  inner join "asset_face" as "af" on "af"."id" = "pfs"."assetFaceId"
  inner join "asset" on "asset"."id" = "af"."assetId"
where
  "pfs"."spacePersonId" = $1
  and "pfs"."assetFaceId" = $2
  and "pfs"."status" = $3
  and "pfs"."distance" > $4
  and "pfs"."distance" <= $5
  and "shared_space_person"."spaceId" = $6
  and BTRIM("shared_space_person"."name") <> $7
  and "shared_space_person"."isHidden" is false
  and "shared_space_person"."type" = $8
  and "shared_space"."faceRecognitionEnabled" is true
  and "af"."personId" is null
  and "af"."deletedAt" is null
  and "af"."isVisible" is true
  and "asset"."deletedAt" is null
  and "asset"."isOffline" is false
  and "asset"."visibility" in ($9, $10)
  and (
    exists (
      select
        "shared_space_asset"."assetId"
      from
        "shared_space_asset"
      where
        "shared_space_asset"."assetId" = "asset"."id"
        and "shared_space_asset"."spaceId" = $11
    )
    or exists (
      select
        "shared_space_library"."libraryId"
      from
        "shared_space_library"
      where
        "shared_space_library"."libraryId" = "asset"."libraryId"
        and "shared_space_library"."spaceId" = $12
    )
  )
