-- NOTE: This file is auto generated by ./sql-generator

-- PersonFaceSuggestionRepository.upsertPending
insert into
  "person_face_suggestion" ("personId", "assetFaceId", "distance")
values
  ($1, $2, $3)
on conflict ("personId", "assetFaceId") do update
set
  "distance" = "excluded"."distance",
  "updatedAt" = now()
where
  "person_face_suggestion"."status" = $4

-- PersonFaceSuggestionRepository.resolveAssignedFace
delete from "person_face_suggestion"
where
  "assetFaceId" = $1
  and "status" = $2

-- PersonFaceSuggestionRepository.getPendingForPerson
select
  "person"."id"
from
  "person"
where
  "person"."id" = $1
  and "person"."name" != $2
  and "person"."isHidden" = $3
  and "person"."type" = $4
