-- NOTE: This file is auto generated by ./sql-generator

-- PetFaceRepository.getPetFaceForRecognition
select
  "asset_face"."id",
  "asset_face"."assetId",
  "asset_face"."personGroupId",
  (
    select
      to_json(obj)
    from
      (
        select
          "asset"."ownerId"
        from
          "asset"
        where
          "asset"."id" = "asset_face"."assetId"
      ) as obj
  ) as "asset",
  (
    select
      to_json(obj)
    from
      (
        select
          "pet_search".*
        from
          "pet_search"
        where
          "pet_search"."faceId" = "asset_face"."id"
      ) as obj
  ) as "petSearch"
from
  "asset_face"
where
  "asset_face"."id" = $1
  and "asset_face"."deletedAt" is null

-- PetFaceRepository.refreshPetFaces
begin
insert into
  "asset_face" ("id", "assetId")
values
  ($1, $2)
rollback
