-- NOTE: This file is auto generated by ./sql-generator

-- SearchRepository.getEmbedding
select
  "embedding"
from
  "smart_search"
where
  "assetId" = $1

-- SearchRepository.searchMetadata
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  exists (
    select
      1 as "exists"
    from
      "asset_favorite"
    where
      "asset_favorite"."assetId" = "asset"."id"
      and "asset_favorite"."userId" = $1::uuid
  ) as "isFavoriteForUser"
from
  "asset"
  inner join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  "asset_exif"."lensModel" = $2
  and "asset"."ownerId" = any ($3::uuid[])
  and exists (
    select
      1 as "exists"
    from
      "asset_favorite"
    where
      "asset_favorite"."assetId" = "asset"."id"
      and "asset_favorite"."userId" = $4::uuid
  )
  and "asset"."deletedAt" is null
  and "asset"."localDateTime" >= $5
order by
  "asset"."localDateTime" desc,
  "asset"."id" desc
limit
  $6
offset
  $7

-- SearchRepository.searchMetadata (identity-filter)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height"
from
  "asset"
  inner join (
    select
      "asset_face"."assetId"
    from
      "asset_face"
      inner join "face_identity_face" on "face_identity_face"."assetFaceId" = "asset_face"."id"
    where
      "face_identity_face"."identityId" = any ($1::uuid[])
      and "asset_face"."deletedAt" is null
      and "asset_face"."isVisible" is true
    group by
      "asset_face"."assetId"
    having
      count(distinct "face_identity_face"."identityId") = $2
  ) as "has_face_identities" on "has_face_identities"."assetId" = "asset"."id"
where
  (
    "asset"."ownerId" = any ($3::uuid[])
    or (
      "asset"."visibility" in ($4, $5)
      and "asset"."deletedAt" is null
      and (
        exists (
          select
            1 as "exists"
          from
            "shared_space_asset"
          where
            "shared_space_asset"."assetId" = "asset"."id"
            and "shared_space_asset"."spaceId" = any ($6::uuid[])
        )
        or exists (
          select
            1 as "exists"
          from
            "shared_space_library"
          where
            "shared_space_library"."libraryId" = "asset"."libraryId"
            and "shared_space_library"."spaceId" = any ($7::uuid[])
        )
        or (
          exists (
            select
              1 as "exists"
            from
              "shared_space_album"
              inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
              inner join "album" on "album"."id" = "shared_space_album"."albumId"
              and "album"."deletedAt" is null
            where
              "album_asset"."assetId" = "asset"."id"
              and "shared_space_album"."spaceId" = any ($8::uuid[])
              and "shared_space_album"."showInTimeline" = $9
          )
          or exists (
            select
              1 as "exists"
            from
              "shared_space_album"
              inner join "album_space_asset" on "album_space_asset"."albumId" = "shared_space_album"."albumId"
              and "album_space_asset"."spaceId" = "shared_space_album"."spaceId"
              inner join "album" on "album"."id" = "shared_space_album"."albumId"
              and "album"."deletedAt" is null
            where
              "album_space_asset"."assetId" = "asset"."id"
              and "shared_space_album"."spaceId" = any ($10::uuid[])
              and "shared_space_album"."showInTimeline" = $11
          )
        )
      )
    )
  )
  and "asset"."deletedAt" is null
order by
  "asset"."localDateTime" desc,
  "asset"."id" desc
limit
  $12
offset
  $13

-- SearchRepository.searchStatistics
select
  count(*) as "total"
from
  "asset"
  inner join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  "asset_exif"."lensModel" = $1
  and "asset"."ownerId" = any ($2::uuid[])
  and exists (
    select
      1 as "exists"
    from
      "asset_favorite"
    where
      "asset_favorite"."assetId" = "asset"."id"
      and "asset_favorite"."userId" = $3::uuid
  )
  and "asset"."deletedAt" is null
  and "asset"."localDateTime" >= $4

-- SearchRepository.searchRandom
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  exists (
    select
      1 as "exists"
    from
      "asset_favorite"
    where
      "asset_favorite"."assetId" = "asset"."id"
      and "asset_favorite"."userId" = $1::uuid
  ) as "isFavoriteForUser"
from
  "asset"
  inner join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  "asset_exif"."lensModel" = $2
  and "asset"."ownerId" = any ($3::uuid[])
  and exists (
    select
      1 as "exists"
    from
      "asset_favorite"
    where
      "asset_favorite"."assetId" = "asset"."id"
      and "asset_favorite"."userId" = $4::uuid
  )
  and "asset"."deletedAt" is null
  and "asset"."localDateTime" >= $5
order by
  random()
limit
  $6

-- SearchRepository.searchLargeAssets
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  exists (
    select
      1 as "exists"
    from
      "asset_favorite"
    where
      "asset_favorite"."assetId" = "asset"."id"
      and "asset_favorite"."userId" = $1::uuid
  ) as "isFavoriteForUser",
  to_json("asset_exif") as "exifInfo"
from
  "asset"
  inner join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  "asset_exif"."lensModel" = $2
  and "asset"."ownerId" = any ($3::uuid[])
  and exists (
    select
      1 as "exists"
    from
      "asset_favorite"
    where
      "asset_favorite"."assetId" = "asset"."id"
      and "asset_favorite"."userId" = $4::uuid
  )
  and "asset"."deletedAt" is null
  and "asset"."localDateTime" >= $5
  and "asset"."visibility" != 'hidden'
  and "asset_exif"."fileSizeInByte" > $6
order by
  "asset_exif"."fileSizeInByte" desc
limit
  $7

-- SearchRepository.searchSmart
begin
set
  local vchordrq.probes = 1
select
  *
from
  (
    select
      "asset".*,
      exists (
        select
          1 as "exists"
        from
          "asset_favorite"
        where
          "asset_favorite"."assetId" = "asset"."id"
          and "asset_favorite"."userId" = $1::uuid
      ) as "isFavoriteForUser"
    from
      "asset"
      inner join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
      inner join "smart_search" on "asset"."id" = "smart_search"."assetId"
    where
      (
        "asset"."ownerId" = any ($2::uuid[])
        or (
          "asset"."visibility" in ($3, $4)
          and "asset"."deletedAt" is null
          and (
            exists (
              select
                1 as "exists"
              from
                "shared_space_asset"
              where
                "shared_space_asset"."assetId" = "asset"."id"
                and "shared_space_asset"."spaceId" = any ($5::uuid[])
            )
            or exists (
              select
                1 as "exists"
              from
                "shared_space_library"
              where
                "shared_space_library"."libraryId" = "asset"."libraryId"
                and "shared_space_library"."spaceId" = any ($6::uuid[])
            )
            or (
              exists (
                select
                  1 as "exists"
                from
                  "shared_space_album"
                  inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
                  inner join "album" on "album"."id" = "shared_space_album"."albumId"
                  and "album"."deletedAt" is null
                where
                  "album_asset"."assetId" = "asset"."id"
                  and "shared_space_album"."spaceId" = any ($7::uuid[])
                  and "shared_space_album"."showInTimeline" = $8
              )
              or exists (
                select
                  1 as "exists"
                from
                  "shared_space_album"
                  inner join "album_space_asset" on "album_space_asset"."albumId" = "shared_space_album"."albumId"
                  and "album_space_asset"."spaceId" = "shared_space_album"."spaceId"
                  inner join "album" on "album"."id" = "shared_space_album"."albumId"
                  and "album"."deletedAt" is null
                where
                  "album_space_asset"."assetId" = "asset"."id"
                  and "shared_space_album"."spaceId" = any ($9::uuid[])
                  and "shared_space_album"."showInTimeline" = $10
              )
            )
          )
        )
      )
      and exists (
        select
        from
          "shared_space_person_face"
          inner join "asset_face" on "asset_face"."id" = "shared_space_person_face"."assetFaceId"
        where
          "asset_face"."assetId" = "asset"."id"
          and "asset_face"."deletedAt" is null
          and "asset_face"."isVisible" is true
          and "shared_space_person_face"."personId" = $11::uuid
      )
      and "asset_exif"."lensModel" = $12
      and exists (
        select
          1 as "exists"
        from
          "asset_favorite"
        where
          "asset_favorite"."assetId" = "asset"."id"
          and "asset_favorite"."userId" = $13::uuid
      )
      and "asset"."deletedAt" is null
      and "asset"."localDateTime" >= $14
      and (smart_search.embedding <=> $15) <= $16
    order by
      smart_search.embedding <=> $17
    limit
      $18
  ) as "candidates"
order by
  "candidates"."fileCreatedAt" desc nulls last,
  "candidates"."id"
limit
  $19
offset
  $20
commit

-- SearchRepository.searchFaces
begin
set
  local vchordrq.probes = 1
with
  "cte" as (
    select
      "asset_face"."id",
      "asset_face"."personGroupId",
      face_search.embedding <=> $1 as "distance"
    from
      "asset_face"
      inner join "asset" on "asset"."id" = "asset_face"."assetId"
      inner join "face_search" on "face_search"."faceId" = "asset_face"."id"
    where
      "asset"."ownerId" in (
        select
          "user"."id"
        from
          "user"
        where
          "user"."clusterGroupId" = $2
      )
      and "asset"."deletedAt" is null
    order by
      "distance"
    limit
      $3
  )
select
  *
from
  "cte"
where
  "cte"."distance" <= $4
rollback

-- SearchRepository.searchPets
begin
set
  local vchordrq.probes = 1
with
  "cte" as (
    select
      "asset_face"."id",
      "asset_face"."personGroupId",
      pet_search.embedding <=> $1 as "distance"
    from
      "asset_face"
      inner join "asset" on "asset"."id" = "asset_face"."assetId"
      inner join "pet_search" on "pet_search"."faceId" = "asset_face"."id"
    where
      "asset"."ownerId" = any ($2::uuid[])
      and "asset"."deletedAt" is null
    order by
      "distance"
    limit
      $3
  )
select
  *
from
  "cte"
where
  "cte"."distance" <= $4
commit

-- SearchRepository.searchPlaces
select
  *
from
  "geodata_places"
where
  f_unaccent (name) %>> f_unaccent ($1)
  or f_unaccent ("admin2Name") %>> f_unaccent ($2)
  or f_unaccent ("admin1Name") %>> f_unaccent ($3)
  or f_unaccent ("alternateNames") %>> f_unaccent ($4)
order by
  coalesce(f_unaccent (name) <->>> f_unaccent ($5), 0.1) + coalesce(
    f_unaccent ("admin2Name") <->>> f_unaccent ($6),
    0.1
  ) + coalesce(
    f_unaccent ("admin1Name") <->>> f_unaccent ($7),
    0.1
  ) + coalesce(
    f_unaccent ("alternateNames") <->>> f_unaccent ($8),
    0.1
  )
limit
  $9

-- SearchRepository.getAssetsByCity
with recursive
  "cte" as (
    (
      select
        "city",
        "assetId"
      from
        "asset_exif"
        inner join "asset" on "asset"."id" = "asset_exif"."assetId"
      where
        (
          "asset"."ownerId" = any ($1::uuid[])
          or exists (
            select
              1 as "exists"
            from
              "shared_space_asset"
            where
              "shared_space_asset"."assetId" = "asset"."id"
              and "shared_space_asset"."spaceId" = any ($2::uuid[])
          )
          or exists (
            select
              1 as "exists"
            from
              "shared_space_library"
            where
              "shared_space_library"."libraryId" = "asset"."libraryId"
              and "shared_space_library"."spaceId" = any ($3::uuid[])
          )
          or (
            exists (
              select
                1 as "exists"
              from
                "shared_space_album"
                inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
                inner join "album" on "album"."id" = "shared_space_album"."albumId"
                and "album"."deletedAt" is null
              where
                "album_asset"."assetId" = "asset"."id"
                and "shared_space_album"."spaceId" = any ($4::uuid[])
                and "shared_space_album"."showInTimeline" = $5
            )
            or exists (
              select
                1 as "exists"
              from
                "shared_space_album"
                inner join "album_space_asset" on "album_space_asset"."albumId" = "shared_space_album"."albumId"
                and "album_space_asset"."spaceId" = "shared_space_album"."spaceId"
                inner join "album" on "album"."id" = "shared_space_album"."albumId"
                and "album"."deletedAt" is null
              where
                "album_space_asset"."assetId" = "asset"."id"
                and "shared_space_album"."spaceId" = any ($6::uuid[])
                and "shared_space_album"."showInTimeline" = $7
            )
          )
        )
        and "asset"."visibility" = $8
        and "asset"."type" = $9
        and "asset"."deletedAt" is null
      order by
        "city"
      limit
        $10
    )
    union all
    (
      select
        "l"."city",
        "l"."assetId"
      from
        "cte"
        inner join lateral (
          select
            "city",
            "assetId"
          from
            "asset_exif"
            inner join "asset" on "asset"."id" = "asset_exif"."assetId"
          where
            (
              "asset"."ownerId" = any ($11::uuid[])
              or exists (
                select
                  1 as "exists"
                from
                  "shared_space_asset"
                where
                  "shared_space_asset"."assetId" = "asset"."id"
                  and "shared_space_asset"."spaceId" = any ($12::uuid[])
              )
              or exists (
                select
                  1 as "exists"
                from
                  "shared_space_library"
                where
                  "shared_space_library"."libraryId" = "asset"."libraryId"
                  and "shared_space_library"."spaceId" = any ($13::uuid[])
              )
              or (
                exists (
                  select
                    1 as "exists"
                  from
                    "shared_space_album"
                    inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
                    inner join "album" on "album"."id" = "shared_space_album"."albumId"
                    and "album"."deletedAt" is null
                  where
                    "album_asset"."assetId" = "asset"."id"
                    and "shared_space_album"."spaceId" = any ($14::uuid[])
                    and "shared_space_album"."showInTimeline" = $15
                )
                or exists (
                  select
                    1 as "exists"
                  from
                    "shared_space_album"
                    inner join "album_space_asset" on "album_space_asset"."albumId" = "shared_space_album"."albumId"
                    and "album_space_asset"."spaceId" = "shared_space_album"."spaceId"
                    inner join "album" on "album"."id" = "shared_space_album"."albumId"
                    and "album"."deletedAt" is null
                  where
                    "album_space_asset"."assetId" = "asset"."id"
                    and "shared_space_album"."spaceId" = any ($16::uuid[])
                    and "shared_space_album"."showInTimeline" = $17
                )
              )
            )
            and "asset"."visibility" = $18
            and "asset"."type" = $19
            and "asset"."deletedAt" is null
            and "asset_exif"."city" > "cte"."city"
          order by
            "city"
          limit
            $20
        ) as "l" on true
    )
  )
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  to_jsonb("asset_exif") as "exifInfo"
from
  "asset"
  inner join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
  inner join "cte" on "asset"."id" = "cte"."assetId"
order by
  "asset_exif"."city"

-- SearchRepository.getAssetsByCity (with authUserId)
with recursive
  "cte" as (
    (
      select
        "city",
        "assetId"
      from
        "asset_exif"
        inner join "asset" on "asset"."id" = "asset_exif"."assetId"
      where
        (
          "asset"."ownerId" = any ($1::uuid[])
          or exists (
            select
              1 as "exists"
            from
              "shared_space_asset"
            where
              "shared_space_asset"."assetId" = "asset"."id"
              and "shared_space_asset"."spaceId" = any ($2::uuid[])
          )
          or exists (
            select
              1 as "exists"
            from
              "shared_space_library"
            where
              "shared_space_library"."libraryId" = "asset"."libraryId"
              and "shared_space_library"."spaceId" = any ($3::uuid[])
          )
          or (
            exists (
              select
                1 as "exists"
              from
                "shared_space_album"
                inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
                inner join "album" on "album"."id" = "shared_space_album"."albumId"
                and "album"."deletedAt" is null
              where
                "album_asset"."assetId" = "asset"."id"
                and "shared_space_album"."spaceId" = any ($4::uuid[])
                and "shared_space_album"."showInTimeline" = $5
            )
            or exists (
              select
                1 as "exists"
              from
                "shared_space_album"
                inner join "album_space_asset" on "album_space_asset"."albumId" = "shared_space_album"."albumId"
                and "album_space_asset"."spaceId" = "shared_space_album"."spaceId"
                inner join "album" on "album"."id" = "shared_space_album"."albumId"
                and "album"."deletedAt" is null
              where
                "album_space_asset"."assetId" = "asset"."id"
                and "shared_space_album"."spaceId" = any ($6::uuid[])
                and "shared_space_album"."showInTimeline" = $7
            )
          )
        )
        and "asset"."visibility" = $8
        and "asset"."type" = $9
        and "asset"."deletedAt" is null
      order by
        "city"
      limit
        $10
    )
    union all
    (
      select
        "l"."city",
        "l"."assetId"
      from
        "cte"
        inner join lateral (
          select
            "city",
            "assetId"
          from
            "asset_exif"
            inner join "asset" on "asset"."id" = "asset_exif"."assetId"
          where
            (
              "asset"."ownerId" = any ($11::uuid[])
              or exists (
                select
                  1 as "exists"
                from
                  "shared_space_asset"
                where
                  "shared_space_asset"."assetId" = "asset"."id"
                  and "shared_space_asset"."spaceId" = any ($12::uuid[])
              )
              or exists (
                select
                  1 as "exists"
                from
                  "shared_space_library"
                where
                  "shared_space_library"."libraryId" = "asset"."libraryId"
                  and "shared_space_library"."spaceId" = any ($13::uuid[])
              )
              or (
                exists (
                  select
                    1 as "exists"
                  from
                    "shared_space_album"
                    inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
                    inner join "album" on "album"."id" = "shared_space_album"."albumId"
                    and "album"."deletedAt" is null
                  where
                    "album_asset"."assetId" = "asset"."id"
                    and "shared_space_album"."spaceId" = any ($14::uuid[])
                    and "shared_space_album"."showInTimeline" = $15
                )
                or exists (
                  select
                    1 as "exists"
                  from
                    "shared_space_album"
                    inner join "album_space_asset" on "album_space_asset"."albumId" = "shared_space_album"."albumId"
                    and "album_space_asset"."spaceId" = "shared_space_album"."spaceId"
                    inner join "album" on "album"."id" = "shared_space_album"."albumId"
                    and "album"."deletedAt" is null
                  where
                    "album_space_asset"."assetId" = "asset"."id"
                    and "shared_space_album"."spaceId" = any ($16::uuid[])
                    and "shared_space_album"."showInTimeline" = $17
                )
              )
            )
            and "asset"."visibility" = $18
            and "asset"."type" = $19
            and "asset"."deletedAt" is null
            and "asset_exif"."city" > "cte"."city"
          order by
            "city"
          limit
            $20
        ) as "l" on true
    )
  )
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height",
  to_jsonb("asset_exif") as "exifInfo",
  exists (
    select
      1 as "exists"
    from
      "asset_favorite"
    where
      "asset_favorite"."assetId" = "asset"."id"
      and "asset_favorite"."userId" = $21::uuid
  ) as "isFavoriteForUser"
from
  "asset"
  inner join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
  inner join "cte" on "asset"."id" = "cte"."assetId"
order by
  "asset_exif"."city"

-- SearchRepository.getStates
select distinct
  on ("state") "state"
from
  "asset_exif"
  inner join "asset" on "asset"."id" = "asset_exif"."assetId"
where
  "ownerId" = any ($1::uuid[])
  and "visibility" = $2
  and "deletedAt" is null
  and "state" is not null
  and "state" != $3

-- SearchRepository.getCities
select distinct
  on ("city") "city"
from
  "asset_exif"
  inner join "asset" on "asset"."id" = "asset_exif"."assetId"
where
  "ownerId" = any ($1::uuid[])
  and "visibility" = $2
  and "deletedAt" is null
  and "city" is not null
  and "city" != $3

-- SearchRepository.getCameraMakes
select distinct
  on ("make") "make"
from
  "asset_exif"
  inner join "asset" on "asset"."id" = "asset_exif"."assetId"
where
  "ownerId" = any ($1::uuid[])
  and "visibility" = $2
  and "deletedAt" is null
  and "make" is not null
  and "make" != $3

-- SearchRepository.getCameraModels
select distinct
  on ("model") "model"
from
  "asset_exif"
  inner join "asset" on "asset"."id" = "asset_exif"."assetId"
where
  "ownerId" = any ($1::uuid[])
  and "visibility" = $2
  and "deletedAt" is null
  and "model" is not null
  and "model" != $3

-- SearchRepository.getCameraLensModels
select distinct
  on ("lensModel") "lensModel"
from
  "asset_exif"
  inner join "asset" on "asset"."id" = "asset_exif"."assetId"
where
  "ownerId" = any ($1::uuid[])
  and "visibility" = $2
  and "deletedAt" is null
  and "lensModel" is not null
  and "lensModel" != $3

-- SearchRepository.searchMetadataV3 (baseline)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  "asset"."ownerId" = any ($1::uuid[])
  and (
    "asset"."visibility" != $2
    or "asset"."ownerId" = $3
  )
  and true
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $4
offset
  $5

-- SearchRepository.searchMetadataV3 (or-mixed-scope)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  (
    "asset"."visibility" != $1
    or "asset"."ownerId" = $2
  )
  and (
    exists (
      select
      from
        "album_asset"
      where
        "album_asset"."assetId" = "asset"."id"
        and "album_asset"."albumId" = any ($3::uuid[])
    )
    or (
      "asset_exif"."city" = $4
      and "asset"."ownerId" = any ($5::uuid[])
    )
  )
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $6
offset
  $7

-- SearchRepository.searchMetadataV3 (or-exif-only)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  "asset"."ownerId" = any ($1::uuid[])
  and (
    "asset"."visibility" != $2
    or "asset"."ownerId" = $3
  )
  and "asset_exif"."city" = $4
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $5
offset
  $6

-- SearchRepository.searchMetadataV3 (string-eq-null)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  "asset"."ownerId" = any ($1::uuid[])
  and (
    "asset"."visibility" != $2
    or "asset"."ownerId" = $3
  )
  and "asset_exif"."city" is null
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $4
offset
  $5

-- SearchRepository.searchMetadataV3 (string-pattern-like)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  "asset"."ownerId" = any ($1::uuid[])
  and (
    "asset"."visibility" != $2
    or "asset"."ownerId" = $3
  )
  and f_unaccent ("asset_exif"."description") ilike ('%' || f_unaccent ($4) || '%')
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $5
offset
  $6

-- SearchRepository.searchMetadataV3 (string-pattern-notLike)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  "asset"."ownerId" = any ($1::uuid[])
  and (
    "asset"."visibility" != $2
    or "asset"."ownerId" = $3
  )
  and f_unaccent ("asset_exif"."description") not ilike ('%' || f_unaccent ($4) || '%')
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $5
offset
  $6

-- SearchRepository.searchMetadataV3 (string-pattern-startsWith)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  "asset"."ownerId" = any ($1::uuid[])
  and (
    "asset"."visibility" != $2
    or "asset"."ownerId" = $3
  )
  and f_unaccent ("asset"."originalFileName") ilike (f_unaccent ($4) || '%')
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $5
offset
  $6

-- SearchRepository.searchMetadataV3 (string-similarity-ocr)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  "asset"."ownerId" = any ($1::uuid[])
  and (
    "asset"."visibility" != $2
    or "asset"."ownerId" = $3
  )
  and exists (
    select
    from
      "ocr_search"
    where
      "ocr_search"."assetId" = "asset"."id"
      and f_unaccent (ocr_search.text) %>> f_unaccent ($4)
  )
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $5
offset
  $6

-- SearchRepository.searchMetadataV3 (ids-any)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  (
    "asset"."visibility" != $1
    or "asset"."ownerId" = $2
  )
  and exists (
    select
    from
      "album_asset"
    where
      "album_asset"."assetId" = "asset"."id"
      and "album_asset"."albumId" = any ($3::uuid[])
  )
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $4
offset
  $5

-- SearchRepository.searchMetadataV3 (ids-all)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  "asset"."ownerId" = any ($1::uuid[])
  and (
    "asset"."visibility" != $2
    or "asset"."ownerId" = $3
  )
  and exists (
    select
      "asset_face"."assetId"
    from
      "asset_face"
    where
      "asset_face"."assetId" = "asset"."id"
      and "asset_face"."deletedAt" is null
      and "asset_face"."isVisible" = $4
      and "asset_face"."personGroupId" = any ($5::uuid[])
    group by
      "asset_face"."assetId"
    having
      count(distinct "asset_face"."personGroupId") = $6
  )
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $7
offset
  $8

-- SearchRepository.searchMetadataV3 (ids-all-single)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  (
    "asset"."visibility" != $1
    or "asset"."ownerId" = $2
  )
  and exists (
    select
    from
      "album_asset"
    where
      "album_asset"."assetId" = "asset"."id"
      and "album_asset"."albumId" = any ($3::uuid[])
  )
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $4
offset
  $5

-- SearchRepository.searchMetadataV3 (ids-none)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  "asset"."ownerId" = any ($1::uuid[])
  and (
    "asset"."visibility" != $2
    or "asset"."ownerId" = $3
  )
  and not exists (
    select
    from
      "tag_asset"
      inner join "tag_closure" on "tag_asset"."tagId" = "tag_closure"."id_descendant"
    where
      "tag_asset"."assetId" = "asset"."id"
      and "tag_closure"."id_ancestor" = any ($4::uuid[])
  )
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $5
offset
  $6

-- SearchRepository.searchMetadataV3 (ids-tags-all)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  "asset"."ownerId" = any ($1::uuid[])
  and (
    "asset"."visibility" != $2
    or "asset"."ownerId" = $3
  )
  and exists (
    select
      "tag_asset"."assetId"
    from
      "tag_asset"
      inner join "tag_closure" on "tag_asset"."tagId" = "tag_closure"."id_descendant"
    where
      "tag_asset"."assetId" = "asset"."id"
      and "tag_closure"."id_ancestor" = any ($4::uuid[])
    group by
      "tag_asset"."assetId"
    having
      count(distinct "tag_closure"."id_ancestor") = $5
  )
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $6
offset
  $7

-- SearchRepository.searchMetadataV3 (has-albums-false)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  "asset"."ownerId" = any ($1::uuid[])
  and (
    "asset"."visibility" != $2
    or "asset"."ownerId" = $3
  )
  and not exists (
    select
    from
      "album_asset"
    where
      "album_asset"."assetId" = "asset"."id"
  )
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $4
offset
  $5

-- SearchRepository.searchMetadataV3 (is-encoded)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  "asset"."ownerId" = any ($1::uuid[])
  and (
    "asset"."visibility" != $2
    or "asset"."ownerId" = $3
  )
  and exists (
    select
    from
      "asset_file"
    where
      "asset_file"."assetId" = "asset"."id"
      and "asset_file"."type" = $4
  )
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $5
offset
  $6

-- SearchRepository.searchMetadataV3 (number-range)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  "asset"."ownerId" = any ($1::uuid[])
  and (
    "asset"."visibility" != $2
    or "asset"."ownerId" = $3
  )
  and (
    "asset_exif"."fileSizeInByte" <= $4
    and "asset_exif"."fileSizeInByte" >= $5
  )
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $6
offset
  $7

-- SearchRepository.searchMetadataV3 (date-eq)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  "asset"."ownerId" = any ($1::uuid[])
  and (
    "asset"."visibility" != $2
    or "asset"."ownerId" = $3
  )
  and "asset"."fileCreatedAt" = $4
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $5
offset
  $6

-- SearchRepository.searchMetadataV3 (date-range)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  "asset"."ownerId" = any ($1::uuid[])
  and (
    "asset"."visibility" != $2
    or "asset"."ownerId" = $3
  )
  and (
    "asset"."fileCreatedAt" < $4
    and "asset"."fileCreatedAt" >= $5
  )
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $6
offset
  $7

-- SearchRepository.searchMetadataV3 (order-fileSize-noExif)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  "asset"."ownerId" = any ($1::uuid[])
  and (
    "asset"."visibility" != $2
    or "asset"."ownerId" = $3
  )
  and true
order by
  "asset_exif"."fileSizeInByte" desc nulls last,
  "asset"."id" desc
limit
  $4
offset
  $5

-- SearchRepository.searchMetadataV3 (order-rating-withExif)
select
  to_json("asset_exif") as "exifInfo",
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  "asset"."ownerId" = any ($1::uuid[])
  and (
    "asset"."visibility" != $2
    or "asset"."ownerId" = $3
  )
  and true
order by
  "asset_exif"."rating" asc nulls last,
  "asset"."id" asc
limit
  $4
offset
  $5

-- SearchRepository.searchMetadataV3 (or-branches)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  "asset"."ownerId" = any ($1::uuid[])
  and (
    "asset"."visibility" != $2
    or "asset"."ownerId" = $3
  )
  and (
    exists (
      select
        1 as "exists"
      from
        "asset_favorite"
      where
        "asset_favorite"."assetId" = "asset"."id"
        and "asset_favorite"."userId" = $4::uuid
    )
    or exists (
      select
      from
        "asset_face"
      where
        "asset_face"."assetId" = "asset"."id"
        and "asset_face"."deletedAt" is null
        and "asset_face"."isVisible" = $5
        and "asset_face"."personGroupId" = any ($6::uuid[])
    )
  )
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $7
offset
  $8

-- SearchRepository.searchMetadataV3 (or-with-top-level)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  (
    "asset"."visibility" != $1
    or "asset"."ownerId" = $2
  )
  and (
    "asset"."fileCreatedAt" < $3
    and "asset"."fileCreatedAt" >= $4
    and (
      (
        exists (
          select
            1 as "exists"
          from
            "asset_favorite"
          where
            "asset_favorite"."assetId" = "asset"."id"
            and "asset_favorite"."userId" = $5::uuid
        )
        and "asset"."ownerId" = any ($6::uuid[])
      )
      or exists (
        select
        from
          "album_asset"
        where
          "album_asset"."assetId" = "asset"."id"
          and "album_asset"."albumId" = any ($7::uuid[])
      )
    )
  )
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $8
offset
  $9

-- SearchRepository.searchMetadataV3 (cursor-offset)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  "asset"."ownerId" = any ($1::uuid[])
  and (
    "asset"."visibility" != $2
    or "asset"."ownerId" = $3
  )
  and exists (
    select
      1 as "exists"
    from
      "asset_favorite"
    where
      "asset_favorite"."assetId" = "asset"."id"
      and "asset_favorite"."userId" = $4::uuid
  )
order by
  "asset"."fileCreatedAt" desc,
  "asset"."id" desc
limit
  $5
offset
  $6

-- SearchRepository.searchRandomV3 (baseline)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  "asset"."ownerId" = any ($1::uuid[])
  and (
    "asset"."visibility" != $2
    or "asset"."ownerId" = $3
  )
  and true
order by
  random()
limit
  $4

-- SearchRepository.searchRandomV3 (with-filter)
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  "asset"."ownerId" = any ($1::uuid[])
  and (
    "asset"."visibility" != $2
    or "asset"."ownerId" = $3
  )
  and exists (
    select
      1 as "exists"
    from
      "asset_favorite"
    where
      "asset_favorite"."assetId" = "asset"."id"
      and "asset_favorite"."userId" = $4::uuid
  )
order by
  random()
limit
  $5

-- SearchRepository.searchSmartV3 (baseline)
begin
set
  local vchordrq.probes = 1
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
  inner join "smart_search" on "asset"."id" = "smart_search"."assetId"
where
  "asset"."ownerId" = any ($1::uuid[])
  and (
    "asset"."visibility" != $2
    or "asset"."ownerId" = $3
  )
  and true
order by
  smart_search.embedding <=> $4,
  "asset"."id" asc
limit
  $5
offset
  $6
commit

-- SearchRepository.searchSmartV3 (with-filter)
begin
set
  local vchordrq.probes = 1
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
  inner join "smart_search" on "asset"."id" = "smart_search"."assetId"
where
  "asset"."ownerId" = any ($1::uuid[])
  and (
    "asset"."visibility" != $2
    or "asset"."ownerId" = $3
  )
  and (
    "asset"."fileCreatedAt" < $4
    and "asset"."fileCreatedAt" >= $5
  )
order by
  smart_search.embedding <=> $6,
  "asset"."id" asc
limit
  $7
offset
  $8
commit

-- SearchRepository.searchSmartV3 (cursor-offset)
begin
set
  local vchordrq.probes = 1
select
  "asset"."id",
  "asset"."updateId",
  "asset"."createdAt",
  "asset"."updatedAt",
  "asset"."deletedAt",
  "asset"."status",
  "asset"."checksum",
  "asset"."checksumAlgorithm",
  "asset"."duplicateId",
  "asset"."duration",
  "asset"."fileCreatedAt",
  "asset"."fileModifiedAt",
  "asset"."isExternal",
  "asset"."isOffline",
  "asset"."isEdited",
  "asset"."visibility",
  "asset"."libraryId",
  "asset"."livePhotoVideoId",
  "asset"."localDateTime",
  "asset"."originalFileName",
  "asset"."originalPath",
  "asset"."ownerId",
  "asset"."stackId",
  "asset"."thumbhash",
  "asset"."type",
  "asset"."width",
  "asset"."height"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
  inner join "smart_search" on "asset"."id" = "smart_search"."assetId"
where
  "asset"."ownerId" = any ($1::uuid[])
  and (
    "asset"."visibility" != $2
    or "asset"."ownerId" = $3
  )
  and true
order by
  smart_search.embedding <=> $4,
  "asset"."id" asc
limit
  $5
offset
  $6
commit

-- SearchRepository.searchStatisticsV3 (baseline)
select
  count(*) as "total"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  "asset"."ownerId" = any ($1::uuid[])
  and (
    "asset"."visibility" != $2
    or "asset"."ownerId" = $3
  )
  and true

-- SearchRepository.searchStatisticsV3 (with-filter)
select
  count(*) as "total"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  "asset"."ownerId" = any ($1::uuid[])
  and (
    "asset"."visibility" != $2
    or "asset"."ownerId" = $3
  )
  and (
    "asset_exif"."fileSizeInByte" >= $4
    and "asset"."fileCreatedAt" < $5
    and "asset"."fileCreatedAt" >= $6
  )

-- SearchRepository.searchStatisticsV3 (with-or)
select
  count(*) as "total"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  "asset"."ownerId" = any ($1::uuid[])
  and (
    "asset"."visibility" != $2
    or "asset"."ownerId" = $3
  )
  and (
    exists (
      select
        1 as "exists"
      from
        "asset_favorite"
      where
        "asset_favorite"."assetId" = "asset"."id"
        and "asset_favorite"."userId" = $4::uuid
    )
    or not exists (
      select
      from
        "album_asset"
      where
        "album_asset"."assetId" = "asset"."id"
    )
  )
