-- NOTE: This file is auto generated by ./sql-generator

-- SharedSpaceRepository.getById
select
  *
from
  "shared_space"
where
  "id" = $1

-- SharedSpaceRepository.getAllByUserId
select
  "shared_space".*
from
  "shared_space"
  inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space"."id"
where
  "shared_space_member"."userId" = $1

-- SharedSpaceRepository.update
update "shared_space"
set
  "name" = $1
where
  "id" = $2
returning
  *

-- SharedSpaceRepository.remove
delete from "shared_space"
where
  "id" = $1

-- SharedSpaceRepository.getMembers
select
  "shared_space_member"."spaceId",
  "shared_space_member"."userId",
  "shared_space_member"."role",
  "shared_space_member"."joinedAt",
  "user"."name",
  "user"."email",
  "user"."profileImagePath",
  "user"."profileChangedAt",
  "user"."avatarColor"
from
  "shared_space_member"
  inner join "user" on "user"."id" = "shared_space_member"."userId"
  and "user"."deletedAt" is null
where
  "shared_space_member"."spaceId" = $1

-- SharedSpaceRepository.getMember
select
  "shared_space_member"."spaceId",
  "shared_space_member"."userId",
  "shared_space_member"."role",
  "shared_space_member"."joinedAt",
  "user"."name",
  "user"."email",
  "user"."profileImagePath",
  "user"."profileChangedAt",
  "user"."avatarColor"
from
  "shared_space_member"
  inner join "user" on "user"."id" = "shared_space_member"."userId"
  and "user"."deletedAt" is null
where
  "shared_space_member"."spaceId" = $1
  and "shared_space_member"."userId" = $2

-- SharedSpaceRepository.updateMember
update "shared_space_member"
set
  "role" = $1
where
  "spaceId" = $2
  and "userId" = $3
returning
  *

-- SharedSpaceRepository.removeMember
delete from "shared_space_member"
where
  "spaceId" = $1
  and "userId" = $2

-- SharedSpaceRepository.getAssetCount
select
  count(*) as "count"
from
  "shared_space_asset"
where
  "spaceId" = $1

-- SharedSpaceRepository.removeAssets
delete from "shared_space_asset"
where
  "spaceId" = $1
  and "assetId" in ($2)
