-- NOTE: This file is auto generated by ./sql-generator

-- SharedSpaceRepository.getById
select
  *
from
  "shared_space"
where
  "id" = $1

-- SharedSpaceRepository.getAllByUserId
select
  "shared_space".*
from
  "shared_space"
  inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space"."id"
where
  "shared_space_member"."userId" = $1

-- SharedSpaceRepository.update
update "shared_space"
set
  "name" = $1
where
  "id" = $2
returning
  *

-- SharedSpaceRepository.remove
delete from "shared_space"
where
  "id" = $1

-- SharedSpaceRepository.getMembers
select
  "shared_space_member"."spaceId",
  "shared_space_member"."userId",
  "shared_space_member"."role",
  "shared_space_member"."joinedAt",
  "shared_space_member"."showInTimeline",
  "shared_space_member"."sharePersonMetadata",
  "shared_space_member"."lastViewedAt",
  "user"."name",
  "user"."email",
  "user"."profileImagePath",
  "user"."profileChangedAt",
  "user"."avatarColor"
from
  "shared_space_member"
  inner join "user" on "user"."id" = "shared_space_member"."userId"
  and "user"."deletedAt" is null
where
  "shared_space_member"."spaceId" = $1

-- SharedSpaceRepository.getMember
select
  "shared_space_member"."spaceId",
  "shared_space_member"."userId",
  "shared_space_member"."role",
  "shared_space_member"."joinedAt",
  "shared_space_member"."showInTimeline",
  "shared_space_member"."sharePersonMetadata",
  "shared_space_member"."lastViewedAt",
  "user"."name",
  "user"."email",
  "user"."profileImagePath",
  "user"."profileChangedAt",
  "user"."avatarColor"
from
  "shared_space_member"
  inner join "user" on "user"."id" = "shared_space_member"."userId"
  and "user"."deletedAt" is null
where
  "shared_space_member"."spaceId" = $1
  and "shared_space_member"."userId" = $2

-- SharedSpaceRepository.updateMember
update "shared_space_member"
set
  "role" = $1
where
  "spaceId" = $2
  and "userId" = $3
returning
  *

-- SharedSpaceRepository.removeMember
delete from "shared_space_member"
where
  "spaceId" = $1
  and "userId" = $2

-- SharedSpaceRepository.getContributableAssetSpaces
select distinct
  on ("asset"."id") "asset"."id" as "assetId",
  "link"."spaceId" as "spaceId"
from
  "shared_space_album" as "link"
  inner join "shared_space_member" as "m" on "m"."spaceId" = "link"."spaceId"
  and "m"."userId" = $1
  and "m"."role" in ($2, $3)
  inner join "asset" on "asset"."id" in ($4)
  and "asset"."deletedAt" is null
  and "asset"."ownerId" != $5
  and "asset"."visibility" in ($6, $7)
where
  "link"."albumId" = $8
  and (
    exists (
      select
        1 as "x"
      from
        "shared_space_asset" as "sd"
      where
        "sd"."spaceId" = "link"."spaceId"
        and "sd"."assetId" = "asset"."id"
    )
    or exists (
      select
        1 as "x"
      from
        "shared_space_library" as "sl"
      where
        "sl"."spaceId" = "link"."spaceId"
        and "sl"."libraryId" = "asset"."libraryId"
        and "asset"."isOffline" = $9
    )
    or exists (
      select
        1 as "x"
      from
        "shared_space_album" as "sa2"
        inner join "album_asset" as "aa2" on "aa2"."albumId" = "sa2"."albumId"
        inner join "album" as "al2" on "al2"."id" = "sa2"."albumId"
        and "al2"."deletedAt" is null
      where
        "sa2"."spaceId" = "link"."spaceId"
        and "aa2"."assetId" = "asset"."id"
    )
  )
order by
  "asset"."id"

-- SharedSpaceRepository.getMemberSpaceIdsLinkingAlbum
select
  "shared_space_album"."spaceId"
from
  "shared_space_album"
  inner join "album" on "album"."id" = "shared_space_album"."albumId"
  and "album"."deletedAt" is null
  inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_album"."spaceId"
where
  "shared_space_album"."albumId" = $1
  and "shared_space_member"."userId" = $2

-- SharedSpaceRepository.getSpaceIdsForTimeline
select
  "spaceId"
from
  "shared_space_member"
where
  "userId" = $1
  and "showInTimeline" = $2

-- SharedSpaceRepository.getSpaceIdsWithFaceRecognitionEnabled
select
  "id"
from
  "shared_space"
where
  "faceRecognitionEnabled" = $1

-- SharedSpaceRepository.getAssetCount
select
  count(*) as "count"
from
  (
    select
      "asset"."id"
    from
      "shared_space_asset"
      inner join "asset" on "asset"."id" = "shared_space_asset"."assetId"
    where
      "shared_space_asset"."spaceId" = $1
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $2
      and "asset"."visibility" in ($3, $4)
    union
    select
      "asset"."id"
    from
      "shared_space_library"
      inner join "asset" on "asset"."libraryId" = "shared_space_library"."libraryId"
    where
      "shared_space_library"."spaceId" = $5
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $6
      and "asset"."visibility" in ($7, $8)
    union
    select
      "asset"."id"
    from
      "shared_space_album"
      inner join "album" on "album"."id" = "shared_space_album"."albumId"
      and "album"."deletedAt" is null
      inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
      inner join "asset" on "asset"."id" = "album_asset"."assetId"
    where
      "shared_space_album"."spaceId" = $9
      and "shared_space_album"."showInTimeline" = $10
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $11
      and "asset"."visibility" in ($12, $13)
    union
    select
      "asset"."id"
    from
      "asset"
    where
      exists (
        select
          1 as "exists"
        from
          "shared_space_album"
          inner join "album_space_asset" on "album_space_asset"."albumId" = "shared_space_album"."albumId"
          and "album_space_asset"."spaceId" = "shared_space_album"."spaceId"
          inner join "album" on "album"."id" = "shared_space_album"."albumId"
          and "album"."deletedAt" is null
        where
          "album_space_asset"."assetId" = "asset"."id"
          and "shared_space_album"."spaceId" = $14::uuid
          and "shared_space_album"."showInTimeline" = $15
      )
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $16
      and "asset"."visibility" in ($17, $18)
  ) as "combined"

-- SharedSpaceRepository.getEditableByAssetIds
select distinct
  "shared_space_asset"."spaceId"
from
  "shared_space_asset"
  inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_asset"."spaceId"
where
  "shared_space_asset"."assetId" in ($1)
  and "shared_space_member"."userId" = $2
  and "shared_space_member"."role" in ($3, $4)

-- SharedSpaceRepository.removeAssets
delete from "shared_space_asset"
where
  "spaceId" = $1
  and "assetId" in ($2)
returning
  "assetId"

-- SharedSpaceRepository.getDirectAssetIds
select
  "assetId"
from
  "shared_space_asset"
where
  "spaceId" = $1
  and "assetId" in ($2)

-- SharedSpaceRepository.emitDirectAssetVisibilityPurge
insert into
  "shared_space_asset_audit" ("spaceId", "assetId")
select
  "shared_space_asset"."spaceId",
  "shared_space_asset"."assetId"
from
  "shared_space_asset"
where
  "shared_space_asset"."assetId" in ($1)

-- SharedSpaceRepository.emitDirectAssetVisibilityRestore
update "shared_space_asset"
set
  "updatedAt" = clock_timestamp()
where
  "assetId" in ($1)

-- SharedSpaceRepository.emitAlbumAssetVisibilityPurge
insert into
  "shared_space_album_asset_audit" ("albumId", "assetId")
select
  "album_asset"."albumId",
  "album_asset"."assetId"
from
  "album_asset"
where
  "album_asset"."assetId" in ($1)
  and "album_asset"."albumId" in (
    select
      "shared_space_album"."albumId"
    from
      "shared_space_album"
  )
insert into
  "album_space_asset_audit" ("albumId", "assetId")
select
  "album_space_asset"."albumId",
  "album_space_asset"."assetId"
from
  "album_space_asset"
where
  "album_space_asset"."assetId" in ($1)

-- SharedSpaceRepository.emitAlbumAssetVisibilityRestore
update "album_asset"
set
  "updatedAt" = clock_timestamp()
where
  "assetId" in ($1)
  and "albumId" in (
    select
      "shared_space_album"."albumId"
    from
      "shared_space_album"
  )
update "album_space_asset"
set
  "updatedAt" = clock_timestamp()
where
  "assetId" in ($1)

-- SharedSpaceRepository.emitLibraryAssetVisibilityPurge
insert into
  "shared_space_library_asset_audit" ("libraryId", "assetId")
select
  "asset"."libraryId" as "libraryId",
  "asset"."id" as "assetId"
from
  "asset"
where
  "asset"."id" in ($1)
  and "asset"."libraryId" is not null
  and "asset"."libraryId" in (
    select
      "shared_space_library"."libraryId"
    from
      "shared_space_library"
  )

-- SharedSpaceRepository.emitLibraryAssetVisibilityRestore
update "asset_exif"
set
  "updatedAt" = clock_timestamp()
where
  "assetId" in ($1)
  and "assetId" in (
    select
      "asset"."id"
    from
      "asset"
    where
      "asset"."libraryId" is not null
      and "asset"."libraryId" in (
        select
          "shared_space_library"."libraryId"
        from
          "shared_space_library"
      )
  )

-- SharedSpaceRepository.removeLibrary
delete from "shared_space_library"
where
  "spaceId" = $1
  and "libraryId" = $2

-- SharedSpaceRepository.getLinkedLibraries
select
  *
from
  "shared_space_library"
where
  "spaceId" = $1

-- SharedSpaceRepository.getSpacesLinkedToLibrary
select
  "shared_space_library".*,
  "shared_space"."faceRecognitionEnabled"
from
  "shared_space_library"
  inner join "shared_space" on "shared_space"."id" = "shared_space_library"."spaceId"
where
  "shared_space_library"."libraryId" = $1

-- SharedSpaceRepository.hasLibraryLink
select
  "spaceId"
from
  "shared_space_library"
where
  "spaceId" = $1
  and "libraryId" = $2

-- SharedSpaceRepository.removeAlbum
begin
insert into
  "album_space_asset_audit" ("albumId", "assetId")
select
  "album_space_asset"."albumId",
  "album_space_asset"."assetId"
from
  "album_space_asset"
where
  "album_space_asset"."spaceId" = $1
  and "album_space_asset"."albumId" in ($2)
delete from "shared_space_album"
where
  "spaceId" = $1
  and "albumId" = $2
commit

-- SharedSpaceRepository.removeOwnedAlbumLinksAddedBy
delete from "shared_space_album"
where
  "shared_space_album"."spaceId" = $1
  and "shared_space_album"."addedById" = $2
  and "shared_space_album"."albumId" in (
    select
      "album_user"."albumId"
    from
      "album_user"
    where
      "album_user"."userId" = $3
      and "album_user"."role" = $4
  )
returning
  "shared_space_album"."albumId"

-- SharedSpaceRepository.getLinkedAlbumCount
select
  count(*) as "count"
from
  "shared_space_album"
  inner join "album" on "album"."id" = "shared_space_album"."albumId"
where
  "shared_space_album"."spaceId" = $1
  and "album"."deletedAt" is null

-- SharedSpaceRepository.getLinkedAlbums
select
  "album".*,
  "shared_space_album"."addedById",
  "shared_space_album"."showInTimeline",
  "shared_space_album"."createdAt" as "linkedAt",
  (
    select
      "album_user"."userId"
    from
      "album_user"
    where
      "album_user"."albumId" = "album"."id"
      and "album_user"."role" = $1
    limit
      $2
  ) as "ownerId",
  coalesce(
    (
      select
        "asset"."id"
      from
        "asset"
      where
        "asset"."id" = "album"."albumThumbnailAssetId"
        and "asset"."deletedAt" is null
        and "asset"."visibility" in ($3, $4)
    ),
    (
      select
        "asset"."id"
      from
        "album_asset"
        inner join "asset" on "asset"."id" = "album_asset"."assetId"
      where
        "album_asset"."albumId" = "album"."id"
        and "asset"."deletedAt" is null
        and "asset"."visibility" in ($5, $6)
      order by
        "asset"."fileCreatedAt" desc,
        "asset"."id" asc
      limit
        $7
    )
  ) as "albumThumbnailAssetId"
from
  "shared_space_album"
  inner join "album" on "album"."id" = "shared_space_album"."albumId"
where
  "shared_space_album"."spaceId" = $8
  and "album"."deletedAt" is null
order by
  "album"."createdAt" desc,
  "album"."id" asc

-- SharedSpaceRepository.getLinkedAlbumIds
select
  "albumId"
from
  "shared_space_album"
where
  "spaceId" = $1

-- SharedSpaceRepository.reconcileAlbumGrants
insert into
  "shared_space_album_user" ("userId", "albumId")
select
  "shared_space_member"."userId",
  "shared_space_album"."albumId"
from
  "shared_space_album"
  inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_album"."spaceId"
  inner join "album" on "album"."id" = "shared_space_album"."albumId"
where
  "shared_space_album"."albumId" in ($1)
  and "album"."deletedAt" is null
on conflict do nothing
insert into
  "shared_space_album_user_audit" ("albumId", "userId")
select
  "shared_space_album_user"."albumId",
  "shared_space_album_user"."userId"
from
  "shared_space_album_user"
where
  "shared_space_album_user"."albumId" in ($1)
  and NOT user_has_album_path (
    "shared_space_album_user"."albumId",
    "shared_space_album_user"."userId",
    '00000000-0000-0000-0000-000000000000'::uuid
  )
returning
  "albumId"

-- SharedSpaceRepository.getAllGrantedAlbumIds
select distinct
  "albumId"
from
  "shared_space_album_user"

-- SharedSpaceRepository.getSpacesLinkedToAlbum
select
  "shared_space_album".*,
  "shared_space"."faceRecognitionEnabled"
from
  "shared_space_album"
  inner join "shared_space" on "shared_space"."id" = "shared_space_album"."spaceId"
where
  "shared_space_album"."albumId" = $1

-- SharedSpaceRepository.hasAlbumLink
select
  "spaceId"
from
  "shared_space_album"
where
  "spaceId" = $1
  and "albumId" = $2

-- SharedSpaceRepository.setAlbumShowInTimeline
update "shared_space_album"
set
  "showInTimeline" = $1
where
  "spaceId" = $2
  and "albumId" = $3

-- SharedSpaceRepository.getAlbumAssetCount
select
  count(*) as "count"
from
  "album_asset"
  inner join "asset" on "asset"."id" = "album_asset"."assetId"
where
  "album_asset"."albumId" = $1
  and "asset"."deletedAt" is null

-- SharedSpaceRepository.getRecentAssets
select
  "combined"."id",
  "combined"."thumbhash"
from
  (
    select
      "asset"."id",
      "asset"."thumbhash",
      "asset"."fileCreatedAt"
    from
      "shared_space_asset"
      inner join "asset" on "asset"."id" = "shared_space_asset"."assetId"
    where
      "shared_space_asset"."spaceId" = $1
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $2
      and "asset"."type" = $3
      and "asset"."visibility" in ($4, $5)
      and "asset"."thumbhash" is not null
    union
    select
      "asset"."id",
      "asset"."thumbhash",
      "asset"."fileCreatedAt"
    from
      "shared_space_library"
      inner join "asset" on "asset"."libraryId" = "shared_space_library"."libraryId"
    where
      "shared_space_library"."spaceId" = $6
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $7
      and "asset"."type" = $8
      and "asset"."visibility" in ($9, $10)
      and "asset"."thumbhash" is not null
    union
    select
      "asset"."id",
      "asset"."thumbhash",
      "asset"."fileCreatedAt"
    from
      "shared_space_album"
      inner join "album" on "album"."id" = "shared_space_album"."albumId"
      and "album"."deletedAt" is null
      inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
      inner join "asset" on "asset"."id" = "album_asset"."assetId"
    where
      "shared_space_album"."spaceId" = $11
      and "shared_space_album"."showInTimeline" = $12
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $13
      and "asset"."type" = $14
      and "asset"."visibility" in ($15, $16)
      and "asset"."thumbhash" is not null
    union
    select
      "asset"."id",
      "asset"."thumbhash",
      "asset"."fileCreatedAt"
    from
      "asset"
    where
      exists (
        select
          1 as "exists"
        from
          "shared_space_album"
          inner join "album_space_asset" on "album_space_asset"."albumId" = "shared_space_album"."albumId"
          and "album_space_asset"."spaceId" = "shared_space_album"."spaceId"
          inner join "album" on "album"."id" = "shared_space_album"."albumId"
          and "album"."deletedAt" is null
        where
          "album_space_asset"."assetId" = "asset"."id"
          and "shared_space_album"."spaceId" = $17::uuid
          and "shared_space_album"."showInTimeline" = $18
      )
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $19
      and "asset"."type" = $20
      and "asset"."thumbhash" is not null
      and "asset"."visibility" in ($21, $22)
  ) as "combined"
order by
  "combined"."fileCreatedAt" desc
limit
  $23

-- SharedSpaceRepository.getLastAssetAddedAt
select
  max("combined"."ts") as "lastAddedAt"
from
  (
    select
      "shared_space_asset"."addedAt" as "ts"
    from
      "shared_space_asset"
      inner join "asset" on "asset"."id" = "shared_space_asset"."assetId"
    where
      "shared_space_asset"."spaceId" = $1
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $2
      and "asset"."visibility" in ($3, $4)
    union
    select
      "asset"."createdAt" as "ts"
    from
      "shared_space_library"
      inner join "asset" on "asset"."libraryId" = "shared_space_library"."libraryId"
    where
      "shared_space_library"."spaceId" = $5
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $6
      and "asset"."visibility" in ($7, $8)
    union
    select
      "asset"."createdAt" as "ts"
    from
      "shared_space_album"
      inner join "album" on "album"."id" = "shared_space_album"."albumId"
      and "album"."deletedAt" is null
      inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
      inner join "asset" on "asset"."id" = "album_asset"."assetId"
    where
      "shared_space_album"."spaceId" = $9
      and "shared_space_album"."showInTimeline" = $10
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $11
      and "asset"."visibility" in ($12, $13)
    union
    select
      "asset"."createdAt" as "ts"
    from
      "asset"
    where
      exists (
        select
          1 as "exists"
        from
          "shared_space_album"
          inner join "album_space_asset" on "album_space_asset"."albumId" = "shared_space_album"."albumId"
          and "album_space_asset"."spaceId" = "shared_space_album"."spaceId"
          inner join "album" on "album"."id" = "shared_space_album"."albumId"
          and "album"."deletedAt" is null
        where
          "album_space_asset"."assetId" = "asset"."id"
          and "shared_space_album"."spaceId" = $14::uuid
          and "shared_space_album"."showInTimeline" = $15
      )
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $16
      and "asset"."visibility" in ($17, $18)
  ) as "combined"

-- SharedSpaceRepository.getNewAssetCount
select
  count(*) as "count"
from
  (
    select
      "asset"."id"
    from
      "shared_space_asset"
      inner join "asset" on "asset"."id" = "shared_space_asset"."assetId"
    where
      "shared_space_asset"."spaceId" = $1
      and "shared_space_asset"."addedAt" > $2
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $3
      and "asset"."visibility" in ($4, $5)
    union
    select
      "asset"."id"
    from
      "shared_space_library"
      inner join "asset" on "asset"."libraryId" = "shared_space_library"."libraryId"
    where
      "shared_space_library"."spaceId" = $6
      and "asset"."createdAt" > $7
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $8
      and "asset"."visibility" in ($9, $10)
    union
    select
      "asset"."id"
    from
      "shared_space_album"
      inner join "album" on "album"."id" = "shared_space_album"."albumId"
      and "album"."deletedAt" is null
      inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
      inner join "asset" on "asset"."id" = "album_asset"."assetId"
    where
      "shared_space_album"."spaceId" = $11
      and "shared_space_album"."showInTimeline" = $12
      and "asset"."createdAt" > $13
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $14
      and "asset"."visibility" in ($15, $16)
  ) as "combined"

-- SharedSpaceRepository.getLastContributor
select
  "user"."id",
  "user"."name"
from
  (
    select
      "shared_space_asset"."addedById" as "userId",
      "shared_space_asset"."addedAt" as "ts"
    from
      "shared_space_asset"
      inner join "asset" on "asset"."id" = "shared_space_asset"."assetId"
    where
      "shared_space_asset"."spaceId" = $1
      and "shared_space_asset"."addedAt" > $2
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $3
      and "asset"."visibility" in ($4, $5)
    union
    select
      "asset"."ownerId" as "userId",
      "asset"."createdAt" as "ts"
    from
      "shared_space_library"
      inner join "asset" on "asset"."libraryId" = "shared_space_library"."libraryId"
    where
      "shared_space_library"."spaceId" = $6
      and "asset"."createdAt" > $7
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $8
      and "asset"."visibility" in ($9, $10)
    union
    select
      "asset"."ownerId" as "userId",
      "asset"."createdAt" as "ts"
    from
      "shared_space_album"
      inner join "album" on "album"."id" = "shared_space_album"."albumId"
      and "album"."deletedAt" is null
      inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
      inner join "asset" on "asset"."id" = "album_asset"."assetId"
    where
      "shared_space_album"."spaceId" = $11
      and "shared_space_album"."showInTimeline" = $12
      and "asset"."createdAt" > $13
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $14
      and "asset"."visibility" in ($15, $16)
  ) as "contrib"
  inner join "user" on "user"."id" = "contrib"."userId"
  and "user"."deletedAt" is null
order by
  "contrib"."ts" desc
limit
  $17

-- SharedSpaceRepository.updateMemberLastViewed
update "shared_space_member"
set
  "lastViewedAt" = $1
where
  "spaceId" = $2
  and "userId" = $3

-- SharedSpaceRepository.getContributionCounts
select
  "combined"."userId" as "addedById",
  count(*) as "count"
from
  (
    select
      "shared_space_asset"."addedById" as "userId",
      "asset"."id" as "assetId"
    from
      "shared_space_asset"
      inner join "asset" on "asset"."id" = "shared_space_asset"."assetId"
    where
      "shared_space_asset"."spaceId" = $1
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $2
      and "asset"."visibility" in ($3, $4)
    union
    select
      "shared_space_library"."addedById" as "userId",
      "asset"."id" as "assetId"
    from
      "shared_space_library"
      inner join "asset" on "asset"."libraryId" = "shared_space_library"."libraryId"
    where
      "shared_space_library"."spaceId" = $5
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $6
      and "asset"."visibility" in ($7, $8)
    union
    select
      "shared_space_album"."addedById" as "userId",
      "asset"."id" as "assetId"
    from
      "shared_space_album"
      inner join "album" on "album"."id" = "shared_space_album"."albumId"
      and "album"."deletedAt" is null
      inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
      inner join "asset" on "asset"."id" = "album_asset"."assetId"
    where
      "shared_space_album"."spaceId" = $9
      and "shared_space_album"."showInTimeline" = $10
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $11
      and "asset"."visibility" in ($12, $13)
    union
    select
      "album_space_asset"."addedById" as "userId",
      "asset"."id" as "assetId"
    from
      "album_space_asset"
      inner join "shared_space_album" on "shared_space_album"."albumId" = "album_space_asset"."albumId"
      and "shared_space_album"."spaceId" = "album_space_asset"."spaceId"
      inner join "album" on "album"."id" = "shared_space_album"."albumId"
      and "album"."deletedAt" is null
      inner join "asset" on "asset"."id" = "album_space_asset"."assetId"
    where
      "album_space_asset"."spaceId" = $14
      and "shared_space_album"."showInTimeline" = $15
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $16
      and "asset"."visibility" in ($17, $18)
  ) as "combined"
where
  "combined"."userId" is not null
group by
  "combined"."userId"

-- SharedSpaceRepository.getMemberActivity
select
  "shared_space_asset"."addedById",
  max("shared_space_asset"."addedAt") as "lastAddedAt",
  (
    select
      "ssa2"."assetId"
    from
      "shared_space_asset" as "ssa2"
      inner join "asset" as "asset2" on "asset2"."id" = "ssa2"."assetId"
    where
      "ssa2"."addedById" = "shared_space_asset"."addedById"
      and "ssa2"."spaceId" = $1
      and "asset2"."deletedAt" is null
      and "asset2"."isOffline" = $2
      and "asset2"."visibility" in ($3, $4)
    order by
      "ssa2"."addedAt" desc
    limit
      $5
  ) as "recentAssetId"
from
  "shared_space_asset"
  inner join "asset" on "asset"."id" = "shared_space_asset"."assetId"
where
  "shared_space_asset"."spaceId" = $6
  and "asset"."deletedAt" is null
  and "asset"."isOffline" = $7
  and "asset"."visibility" in ($8, $9)
group by
  "shared_space_asset"."addedById"

-- SharedSpaceRepository.getMapMarkers
select
  "asset"."id",
  "asset_exif"."latitude",
  "asset_exif"."longitude",
  "asset_exif"."city",
  "asset_exif"."state",
  "asset_exif"."country"
from
  (
    select
      "asset"."id"
    from
      "shared_space_asset"
      inner join "asset" on "asset"."id" = "shared_space_asset"."assetId"
    where
      "shared_space_asset"."spaceId" = $1
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $2
      and "asset"."visibility" in ($3, $4)
    union
    select
      "asset"."id"
    from
      "shared_space_library"
      inner join "asset" on "asset"."libraryId" = "shared_space_library"."libraryId"
    where
      "shared_space_library"."spaceId" = $5
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $6
      and "asset"."visibility" in ($7, $8)
  ) as "combined"
  inner join "asset" on "asset"."id" = "combined"."id"
  inner join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  "asset_exif"."latitude" is not null
  and "asset_exif"."longitude" is not null

-- SharedSpaceRepository.getFilteredMapMarkers
select
  "asset"."id",
  "asset_exif"."latitude" as "lat",
  "asset_exif"."longitude" as "lon",
  "asset_exif"."city",
  "asset_exif"."state",
  "asset_exif"."country"
from
  "asset"
  inner join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  "asset"."visibility" = $1
  and "asset"."ownerId" = any ($2::uuid[])
  and "asset"."deletedAt" is null
  and "asset_exif"."latitude" is not null
  and "asset_exif"."longitude" is not null

-- SharedSpaceRepository.getActivities
select
  "shared_space_activity"."id",
  "shared_space_activity"."type",
  "shared_space_activity"."data",
  "shared_space_activity"."createdAt",
  "shared_space_activity"."userId",
  "user"."name",
  "user"."email",
  "user"."profileImagePath",
  "user"."avatarColor"
from
  "shared_space_activity"
  left join "user" on "user"."id" = "shared_space_activity"."userId"
where
  "shared_space_activity"."spaceId" = $1
  and (
    "shared_space_activity"."type" not in ($2, $3)
    or exists (
      select
        "album"."id"
      from
        "album"
      where
        "album"."deletedAt" is null
        and album.id::text = shared_space_activity.data ->> 'albumId'
    )
  )
order by
  "shared_space_activity"."createdAt" desc
limit
  $4
offset
  $5

-- SharedSpaceRepository.hasPetsBySpaceId
select
  count(*) as "count"
from
  "shared_space_person"
where
  "spaceId" = $1
  and "type" = $2

-- SharedSpaceRepository.getPersonsBySpaceId
select
  "shared_space_person".*
from
  "shared_space_person"
where
  "shared_space_person"."spaceId" = $1
  and "shared_space_person"."isHidden" = $2
  and (
    "shared_space_person"."name" != $3
    or "shared_space_person"."assetCount" >= $4
  )
  and exists (
    select
    from
      "shared_space_person_face" as "spf2"
      inner join "asset_face" as "af2" on "af2"."id" = "spf2"."assetFaceId"
      inner join "asset" on "asset"."id" = "af2"."assetId"
    where
      "spf2"."personId" = "shared_space_person"."id"
      and "af2"."deletedAt" is null
      and "af2"."isVisible" = $5
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $6
      and "asset"."visibility" in ($7, $8)
      and (
        exists (
          select
            "shared_space_asset"."assetId"
          from
            "shared_space_asset"
          where
            "shared_space_asset"."assetId" = "asset"."id"
            and "shared_space_asset"."spaceId" = $9
        )
        or exists (
          select
            "shared_space_library"."libraryId"
          from
            "shared_space_library"
          where
            "shared_space_library"."libraryId" = "asset"."libraryId"
            and "shared_space_library"."spaceId" = $10
        )
        or exists (
          select
            "shared_space_album"."albumId"
          from
            "shared_space_album"
            inner join "album" on "album"."id" = "shared_space_album"."albumId"
            and "album"."deletedAt" is null
            inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
          where
            "album_asset"."assetId" = "asset"."id"
            and "shared_space_album"."spaceId" = $11
        )
      )
  )
order by
  "shared_space_person"."isHidden" asc,
  NULLIF(BTRIM(shared_space_person.name), '') asc nulls last,
  CASE
    WHEN NULLIF(BTRIM(shared_space_person.name), '') IS NULL THEN "shared_space_person"."assetCount"
  END desc nulls last,
  "shared_space_person"."id"
limit
  $12

-- SharedSpaceRepository.countPersonsBySpaceId
WITH
  "asset_scope" AS (
    SELECT
      "asset"."id" AS "assetId"
    FROM
      "shared_space_asset"
      INNER JOIN "asset" ON "asset"."id" = "shared_space_asset"."assetId"
    WHERE
      "shared_space_asset"."spaceId" = $1
      AND "asset"."deletedAt" IS NULL
      AND "asset"."isOffline" = false
      AND "asset"."visibility" IN ($2, $3)
    UNION
    SELECT
      "asset"."id" AS "assetId"
    FROM
      "shared_space_library"
      INNER JOIN "asset" ON "asset"."libraryId" = "shared_space_library"."libraryId"
    WHERE
      "shared_space_library"."spaceId" = $4
      AND "asset"."deletedAt" IS NULL
      AND "asset"."isOffline" = false
      AND "asset"."visibility" IN ($5, $6)
    UNION
    SELECT
      "asset"."id" AS "assetId"
    FROM
      "shared_space_album"
      INNER JOIN "album" ON "album"."id" = "shared_space_album"."albumId"
      AND "album"."deletedAt" IS NULL
      INNER JOIN "album_asset" ON "album_asset"."albumId" = "shared_space_album"."albumId"
      INNER JOIN "asset" ON "asset"."id" = "album_asset"."assetId"
    WHERE
      "shared_space_album"."spaceId" = $7
      AND "asset"."deletedAt" IS NULL
      AND "asset"."isOffline" = false
      AND "asset"."visibility" IN ($8, $9)
  ),
  "person_rows" AS (
    SELECT
      COALESCE(
        "shared_space_person"."identityId",
        "shared_space_person"."id"
      ) AS "personKey",
      "shared_space_person"."isHidden"
    FROM
      "shared_space_person"
    WHERE
      "shared_space_person"."spaceId" = $10
      AND "shared_space_person"."name" ILIKE $11 ESCAPE '\'
      AND (
        "shared_space_person"."name" != ''
        OR "shared_space_person"."assetCount" >= $12
      )
      AND EXISTS (
        SELECT
          1
        FROM
          "shared_space_person_face"
          INNER JOIN "asset_face" ON "asset_face"."id" = "shared_space_person_face"."assetFaceId"
          INNER JOIN "asset_scope" ON "asset_scope"."assetId" = "asset_face"."assetId"
        WHERE
          "shared_space_person_face"."personId" = "shared_space_person"."id"
          AND "asset_face"."deletedAt" IS NULL
          AND "asset_face"."isVisible" = true
      )
  ),
  "person_keys" AS (
    SELECT
      "personKey",
      BOOL_AND("isHidden") AS "allHidden"
    FROM
      "person_rows"
    GROUP BY
      "personKey"
  ),
  "person_counts" AS (
    SELECT
      COUNT(*)::int AS "total",
      COUNT(*) FILTER (
        WHERE
          "allHidden"
      )::int AS "hidden"
    FROM
      "person_keys"
  ),
  "face_counts" AS (
    SELECT
      COUNT(DISTINCT "asset_face"."id")::int AS "detectedFaceCount"
    FROM
      "asset_scope"
      INNER JOIN "asset_face" ON "asset_face"."assetId" = "asset_scope"."assetId"
    WHERE
      "asset_face"."deletedAt" IS NULL
      AND "asset_face"."isVisible" = true
      AND EXISTS (
        SELECT
          1
        FROM
          "shared_space_person_face"
          INNER JOIN "shared_space_person" ON "shared_space_person"."id" = "shared_space_person_face"."personId"
        WHERE
          "shared_space_person_face"."assetFaceId" = "asset_face"."id"
          AND "shared_space_person"."spaceId" = $13
          AND "shared_space_person"."name" ILIKE $14 ESCAPE '\'
      )
  )
SELECT
  "person_counts"."total",
  "person_counts"."hidden",
  "face_counts"."detectedFaceCount"
FROM
  "person_counts",
  "face_counts"

-- SharedSpaceRepository.getPeopleFaceStatisticsBySpaceId
WITH
  "asset_scope" AS (
    SELECT
      "asset"."id" AS "assetId"
    FROM
      "shared_space_asset"
      INNER JOIN "asset" ON "asset"."id" = "shared_space_asset"."assetId"
    WHERE
      "shared_space_asset"."spaceId" = $1
      AND "asset"."deletedAt" IS NULL
      AND "asset"."isOffline" = false
      AND "asset"."visibility" IN ($2, $3)
    UNION
    SELECT
      "asset"."id" AS "assetId"
    FROM
      "shared_space_library"
      INNER JOIN "asset" ON "asset"."libraryId" = "shared_space_library"."libraryId"
    WHERE
      "shared_space_library"."spaceId" = $4
      AND "asset"."deletedAt" IS NULL
      AND "asset"."isOffline" = false
      AND "asset"."visibility" IN ($5, $6)
    UNION
    SELECT
      "asset"."id" AS "assetId"
    FROM
      "shared_space_album"
      INNER JOIN "album" ON "album"."id" = "shared_space_album"."albumId"
      AND "album"."deletedAt" IS NULL
      INNER JOIN "album_asset" ON "album_asset"."albumId" = "shared_space_album"."albumId"
      INNER JOIN "asset" ON "asset"."id" = "album_asset"."assetId"
    WHERE
      "shared_space_album"."spaceId" = $7
      AND "asset"."deletedAt" IS NULL
      AND "asset"."isOffline" = false
      AND "asset"."visibility" IN ($8, $9)
  ),
  "detected_faces" AS (
    SELECT DISTINCT
      "asset_face"."id" AS "assetFaceId"
    FROM
      "asset_scope"
      INNER JOIN "asset_face" ON "asset_face"."assetId" = "asset_scope"."assetId"
    WHERE
      "asset_face"."deletedAt" IS NULL
      AND "asset_face"."isVisible" = true
  ),
  "face_assignments" AS (
    SELECT
      "detected_faces"."assetFaceId",
      COALESCE(
        BOOL_OR("shared_space_person"."type" = 'pet'),
        false
      ) AS "hasPetAssignment",
      COALESCE(
        BOOL_OR(
          "shared_space_person"."id" IS NOT NULL
          AND "shared_space_person"."name" ILIKE $10 ESCAPE '\'
          AND (
            "shared_space_person"."name" != ''
            OR "shared_space_person"."assetCount" >= $11
          )
        ),
        false
      ) AS "hasMatchingAssignment",
      COALESCE(
        BOOL_OR(
          "shared_space_person"."isHidden" = false
          AND "shared_space_person"."name" ILIKE $12 ESCAPE '\'
          AND (
            "shared_space_person"."name" != ''
            OR "shared_space_person"."assetCount" >= $13
          )
        ),
        false
      ) AS "hasMatchingVisibleAssignment",
      COALESCE(
        BOOL_OR(
          "shared_space_person"."isHidden" = true
          AND "shared_space_person"."name" ILIKE $14 ESCAPE '\'
          AND (
            "shared_space_person"."name" != ''
            OR "shared_space_person"."assetCount" >= $15
          )
        ),
        false
      ) AS "hasMatchingHiddenAssignment"
    FROM
      "detected_faces"
      LEFT JOIN "shared_space_person_face" ON "shared_space_person_face"."assetFaceId" = "detected_faces"."assetFaceId"
      LEFT JOIN "shared_space_person" ON "shared_space_person"."id" = "shared_space_person_face"."personId"
      AND "shared_space_person"."spaceId" = $16
    GROUP BY
      "detected_faces"."assetFaceId"
  ),
  "included_faces" AS (
    SELECT
      *
    FROM
      "face_assignments"
    WHERE
      "hasMatchingAssignment" = true
  ),
  "matching_person_rows" AS (
    SELECT DISTINCT
      COALESCE(
        "shared_space_person"."identityId",
        "shared_space_person"."id"
      ) AS "personKey",
      "shared_space_person"."isHidden",
      "shared_space_person"."name"
    FROM
      "detected_faces"
      INNER JOIN "shared_space_person_face" ON "shared_space_person_face"."assetFaceId" = "detected_faces"."assetFaceId"
      INNER JOIN "shared_space_person" ON "shared_space_person"."id" = "shared_space_person_face"."personId"
      AND "shared_space_person"."spaceId" = $17
    WHERE
      true
      AND "shared_space_person"."name" ILIKE $18 ESCAPE '\'
  ),
  "matching_person_keys" AS (
    SELECT
      "personKey",
      BOOL_OR(
        "isHidden" = false
        AND NULLIF(BTRIM("name"), '') IS NOT NULL
      ) AS "hasNamedVisiblePerson"
    FROM
      "matching_person_rows"
    GROUP BY
      "personKey"
  )
SELECT
  COUNT(*)::int AS "detectedFaceCount",
  COUNT(*) FILTER (
    WHERE
      "hasMatchingVisibleAssignment" = true
  )::int AS "assignedVisibleFaceCount",
  (
    SELECT
      COUNT(*)::int
    FROM
      "matching_person_keys"
    WHERE
      "hasNamedVisiblePerson" = true
  ) AS "namedVisiblePersonCount",
  COUNT(*) FILTER (
    WHERE
      "hasMatchingVisibleAssignment" = false
      AND "hasMatchingHiddenAssignment" = true
  )::int AS "assignedHiddenFaceCount",
  COUNT(*) FILTER (
    WHERE
      "hasMatchingVisibleAssignment" = false
      AND "hasMatchingHiddenAssignment" = false
  )::int AS "unassignedFaceCount"
FROM
  "included_faces"

-- SharedSpaceRepository.getSpacePersonStatistics
WITH
  "target_person" AS (
    SELECT
      "id"
    FROM
      "shared_space_person"
    WHERE
      "id" = $1
      AND "spaceId" = $2
  ),
  "asset_scope" AS (
    SELECT
      "asset"."id" AS "assetId"
    FROM
      "shared_space_asset"
      INNER JOIN "asset" ON "asset"."id" = "shared_space_asset"."assetId"
    WHERE
      "shared_space_asset"."spaceId" = $3
      AND "asset"."deletedAt" IS NULL
      AND "asset"."isOffline" = false
      AND "asset"."visibility" IN ($4, $5)
    UNION
    SELECT
      "asset"."id" AS "assetId"
    FROM
      "shared_space_library"
      INNER JOIN "asset" ON "asset"."libraryId" = "shared_space_library"."libraryId"
    WHERE
      "shared_space_library"."spaceId" = $6
      AND "asset"."deletedAt" IS NULL
      AND "asset"."isOffline" = false
      AND "asset"."visibility" IN ($7, $8)
    UNION
    SELECT
      "asset"."id" AS "assetId"
    FROM
      "shared_space_album"
      INNER JOIN "album" ON "album"."id" = "shared_space_album"."albumId"
      AND "album"."deletedAt" IS NULL
      INNER JOIN "album_asset" ON "album_asset"."albumId" = "shared_space_album"."albumId"
      INNER JOIN "asset" ON "asset"."id" = "album_asset"."assetId"
    WHERE
      "shared_space_album"."spaceId" = $9
      AND "asset"."deletedAt" IS NULL
      AND "asset"."isOffline" = false
      AND "asset"."visibility" IN ($10, $11)
  ),
  "selected_faces" AS (
    SELECT DISTINCT
      "asset_face"."id" AS "assetFaceId",
      "asset_face"."assetId"
    FROM
      "target_person"
      INNER JOIN "asset_scope" ON true
      INNER JOIN "asset_face" ON "asset_face"."assetId" = "asset_scope"."assetId"
      INNER JOIN "shared_space_person_face" ON "shared_space_person_face"."assetFaceId" = "asset_face"."id"
      AND "shared_space_person_face"."personId" = "target_person"."id"
    WHERE
      "asset_face"."deletedAt" IS NULL
      AND "asset_face"."isVisible" = true
  )
SELECT
  COUNT(DISTINCT "assetId")::int AS "assets",
  COUNT(DISTINCT "assetFaceId")::int AS "faces"
FROM
  "selected_faces"

-- SharedSpaceRepository.getPersonById
select
  "shared_space_person".*
from
  "shared_space_person"
where
  "shared_space_person"."id" = $1

-- SharedSpaceRepository.getSpaceRepresentativeFaceForUpdate
select
  "asset_face".*
from
  "shared_space_person_face"
  inner join "shared_space_person" on "shared_space_person"."id" = "shared_space_person_face"."personId"
  inner join "asset_face" on "asset_face"."id" = "shared_space_person_face"."assetFaceId"
  inner join "asset" on "asset"."id" = "asset_face"."assetId"
where
  "shared_space_person"."spaceId" = $1
  and "shared_space_person"."id" = $2
  and "asset_face"."id" = $3
  and "asset_face"."deletedAt" is null
  and "asset_face"."isVisible" = $4
  and "asset"."deletedAt" is null
  and "asset"."isOffline" = $5
  and "asset"."visibility" in ($6, $7)
  and (
    exists (
      select
        "shared_space_asset"."assetId"
      from
        "shared_space_asset"
      where
        "shared_space_asset"."assetId" = "asset_face"."assetId"
        and "shared_space_asset"."spaceId" = "shared_space_person"."spaceId"
    )
    or exists (
      select
        "shared_space_library"."libraryId"
      from
        "shared_space_library"
      where
        "shared_space_library"."libraryId" = "asset"."libraryId"
        and "shared_space_library"."spaceId" = "shared_space_person"."spaceId"
    )
    or (
      exists (
        select
          1 as "exists"
        from
          "shared_space_album"
          inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
          inner join "album" on "album"."id" = "shared_space_album"."albumId"
          and "album"."deletedAt" is null
        where
          "album_asset"."assetId" = "asset_face"."assetId"
          and "shared_space_album"."spaceId" = "shared_space_person"."spaceId"
      )
      or exists (
        select
          1 as "exists"
        from
          "shared_space_album"
          inner join "album_space_asset" on "album_space_asset"."albumId" = "shared_space_album"."albumId"
          and "album_space_asset"."spaceId" = "shared_space_album"."spaceId"
          inner join "album" on "album"."id" = "shared_space_album"."albumId"
          and "album"."deletedAt" is null
        where
          "album_space_asset"."assetId" = "asset_face"."assetId"
          and "shared_space_album"."spaceId" = "shared_space_person"."spaceId"
      )
    )
  )

-- SharedSpaceRepository.getSpaceRepresentativeFaces
select
  "asset_face".*,
  "asset"."fileCreatedAt",
  "shared_space_person"."representativeFaceId"
from
  "shared_space_person_face"
  inner join "shared_space_person" on "shared_space_person"."id" = "shared_space_person_face"."personId"
  inner join "asset_face" on "asset_face"."id" = "shared_space_person_face"."assetFaceId"
  inner join "asset" on "asset"."id" = "asset_face"."assetId"
where
  "shared_space_person"."spaceId" = $1
  and "shared_space_person"."id" = $2
  and "asset_face"."deletedAt" is null
  and "asset_face"."isVisible" = $3
  and "asset"."deletedAt" is null
  and "asset"."isOffline" = $4
  and "asset"."visibility" in ($5, $6)
  and (
    exists (
      select
        "shared_space_asset"."assetId"
      from
        "shared_space_asset"
      where
        "shared_space_asset"."assetId" = "asset_face"."assetId"
        and "shared_space_asset"."spaceId" = "shared_space_person"."spaceId"
    )
    or exists (
      select
        "shared_space_library"."libraryId"
      from
        "shared_space_library"
      where
        "shared_space_library"."libraryId" = "asset"."libraryId"
        and "shared_space_library"."spaceId" = "shared_space_person"."spaceId"
    )
    or (
      exists (
        select
          1 as "exists"
        from
          "shared_space_album"
          inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
          inner join "album" on "album"."id" = "shared_space_album"."albumId"
          and "album"."deletedAt" is null
        where
          "album_asset"."assetId" = "asset_face"."assetId"
          and "shared_space_album"."spaceId" = "shared_space_person"."spaceId"
      )
      or exists (
        select
          1 as "exists"
        from
          "shared_space_album"
          inner join "album_space_asset" on "album_space_asset"."albumId" = "shared_space_album"."albumId"
          and "album_space_asset"."spaceId" = "shared_space_album"."spaceId"
          inner join "album" on "album"."id" = "shared_space_album"."albumId"
          and "album"."deletedAt" is null
        where
          "album_space_asset"."assetId" = "asset_face"."assetId"
          and "shared_space_album"."spaceId" = "shared_space_person"."spaceId"
      )
    )
  )
order by
  "asset"."fileCreatedAt" desc,
  "asset_face"."id"
limit
  $7
offset
  $8

-- SharedSpaceRepository.getSpacePersonByIdentity
select
  *
from
  "shared_space_person"
where
  "spaceId" = $1
  and "identityId" = $2

-- SharedSpaceRepository.getMetadataInheritanceCandidates
select
  "person"."personGroupId" as "personId",
  'user-person' as "sourceProfileType",
  "person"."personGroupId" as "sourceProfileId",
  "person"."ownerId" as "userId",
  "shared_space_member"."role",
  "person"."name",
  "person"."birthDate",
  "person"."type",
  "person"."species",
  "person"."updatedAt",
  count("shared_space_person"."id") as "supportingFaceCount",
  person."ownerId" = any ($1::uuid[]) as "isAssetAdder"
from
  "person"
  inner join "shared_space_member" on "shared_space_member"."userId" = "person"."ownerId"
  and "shared_space_member"."spaceId" = $2
  and "shared_space_member"."sharePersonMetadata" = $3
  left join "asset_face" on "asset_face"."personGroupId" = "person"."personGroupId"
  and "asset_face"."deletedAt" is null
  and "asset_face"."isVisible" is true
  left join "shared_space_person_face" on "shared_space_person_face"."assetFaceId" = "asset_face"."id"
  left join "shared_space_person" on "shared_space_person"."id" = "shared_space_person_face"."personId"
  and "shared_space_person"."spaceId" = $4
where
  "person"."identityId" = $5
group by
  "person"."personGroupId",
  "person"."ownerId",
  "shared_space_member"."role",
  "person"."name",
  "person"."birthDate",
  "person"."type",
  "person"."species",
  "person"."updatedAt",
  "isAssetAdder"
select
  "source_person"."id" as "personId",
  'space-person' as "sourceProfileType",
  "source_person"."id" as "sourceProfileId",
  "target_member"."userId" as "userId",
  "target_member"."role",
  "source_person"."birthDate",
  "source_person"."type",
  "source_person"."updatedAt",
  COALESCE(
    NULLIF("source_alias"."alias", ''),
    "source_person"."name",
    ''
  ) as "name",
  NULL as "species",
  "source_person"."faceCount" as "supportingFaceCount",
  true as "isAssetAdder"
from
  "shared_space_person" as "source_person"
  inner join "shared_space_member" as "source_member" on "source_member"."spaceId" = "source_person"."spaceId"
  and "source_member"."userId" = any ($1::uuid[])
  and "source_member"."showInTimeline" = $2
  inner join "shared_space_member" as "target_member" on "target_member"."spaceId" = $3
  and "target_member"."userId" = any ($4::uuid[])
  and "target_member"."sharePersonMetadata" = $5
  left join "shared_space_person_alias" as "source_alias" on "source_alias"."personId" = "source_person"."id"
  and "source_alias"."userId" = "source_member"."userId"
where
  "source_person"."identityId" = $6
  and "source_person"."spaceId" != $7
  and "source_person"."isHidden" = $8

-- SharedSpaceRepository.getSpacePersonAssetAdderIds
select distinct
  "shared_space_asset"."addedById" as "userId"
from
  "shared_space_person_face"
  inner join "asset_face" on "asset_face"."id" = "shared_space_person_face"."assetFaceId"
  inner join "shared_space_asset" on "shared_space_asset"."assetId" = "asset_face"."assetId"
  and "shared_space_asset"."spaceId" = $1
where
  "shared_space_person_face"."personId" = $2
  and "shared_space_asset"."addedById" is not null
select distinct
  "shared_space_library"."addedById" as "userId"
from
  "shared_space_person_face"
  inner join "asset_face" on "asset_face"."id" = "shared_space_person_face"."assetFaceId"
  inner join "asset" on "asset"."id" = "asset_face"."assetId"
  inner join "shared_space_library" on "shared_space_library"."libraryId" = "asset"."libraryId"
  and "shared_space_library"."spaceId" = $1
where
  "shared_space_person_face"."personId" = $2
  and "asset"."deletedAt" is null
  and "asset"."isOffline" = $3
  and "shared_space_library"."addedById" is not null
select distinct
  "shared_space_album"."addedById" as "userId"
from
  "shared_space_person_face"
  inner join "asset_face" on "asset_face"."id" = "shared_space_person_face"."assetFaceId"
  inner join "asset" on "asset"."id" = "asset_face"."assetId"
  inner join "album_asset" on "album_asset"."assetId" = "asset"."id"
  inner join "shared_space_album" on "shared_space_album"."albumId" = "album_asset"."albumId"
  and "shared_space_album"."spaceId" = $1
  inner join "album" on "album"."id" = "shared_space_album"."albumId"
  and "album"."deletedAt" is null
where
  "shared_space_person_face"."personId" = $2
  and "asset"."deletedAt" is null
  and "asset"."isOffline" = $3
  and "shared_space_album"."addedById" is not null

-- SharedSpaceRepository.getSpaceAssetAdder
select
  "addedById"
from
  "shared_space_asset"
where
  "spaceId" = $1
  and "assetId" = $2
select
  "shared_space_library"."addedById"
from
  "shared_space_library"
  inner join "asset" on "asset"."libraryId" = "shared_space_library"."libraryId"
where
  "shared_space_library"."spaceId" = $1
  and "asset"."id" = $2
  and "asset"."deletedAt" is null
  and "asset"."isOffline" = $3
select
  "shared_space_album"."addedById"
from
  "shared_space_album"
  inner join "album" on "album"."id" = "shared_space_album"."albumId"
  and "album"."deletedAt" is null
  inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
  inner join "asset" on "asset"."id" = "album_asset"."assetId"
where
  "shared_space_album"."spaceId" = $1
  and "asset"."id" = $2
  and "asset"."deletedAt" is null
  and "asset"."isOffline" = $3

-- SharedSpaceRepository.getSpacePersonMetadataBackfillPage
select
  "shared_space_person".*
from
  "shared_space_person"
where
  "identityId" is not null
  and "identityId" = $1
  and "id" > $2
order by
  "id"
limit
  $3

-- SharedSpaceRepository.getIdentityEvidenceForSpacePerson
select
  "person"."identityId",
  "person"."type",
  count("asset_face"."id") as "supportingFaceCount"
from
  "shared_space_person_face"
  inner join "asset_face" on "asset_face"."id" = "shared_space_person_face"."assetFaceId"
  inner join "asset" on "asset"."id" = "asset_face"."assetId"
  inner join "person" on "person"."personGroupId" = "asset_face"."personGroupId"
where
  "shared_space_person_face"."personId" = $1
  and (
    exists (
      select
        "shared_space_asset"."assetId"
      from
        "shared_space_asset"
      where
        "shared_space_asset"."assetId" = "asset_face"."assetId"
        and "shared_space_asset"."spaceId" = $2
    )
    or exists (
      select
        "shared_space_library"."libraryId"
      from
        "shared_space_library"
      where
        "shared_space_library"."libraryId" = "asset"."libraryId"
        and "shared_space_library"."spaceId" = $3
    )
    or (
      exists (
        select
          1 as "exists"
        from
          "shared_space_album"
          inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
          inner join "album" on "album"."id" = "shared_space_album"."albumId"
          and "album"."deletedAt" is null
        where
          "album_asset"."assetId" = "asset_face"."assetId"
          and "shared_space_album"."spaceId" = $4::uuid
      )
      or exists (
        select
          1 as "exists"
        from
          "shared_space_album"
          inner join "album_space_asset" on "album_space_asset"."albumId" = "shared_space_album"."albumId"
          and "album_space_asset"."spaceId" = "shared_space_album"."spaceId"
          inner join "album" on "album"."id" = "shared_space_album"."albumId"
          and "album"."deletedAt" is null
        where
          "album_space_asset"."assetId" = "asset_face"."assetId"
          and "shared_space_album"."spaceId" = $5::uuid
      )
    )
  )
  and "person"."identityId" is not null
  and "asset_face"."deletedAt" is null
  and "asset_face"."isVisible" is true
  and "asset"."deletedAt" is null
  and "asset"."visibility" = 'timeline'
group by
  "person"."identityId",
  "person"."type"

-- SharedSpaceRepository.updatePerson
update "shared_space_person"
set
  "name" = $1
where
  "id" = $2
returning
  *

-- SharedSpaceRepository.deletePerson
delete from "shared_space_person"
where
  "id" = $1

-- SharedSpaceRepository.getPersonAssetIds
select distinct
  "asset_face"."assetId"
from
  "shared_space_person_face"
  inner join "shared_space_person" on "shared_space_person"."id" = "shared_space_person_face"."personId"
  inner join "asset_face" on "asset_face"."id" = "shared_space_person_face"."assetFaceId"
  inner join "asset" on "asset"."id" = "asset_face"."assetId"
where
  "shared_space_person_face"."personId" = $1
  and "asset"."deletedAt" is null
  and "asset"."isOffline" = $2
  and "asset"."visibility" in ($3, $4)
  and (
    exists (
      select
        "shared_space_asset"."assetId"
      from
        "shared_space_asset"
      where
        "shared_space_asset"."assetId" = "asset_face"."assetId"
        and "shared_space_asset"."spaceId" = "shared_space_person"."spaceId"
    )
    or exists (
      select
        "shared_space_library"."libraryId"
      from
        "shared_space_library"
      where
        "shared_space_library"."libraryId" = "asset"."libraryId"
        and "shared_space_library"."spaceId" = "shared_space_person"."spaceId"
    )
    or (
      exists (
        select
          1 as "exists"
        from
          "shared_space_album"
          inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
          inner join "album" on "album"."id" = "shared_space_album"."albumId"
          and "album"."deletedAt" is null
        where
          "album_asset"."assetId" = "asset_face"."assetId"
          and "shared_space_album"."spaceId" = "shared_space_person"."spaceId"
          and "shared_space_album"."showInTimeline" = $5
      )
      or exists (
        select
          1 as "exists"
        from
          "shared_space_album"
          inner join "album_space_asset" on "album_space_asset"."albumId" = "shared_space_album"."albumId"
          and "album_space_asset"."spaceId" = "shared_space_album"."spaceId"
          inner join "album" on "album"."id" = "shared_space_album"."albumId"
          and "album"."deletedAt" is null
        where
          "album_space_asset"."assetId" = "asset_face"."assetId"
          and "shared_space_album"."spaceId" = "shared_space_person"."spaceId"
          and "shared_space_album"."showInTimeline" = $6
      )
    )
  )

-- SharedSpaceRepository.getFaceIdsForPerson
select
  "assetFaceId"
from
  "shared_space_person_face"
where
  "personId" = $1

-- SharedSpaceRepository.reassignPersonFacesSafe
delete from "shared_space_person_face"
where
  "personId" = $1
  and "assetFaceId" in (
    select
      "assetFaceId"
    from
      "shared_space_person_face"
    where
      "personId" = $2
  )
update "shared_space_person_face"
set
  "personId" = $1
where
  "personId" = $2

-- SharedSpaceRepository.getFirstFaceIdForPerson
select
  "shared_space_person_face"."assetFaceId"
from
  "shared_space_person_face"
  inner join "face_search" on "face_search"."faceId" = "shared_space_person_face"."assetFaceId"
where
  "shared_space_person_face"."personId" = $1
limit
  $2

-- SharedSpaceRepository.isSpacePersonRepresentativeFaceValid
select
  "asset_face"."id"
from
  "shared_space_person_face"
  inner join "shared_space_person" on "shared_space_person"."id" = "shared_space_person_face"."personId"
  inner join "asset_face" on "asset_face"."id" = "shared_space_person_face"."assetFaceId"
  inner join "asset" on "asset"."id" = "asset_face"."assetId"
where
  "shared_space_person_face"."personId" = $1
  and "asset_face"."id" = $2
  and "asset_face"."deletedAt" is null
  and "asset_face"."isVisible" = $3
  and "asset"."deletedAt" is null
  and "asset"."isOffline" = $4
  and "asset"."visibility" in ($5, $6)
  and (
    exists (
      select
        "shared_space_asset"."assetId"
      from
        "shared_space_asset"
      where
        "shared_space_asset"."assetId" = "asset_face"."assetId"
        and "shared_space_asset"."spaceId" = "shared_space_person"."spaceId"
    )
    or exists (
      select
        "shared_space_library"."libraryId"
      from
        "shared_space_library"
      where
        "shared_space_library"."libraryId" = "asset"."libraryId"
        and "shared_space_library"."spaceId" = "shared_space_person"."spaceId"
    )
    or (
      exists (
        select
          1 as "exists"
        from
          "shared_space_album"
          inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
          inner join "album" on "album"."id" = "shared_space_album"."albumId"
          and "album"."deletedAt" is null
        where
          "album_asset"."assetId" = "asset_face"."assetId"
          and "shared_space_album"."spaceId" = "shared_space_person"."spaceId"
      )
      or exists (
        select
          1 as "exists"
        from
          "shared_space_album"
          inner join "album_space_asset" on "album_space_asset"."albumId" = "shared_space_album"."albumId"
          and "album_space_asset"."spaceId" = "shared_space_album"."spaceId"
          inner join "album" on "album"."id" = "shared_space_album"."albumId"
          and "album"."deletedAt" is null
        where
          "album_space_asset"."assetId" = "asset_face"."assetId"
          and "shared_space_album"."spaceId" = "shared_space_person"."spaceId"
      )
    )
  )

-- SharedSpaceRepository.getFirstValidRepresentativeFaceForPerson
select
  "asset_face"."id"
from
  "shared_space_person_face"
  inner join "shared_space_person" on "shared_space_person"."id" = "shared_space_person_face"."personId"
  inner join "asset_face" on "asset_face"."id" = "shared_space_person_face"."assetFaceId"
  inner join "asset" on "asset"."id" = "asset_face"."assetId"
where
  "shared_space_person_face"."personId" = $1
  and "asset_face"."deletedAt" is null
  and "asset_face"."isVisible" = $2
  and "asset"."deletedAt" is null
  and "asset"."isOffline" = $3
  and "asset"."visibility" in ($4, $5)
  and (
    exists (
      select
        "shared_space_asset"."assetId"
      from
        "shared_space_asset"
      where
        "shared_space_asset"."assetId" = "asset_face"."assetId"
        and "shared_space_asset"."spaceId" = "shared_space_person"."spaceId"
    )
    or exists (
      select
        "shared_space_library"."libraryId"
      from
        "shared_space_library"
      where
        "shared_space_library"."libraryId" = "asset"."libraryId"
        and "shared_space_library"."spaceId" = "shared_space_person"."spaceId"
    )
    or (
      exists (
        select
          1 as "exists"
        from
          "shared_space_album"
          inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
          inner join "album" on "album"."id" = "shared_space_album"."albumId"
          and "album"."deletedAt" is null
        where
          "album_asset"."assetId" = "asset_face"."assetId"
          and "shared_space_album"."spaceId" = "shared_space_person"."spaceId"
      )
      or exists (
        select
          1 as "exists"
        from
          "shared_space_album"
          inner join "album_space_asset" on "album_space_asset"."albumId" = "shared_space_album"."albumId"
          and "album_space_asset"."spaceId" = "shared_space_album"."spaceId"
          inner join "album" on "album"."id" = "shared_space_album"."albumId"
          and "album"."deletedAt" is null
        where
          "album_space_asset"."assetId" = "asset_face"."assetId"
          and "shared_space_album"."spaceId" = "shared_space_person"."spaceId"
      )
    )
  )
order by
  "asset"."fileCreatedAt" desc,
  "asset_face"."id"

-- SharedSpaceRepository.repairOrphanedRepresentativeFaces
update "shared_space_person"
set
  "representativeFaceId" = (
    select
      "shared_space_person_face"."assetFaceId"
    from
      "shared_space_person_face"
      inner join "face_search" on "face_search"."faceId" = "shared_space_person_face"."assetFaceId"
    where
      "shared_space_person_face"."personId" = "shared_space_person"."id"
    limit
      $1
  )
where
  "shared_space_person"."spaceId" = $2
  and "shared_space_person"."representativeFaceId" is null
  and "shared_space_person"."representativeFaceSource" = $3
  and exists (
    select
    from
      "shared_space_person_face"
    where
      "shared_space_person_face"."personId" = "shared_space_person"."id"
  )

-- SharedSpaceRepository.removePersonFacesByAssetIds
select distinct
  "personId"
from
  "shared_space_person_face"
where
  "assetFaceId" in (
    select
      "asset_face"."id"
    from
      "asset_face"
    where
      "asset_face"."assetId" in ($1)
  )
  and "personId" in (
    select
      "shared_space_person"."id"
    from
      "shared_space_person"
    where
      "shared_space_person"."spaceId" = $2
  )
delete from "shared_space_person_face"
where
  "assetFaceId" in (
    select
      "asset_face"."id"
    from
      "asset_face"
    where
      "asset_face"."assetId" in ($1)
  )
  and "personId" in (
    select
      "shared_space_person"."id"
    from
      "shared_space_person"
    where
      "shared_space_person"."spaceId" = $2
  )

-- SharedSpaceRepository.removePersonFacesByLibrary
select distinct
  "personId"
from
  "shared_space_person_face"
where
  "assetFaceId" in (
    select
      "asset_face"."id"
    from
      "asset_face"
      inner join "asset" on "asset"."id" = "asset_face"."assetId"
    where
      "asset"."libraryId" = $1
  )
  and "personId" in (
    select
      "shared_space_person"."id"
    from
      "shared_space_person"
    where
      "shared_space_person"."spaceId" = $2
  )
delete from "shared_space_person_face"
where
  "assetFaceId" in (
    select
      "asset_face"."id"
    from
      "asset_face"
      inner join "asset" on "asset"."id" = "asset_face"."assetId"
    where
      "asset"."libraryId" = $1
  )
  and "personId" in (
    select
      "shared_space_person"."id"
    from
      "shared_space_person"
    where
      "shared_space_person"."spaceId" = $2
  )

-- SharedSpaceRepository.getAlbumAssetIdsWithoutOtherSpacePath
select
  "album_asset"."assetId"
from
  "album_asset"
where
  "album_asset"."albumId" = $1
  and not exists (
    select
    from
      "shared_space_asset"
    where
      "shared_space_asset"."assetId" = "album_asset"."assetId"
      and "shared_space_asset"."spaceId" = $2
  )
  and not exists (
    select
    from
      "shared_space_album"
      inner join "album" on "album"."id" = "shared_space_album"."albumId"
      and "album"."deletedAt" is null
      inner join "album_asset" as "other" on "other"."albumId" = "shared_space_album"."albumId"
    where
      "other"."assetId" = "album_asset"."assetId"
      and "shared_space_album"."spaceId" = $3
      and "shared_space_album"."albumId" != $4
  )
  and not exists (
    select
    from
      "shared_space_album"
      inner join "album" on "album"."id" = "shared_space_album"."albumId"
      and "album"."deletedAt" is null
      inner join "album_space_asset" on "album_space_asset"."albumId" = "shared_space_album"."albumId"
      and "album_space_asset"."spaceId" = "shared_space_album"."spaceId"
    where
      "album_space_asset"."assetId" = "album_asset"."assetId"
      and "shared_space_album"."spaceId" = $5
      and "shared_space_album"."albumId" != $6
  )
  and not exists (
    select
    from
      "shared_space_library"
      inner join "asset" on "asset"."libraryId" = "shared_space_library"."libraryId"
    where
      "asset"."id" = "album_asset"."assetId"
      and "shared_space_library"."spaceId" = $7
  )
select
  "cand"."assetId"
from
  "album_space_asset" as "cand"
where
  "cand"."albumId" = $1
  and "cand"."spaceId" = $2
  and not exists (
    select
    from
      "shared_space_asset"
    where
      "shared_space_asset"."assetId" = "cand"."assetId"
      and "shared_space_asset"."spaceId" = $3
  )
  and not exists (
    select
    from
      "shared_space_album"
      inner join "album" on "album"."id" = "shared_space_album"."albumId"
      and "album"."deletedAt" is null
      inner join "album_asset" as "other" on "other"."albumId" = "shared_space_album"."albumId"
    where
      "other"."assetId" = "cand"."assetId"
      and "shared_space_album"."spaceId" = $4
      and "shared_space_album"."albumId" != $5
  )
  and not exists (
    select
    from
      "shared_space_album"
      inner join "album" on "album"."id" = "shared_space_album"."albumId"
      and "album"."deletedAt" is null
      inner join "album_space_asset" as "otherContribution" on "otherContribution"."albumId" = "shared_space_album"."albumId"
      and "otherContribution"."spaceId" = "shared_space_album"."spaceId"
    where
      "otherContribution"."assetId" = "cand"."assetId"
      and "shared_space_album"."spaceId" = $6
      and "shared_space_album"."albumId" != $7
  )
  and not exists (
    select
    from
      "shared_space_library"
      inner join "asset" on "asset"."libraryId" = "shared_space_library"."libraryId"
    where
      "asset"."id" = "cand"."assetId"
      and "shared_space_library"."spaceId" = $8
  )

-- SharedSpaceRepository.getAssetIdsWithoutOtherSpacePath
select
  "asset"."id"
from
  "asset"
where
  "asset"."id" in ($1)
  and not exists (
    select
    from
      "shared_space_asset"
    where
      "shared_space_asset"."assetId" = "asset"."id"
      and "shared_space_asset"."spaceId" = $2
  )
  and not (
    exists (
      select
        1 as "exists"
      from
        "shared_space_album"
        inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
        inner join "album" on "album"."id" = "shared_space_album"."albumId"
        and "album"."deletedAt" is null
      where
        "album_asset"."assetId" = "asset"."id"
        and "shared_space_album"."spaceId" = $3::uuid
    )
    or exists (
      select
        1 as "exists"
      from
        "shared_space_album"
        inner join "album_space_asset" on "album_space_asset"."albumId" = "shared_space_album"."albumId"
        and "album_space_asset"."spaceId" = "shared_space_album"."spaceId"
        inner join "album" on "album"."id" = "shared_space_album"."albumId"
        and "album"."deletedAt" is null
      where
        "album_space_asset"."assetId" = "asset"."id"
        and "shared_space_album"."spaceId" = $4::uuid
    )
  )
  and not exists (
    select
    from
      "shared_space_library"
      inner join "asset" as "libAsset" on "libAsset"."libraryId" = "shared_space_library"."libraryId"
    where
      "libAsset"."id" = "asset"."id"
      and "shared_space_library"."spaceId" = $5
  )

-- SharedSpaceRepository.getSpacePersonFaceAssetIds
select distinct
  "asset_face"."assetId"
from
  "shared_space_person_face"
  inner join "shared_space_person" on "shared_space_person"."id" = "shared_space_person_face"."personId"
  inner join "asset_face" on "asset_face"."id" = "shared_space_person_face"."assetFaceId"
where
  "shared_space_person"."spaceId" = $1

-- SharedSpaceRepository.deleteOrphanedPersons
begin
select
  "id"
from
  "shared_space_person"
where
  "spaceId" = $1
  and "id" not in (
    select
      "personId"
    from
      "shared_space_person_face"
  )
order by
  "id"
for update
commit

-- SharedSpaceRepository.deleteOrphanedPersonsByIds
begin
select
  "id"
from
  "shared_space_person"
where
  "spaceId" = $1
  and "id" in ($2)
  and "id" not in (
    select
      "personId"
    from
      "shared_space_person_face"
  )
order by
  "id"
for update
commit

-- SharedSpaceRepository.deleteAllOrphanedPersons
delete from "shared_space_person"
where
  "id" not in (
    select
      "personId"
    from
      "shared_space_person_face"
  )

-- SharedSpaceRepository.deleteAllPersonFaces
delete from "shared_space_person_face"

-- SharedSpaceRepository.deleteAllPersons
delete from "shared_space_person"

-- SharedSpaceRepository.deleteAllPets
delete from "shared_space_person"
where
  "type" = $1

-- SharedSpaceRepository.recountPersons
begin
select
  "id"
from
  "shared_space_person"
where
  "id" in ($1)
order by
  "id"
for update
update "shared_space_person"
set
  "faceCount" = (
    select
      count(*) as "count"
    from
      "shared_space_person_face"
      inner join "asset_face" on "asset_face"."id" = "shared_space_person_face"."assetFaceId"
      inner join "asset" on "asset"."id" = "asset_face"."assetId"
    where
      "asset_face"."deletedAt" is null
      and "asset_face"."isVisible" is true
      and "asset"."deletedAt" is null
      and "asset"."visibility" = 'timeline'
      and "shared_space_person_face"."personId" = "shared_space_person"."id"
  ),
  "assetCount" = (
    select
      count(distinct ("asset_face"."assetId")) as "count"
    from
      "shared_space_person_face"
      inner join "asset_face" on "asset_face"."id" = "shared_space_person_face"."assetFaceId"
      inner join "asset" on "asset"."id" = "asset_face"."assetId"
    where
      "asset_face"."deletedAt" is null
      and "asset_face"."isVisible" is true
      and "asset"."deletedAt" is null
      and "asset"."visibility" = 'timeline'
      and "shared_space_person_face"."personId" = "shared_space_person"."id"
  )
where
  "id" in ($1)
commit

-- SharedSpaceRepository.getAlias
select
  *
from
  "shared_space_person_alias"
where
  "personId" = $1
  and "userId" = $2

-- SharedSpaceRepository.deleteAlias
delete from "shared_space_person_alias"
where
  "personId" = $1
  and "userId" = $2

-- SharedSpaceRepository.getAliasesBySpaceAndUser
select
  "shared_space_person_alias".*
from
  "shared_space_person_alias"
  inner join "shared_space_person" on "shared_space_person"."id" = "shared_space_person_alias"."personId"
where
  "shared_space_person"."spaceId" = $1
  and "shared_space_person_alias"."userId" = $2

-- SharedSpaceRepository.migrateAliases
select
  *
from
  "shared_space_person_alias"
where
  "personId" = $1
delete from "shared_space_person_alias"
where
  "personId" = $1

-- SharedSpaceRepository.findClosestSpacePerson
begin
set
  local vchordrq.probes = 1
with
  "cte" as (
    select
      "shared_space_person"."id" as "personId",
      "shared_space_person"."name",
      "shared_space_person"."identityId",
      "shared_space_person"."type",
      face_search.embedding <=> $1 as "distance"
    from
      "shared_space_person"
      inner join "shared_space_person_face" on "shared_space_person_face"."personId" = "shared_space_person"."id"
      inner join "face_search" on "face_search"."faceId" = "shared_space_person_face"."assetFaceId"
    where
      "shared_space_person"."spaceId" = $2
    order by
      "distance"
    limit
      $3
  )
select
  *
from
  "cte"
where
  "cte"."distance" <= $4
commit

-- SharedSpaceRepository.getSpacePersonsWithEmbeddings
select
  "shared_space_person"."id",
  "shared_space_person"."name",
  "shared_space_person"."type",
  "shared_space_person"."identityId",
  "shared_space_person"."isHidden",
  "shared_space_person"."faceCount",
  "shared_space_person"."representativeFaceId",
  "shared_space_person"."representativeFaceSource",
  "face_search"."embedding"
from
  "shared_space_person"
  inner join "shared_space_person_face" on "shared_space_person_face"."personId" = "shared_space_person"."id"
  and "shared_space_person_face"."assetFaceId" = "shared_space_person"."representativeFaceId"
  inner join "asset_face" on "asset_face"."id" = "shared_space_person"."representativeFaceId"
  inner join "face_search" on "face_search"."faceId" = "shared_space_person"."representativeFaceId"
where
  "shared_space_person"."spaceId" = $1
  and "asset_face"."deletedAt" is null
  and "asset_face"."isVisible" = $2

-- SharedSpaceRepository.getSpacePersonAssignedFaceEmbeddings
select
  "face_search"."embedding"
from
  "shared_space_person_face"
  inner join "face_search" on "face_search"."faceId" = "shared_space_person_face"."assetFaceId"
  inner join "asset_face" on "asset_face"."id" = "shared_space_person_face"."assetFaceId"
where
  "shared_space_person_face"."personId" = $1
  and "asset_face"."deletedAt" is null
  and "asset_face"."isVisible" is true
order by
  "shared_space_person_face"."assetFaceId" asc
limit
  $2

-- SharedSpaceRepository.getAssignedFaceIdsForSpace
select
  "shared_space_person_face"."assetFaceId"
from
  "shared_space_person_face"
  inner join "shared_space_person" on "shared_space_person"."id" = "shared_space_person_face"."personId"
where
  "shared_space_person"."spaceId" = $1
  and "shared_space_person_face"."assetFaceId" = any ($2::uuid[])

-- SharedSpaceRepository.getAssetFacesForMatching
select
  "asset_face"."id",
  "asset_face"."assetId",
  "asset_face"."personGroupId" as "personId",
  "face_identity_face"."identityId",
  "person"."type",
  "face_search"."embedding"
from
  "asset_face"
  left join "face_search" on "face_search"."faceId" = "asset_face"."id"
  left join "person" on "person"."personGroupId" = "asset_face"."personGroupId"
  left join "face_identity_face" on "face_identity_face"."assetFaceId" = "asset_face"."id"
where
  "asset_face"."assetId" = $1
  and "asset_face"."deletedAt" is null
  and "asset_face"."isVisible" is true

-- SharedSpaceRepository.isAssetInSpace
select
  "combined"."id"
from
  (
    select
      "shared_space_asset"."assetId" as "id"
    from
      "shared_space_asset"
      inner join "asset" on "asset"."id" = "shared_space_asset"."assetId"
    where
      "shared_space_asset"."spaceId" = $1
      and "shared_space_asset"."assetId" = $2
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $3
      and "asset"."visibility" in ($4, $5)
    union
    select
      "asset"."id"
    from
      "shared_space_library"
      inner join "asset" on "asset"."libraryId" = "shared_space_library"."libraryId"
    where
      "shared_space_library"."spaceId" = $6
      and "asset"."id" = $7
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $8
      and "asset"."visibility" in ($9, $10)
    union
    select
      "asset"."id"
    from
      "shared_space_album"
      inner join "album" on "album"."id" = "shared_space_album"."albumId"
      and "album"."deletedAt" is null
      inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
      inner join "asset" on "asset"."id" = "album_asset"."assetId"
    where
      "shared_space_album"."spaceId" = $11
      and "asset"."id" = $12
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $13
      and "asset"."visibility" in ($14, $15)
    union
    select
      "asset"."id"
    from
      "asset"
    where
      "asset"."id" = $16
      and exists (
        select
          1 as "exists"
        from
          "shared_space_album"
          inner join "album_space_asset" on "album_space_asset"."albumId" = "shared_space_album"."albumId"
          and "album_space_asset"."spaceId" = "shared_space_album"."spaceId"
          inner join "album" on "album"."id" = "shared_space_album"."albumId"
          and "album"."deletedAt" is null
        where
          "album_space_asset"."assetId" = "asset"."id"
          and "shared_space_album"."spaceId" = $17::uuid
      )
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $18
      and "asset"."visibility" in ($19, $20)
  ) as "combined"
limit
  $21

-- SharedSpaceRepository.isFaceInSpace
select
  "combined"."id"
from
  (
    select
      "asset_face"."id"
    from
      "shared_space_asset"
      inner join "asset" on "asset"."id" = "shared_space_asset"."assetId"
      inner join "asset_face" on "asset_face"."assetId" = "shared_space_asset"."assetId"
    where
      "shared_space_asset"."spaceId" = $1
      and "asset_face"."id" = $2
      and "asset_face"."deletedAt" is null
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $3
      and "asset"."visibility" in ($4, $5)
    union
    select
      "asset_face"."id"
    from
      "shared_space_library"
      inner join "asset" on "asset"."libraryId" = "shared_space_library"."libraryId"
      inner join "asset_face" on "asset_face"."assetId" = "asset"."id"
    where
      "shared_space_library"."spaceId" = $6
      and "asset_face"."id" = $7
      and "asset_face"."deletedAt" is null
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $8
      and "asset"."visibility" in ($9, $10)
    union
    select
      "asset_face"."id"
    from
      "shared_space_album"
      inner join "album" on "album"."id" = "shared_space_album"."albumId"
      and "album"."deletedAt" is null
      inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
      inner join "asset" on "asset"."id" = "album_asset"."assetId"
      inner join "asset_face" on "asset_face"."assetId" = "asset"."id"
    where
      "shared_space_album"."spaceId" = $11
      and "asset_face"."id" = $12
      and "asset_face"."deletedAt" is null
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $13
      and "asset"."visibility" in ($14, $15)
      and "shared_space_album"."showInTimeline" = $16
  ) as "combined"
limit
  $17

-- SharedSpaceRepository.getAssetIdForFace
select
  "assetId"
from
  "asset_face"
where
  "id" = $1
  and "deletedAt" is null

-- SharedSpaceRepository.getAssetIdsInSpacePage
select
  "combined"."id" as "assetId"
from
  (
    select
      "shared_space_asset"."assetId" as "id"
    from
      "shared_space_asset"
      inner join "asset" on "asset"."id" = "shared_space_asset"."assetId"
    where
      "shared_space_asset"."spaceId" = $1
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $2
      and "asset"."visibility" in ($3, $4)
    union
    select
      "asset"."id"
    from
      "shared_space_library"
      inner join "asset" on "asset"."libraryId" = "shared_space_library"."libraryId"
    where
      "shared_space_library"."spaceId" = $5
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $6
      and "asset"."visibility" in ($7, $8)
    union
    select
      "asset"."id"
    from
      "asset"
    where
      (
        exists (
          select
            1 as "exists"
          from
            "shared_space_album"
            inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
            inner join "album" on "album"."id" = "shared_space_album"."albumId"
            and "album"."deletedAt" is null
          where
            "album_asset"."assetId" = "asset"."id"
            and "shared_space_album"."spaceId" = $9::uuid
        )
        or exists (
          select
            1 as "exists"
          from
            "shared_space_album"
            inner join "album_space_asset" on "album_space_asset"."albumId" = "shared_space_album"."albumId"
            and "album_space_asset"."spaceId" = "shared_space_album"."spaceId"
            inner join "album" on "album"."id" = "shared_space_album"."albumId"
            and "album"."deletedAt" is null
          where
            "album_space_asset"."assetId" = "asset"."id"
            and "shared_space_album"."spaceId" = $10::uuid
        )
      )
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $11
      and "asset"."visibility" in ($12, $13)
  ) as "combined"
where
  "combined"."id" > $14
order by
  "combined"."id" asc
limit
  $15

-- SharedSpaceRepository.getAssetIdsInSpace
select
  "combined"."id" as "assetId"
from
  (
    select
      "shared_space_asset"."assetId" as "id"
    from
      "shared_space_asset"
      inner join "asset" on "asset"."id" = "shared_space_asset"."assetId"
    where
      "shared_space_asset"."spaceId" = $1
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $2
      and "asset"."visibility" in ($3, $4)
    union
    select
      "asset"."id"
    from
      "shared_space_library"
      inner join "asset" on "asset"."libraryId" = "shared_space_library"."libraryId"
    where
      "shared_space_library"."spaceId" = $5
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $6
      and "asset"."visibility" in ($7, $8)
  ) as "combined"

-- SharedSpaceRepository.getSpaceIdsForAsset
select
  "combined"."spaceId"
from
  (
    select
      "shared_space_asset"."spaceId"
    from
      "shared_space_asset"
      inner join "shared_space" on "shared_space"."id" = "shared_space_asset"."spaceId"
    where
      "shared_space_asset"."assetId" = $1
      and "shared_space"."faceRecognitionEnabled" = $2
    union
    select
      "shared_space_library"."spaceId"
    from
      "shared_space_library"
      inner join "asset" on "asset"."libraryId" = "shared_space_library"."libraryId"
      inner join "shared_space" on "shared_space"."id" = "shared_space_library"."spaceId"
    where
      "asset"."id" = $3
      and "shared_space"."faceRecognitionEnabled" = $4
    union
    select
      "shared_space_album"."spaceId"
    from
      "shared_space_album"
      inner join "album" on "album"."id" = "shared_space_album"."albumId"
      and "album"."deletedAt" is null
      inner join "album_asset" on "album_asset"."albumId" = "shared_space_album"."albumId"
      inner join "shared_space" on "shared_space"."id" = "shared_space_album"."spaceId"
    where
      "album_asset"."assetId" = $5
      and "shared_space"."faceRecognitionEnabled" = $6
  ) as "combined"

-- SharedSpaceRepository.getSpacePersonsForAsset
select distinct
  "shared_space_person"."spaceId",
  "shared_space_person_face"."personId"
from
  "shared_space_person_face"
  inner join "asset_face" on "asset_face"."id" = "shared_space_person_face"."assetFaceId"
  inner join "shared_space_person" on "shared_space_person"."id" = "shared_space_person_face"."personId"
where
  "asset_face"."assetId" = $1

-- SharedSpaceRepository.isPersonFaceAssigned
select
  "shared_space_person_face"."assetFaceId"
from
  "shared_space_person_face"
  inner join "shared_space_person" on "shared_space_person"."id" = "shared_space_person_face"."personId"
where
  "shared_space_person_face"."assetFaceId" = $1
  and "shared_space_person"."spaceId" = $2
limit
  $3

-- SharedSpaceRepository.getPersonFaceAssignmentsForSpace
select
  "shared_space_person_face"."personId",
  "shared_space_person"."identityId",
  "shared_space_person"."type"
from
  "shared_space_person_face"
  inner join "shared_space_person" on "shared_space_person"."id" = "shared_space_person_face"."personId"
where
  "shared_space_person_face"."assetFaceId" = $1
  and "shared_space_person"."spaceId" = $2
order by
  "shared_space_person_face"."personId"

-- SharedSpaceRepository.removePersonFaceAssignmentsForSpaceFace
select
  "shared_space_person_face"."personId"
from
  "shared_space_person_face"
  inner join "shared_space_person" on "shared_space_person"."id" = "shared_space_person_face"."personId"
where
  "shared_space_person_face"."assetFaceId" = $1
  and "shared_space_person"."spaceId" = $2
order by
  "shared_space_person_face"."personId"

-- SharedSpaceRepository.getPetFacesForAsset
select
  "asset_face"."id",
  "asset_face"."assetId",
  "asset_face"."personGroupId" as "personId",
  "person"."identityId",
  "person"."type"
from
  "asset_face"
  inner join "person" on "person"."personGroupId" = "asset_face"."personGroupId"
where
  "asset_face"."assetId" = $1
  and "asset_face"."deletedAt" is null
  and "person"."type" = $2

-- SharedSpaceRepository.findSpacePersonByLinkedPersonId
select
  "shared_space_person".*
from
  "shared_space_person"
  inner join "shared_space_person_face" on "shared_space_person_face"."personId" = "shared_space_person"."id"
  inner join "asset_face" on "asset_face"."id" = "shared_space_person_face"."assetFaceId"
where
  "shared_space_person"."spaceId" = $1
  and "asset_face"."personGroupId" = $2
limit
  $3

-- SharedSpaceRepository.findSpacePersonsByLinkedPersonIds
select
  "shared_space_person"."id",
  "shared_space_person"."name",
  "shared_space_person"."isHidden",
  "shared_space_person"."birthDate",
  "shared_space_person"."updatedAt",
  "shared_space_person"."type",
  "asset_face"."personGroupId" as "personId"
from
  "shared_space_person"
  inner join "shared_space_person_face" on "shared_space_person_face"."personId" = "shared_space_person"."id"
  inner join "asset_face" on "asset_face"."id" = "shared_space_person_face"."assetFaceId"
where
  "shared_space_person"."spaceId" = $1
  and "asset_face"."personGroupId" in ($2)
group by
  "shared_space_person"."id",
  "shared_space_person"."name",
  "shared_space_person"."isHidden",
  "shared_space_person"."birthDate",
  "shared_space_person"."updatedAt",
  "shared_space_person"."type",
  "asset_face"."personGroupId"

-- SharedSpaceRepository.findSpaceForAssetAndUser
select
  "combined"."spaceId"
from
  (
    select
      "shared_space_asset"."spaceId"
    from
      "shared_space_asset"
      inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_asset"."spaceId"
      inner join "asset" on "asset"."id" = "shared_space_asset"."assetId"
      and "asset"."deletedAt" is null
    where
      "shared_space_asset"."assetId" = $1
      and "shared_space_member"."userId" = $2
    union
    select
      "shared_space_library"."spaceId"
    from
      "shared_space_library"
      inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_library"."spaceId"
      inner join "asset" on "asset"."libraryId" = "shared_space_library"."libraryId"
      and "asset"."id" = $3
      and "asset"."deletedAt" is null
      and "asset"."isOffline" = $4
    where
      "shared_space_member"."userId" = $5
  ) as "combined"
limit
  $6
