-- NOTE: This file is auto generated by ./sql-generator

-- SpaceAlbumRepository.getOwnedNames
select
  "album"."id",
  "album"."albumName",
  "album"."albumThumbnailAssetId",
  coalesce("metadata"."assetCount", 0)::int as "assetCount",
  "metadata"."startDate" as "startDate",
  "metadata"."endDate" as "endDate"
from
  "album"
  left join (
    select
      "album_asset"."albumId" as "albumId",
      count("album_asset"."assetId")::int as "assetCount",
      min(
        ("asset"."localDateTime" AT TIME ZONE 'UTC'::text)::date
      ) as "startDate",
      max(
        ("asset"."localDateTime" AT TIME ZONE 'UTC'::text)::date
      ) as "endDate"
    from
      "album_asset"
      inner join "asset" on "asset"."id" = "album_asset"."assetId"
    where
      "asset"."deletedAt" is null
    group by
      "album_asset"."albumId"
  ) as "metadata" on "metadata"."albumId" = "album"."id"
where
  exists (
    select
    from
      "album_user"
    where
      "album_user"."albumId" = "album"."id"
      and "album_user"."userId" = $1
      and "album_user"."role" = $2
  )
  and "album"."deletedAt" is null

-- SpaceAlbumRepository.getOwnedAlbumIdsForAssets
select
  "album_asset"."assetId" as "assetId",
  array_agg("album_asset"."albumId") as "albumIds"
from
  "album_asset"
  inner join "album" on "album"."id" = "album_asset"."albumId"
where
  exists (
    select
    from
      "album_user"
    where
      "album_user"."albumId" = "album"."id"
      and "album_user"."role" = $1
      and "album_user"."userId" = $2
  )
  and "album"."deletedAt" is null
  and "album_asset"."assetId" in ($3)
group by
  "album_asset"."assetId"

-- SpaceAlbumRepository.getSharedNames
select
  "album"."id",
  "album"."albumName",
  "album"."albumThumbnailAssetId",
  coalesce("metadata"."assetCount", 0)::int as "assetCount",
  "metadata"."startDate" as "startDate",
  "metadata"."endDate" as "endDate"
from
  "album"
  left join (
    select
      "album_asset"."albumId" as "albumId",
      count("album_asset"."assetId")::int as "assetCount",
      min(
        ("asset"."localDateTime" AT TIME ZONE 'UTC'::text)::date
      ) as "startDate",
      max(
        ("asset"."localDateTime" AT TIME ZONE 'UTC'::text)::date
      ) as "endDate"
    from
      "album_asset"
      inner join "asset" on "asset"."id" = "album_asset"."assetId"
    where
      "asset"."deletedAt" is null
    group by
      "album_asset"."albumId"
  ) as "metadata" on "metadata"."albumId" = "album"."id"
where
  (
    exists (
      select
      from
        "album_user"
      where
        "album_user"."albumId" = "album"."id"
        and "album_user"."userId" = $1
    )
    or exists (
      select
      from
        "shared_link"
      where
        "shared_link"."albumId" = "album"."id"
        and "shared_link"."userId" = $2
    )
  )
  and "album"."deletedAt" is null

-- SpaceAlbumRepository.getContributedAssetIds
select
  "album_space_asset"."assetId"
from
  "album_space_asset"
where
  "album_space_asset"."albumId" = $1
  and "album_space_asset"."assetId" in ($2)

-- SpaceAlbumRepository.addContributedAssets
insert into
  "album_space_asset" ("albumId", "assetId", "spaceId", "addedById")
values
  ($1, $2, $3, $4)
on conflict do nothing
