-- NOTE: This file is auto generated by ./sql-generator

-- ViewRepository.getUniqueOriginalPaths
select distinct
  substring("asset"."originalPath", $1) as "directoryPath"
from
  "asset"
where
  (
    "asset"."ownerId" = $2::uuid
    or exists (
      select
      from
        "shared_space_asset"
        inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_asset"."spaceId"
      where
        "shared_space_asset"."assetId" = "asset"."id"
        and "shared_space_member"."userId" = $3::uuid
    )
    or exists (
      select
      from
        "shared_space_library"
        inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_library"."spaceId"
      where
        "shared_space_library"."libraryId" = "asset"."libraryId"
        and "shared_space_member"."userId" = $4::uuid
    )
  )
  and "visibility" = $5
  and "deletedAt" is null
  and "fileCreatedAt" is not null
  and "fileModifiedAt" is not null
  and "localDateTime" is not null
order by
  "directoryPath" asc

-- ViewRepository.getAssetsByOriginalPath
select
  "asset".*,
  to_json("asset_exif") as "exifInfo"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  (
    "asset"."ownerId" = $1::uuid
    or exists (
      select
      from
        "shared_space_asset"
        inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_asset"."spaceId"
      where
        "shared_space_asset"."assetId" = "asset"."id"
        and "shared_space_member"."userId" = $2::uuid
    )
    or exists (
      select
      from
        "shared_space_library"
        inner join "shared_space_member" on "shared_space_member"."spaceId" = "shared_space_library"."spaceId"
      where
        "shared_space_library"."libraryId" = "asset"."libraryId"
        and "shared_space_member"."userId" = $3::uuid
    )
  )
  and "visibility" = $4
  and "deletedAt" is null
  and "fileCreatedAt" is not null
  and "fileModifiedAt" is not null
  and "localDateTime" is not null
  and "originalPath" like $5
  and "originalPath" not like $6
order by
  regexp_replace("asset"."originalPath", $7, $8) asc
