import {
  detectAlbums,
  extractFileIndex,
  isAutoGeneratedAlbum,
  matchFastTrack,
  matchForgottenDuplicates,
  matchNormal,
  matchSidecarToMedia,
  parseGoogleTakeoutSidecar,
  stripSupplementalSuffix,
  type TakeoutMediaItem,
} from '$lib/utils/google-takeout-parser';

describe('parseGoogleTakeoutSidecar', () => {
  it('should parse a complete sidecar with all fields', () => {
    const json = JSON.stringify({
      title: 'IMG_1234.jpg',
      description: 'A beautiful sunset',
      photoTakenTime: { timestamp: '1609459200' },
      geoData: { latitude: 48.8566, longitude: 2.3522, altitude: 35 },
      favorited: true,
      archived: true,
    });

    const result = parseGoogleTakeoutSidecar(json);

    expect(result).not.toBeNull();
    expect(result!.title).toBe('IMG_1234.jpg');
    expect(result!.description).toBe('A beautiful sunset');
    expect(result!.dateTaken).toEqual(new Date(1_609_459_200_000));
    expect(result!.latitude).toBe(48.8566);
    expect(result!.longitude).toBe(2.3522);
    expect(result!.isFavorite).toBe(true);
    expect(result!.isArchived).toBe(true);
  });

  it('should return null for non-Takeout JSON', () => {
    const json = JSON.stringify({ name: 'not a takeout file', size: 1234 });
    expect(parseGoogleTakeoutSidecar(json)).toBeNull();
  });

  it('should return null for malformed JSON', () => {
    expect(parseGoogleTakeoutSidecar('{not valid json}')).toBeNull();
  });

  it('should return null for empty string', () => {
    expect(parseGoogleTakeoutSidecar('')).toBeNull();
  });

  it('should handle missing optional fields', () => {
    const json = JSON.stringify({
      title: 'IMG_5678.jpg',
      photoTakenTime: { timestamp: '1609459200' },
    });

    const result = parseGoogleTakeoutSidecar(json);

    expect(result).not.toBeNull();
    expect(result!.title).toBe('IMG_5678.jpg');
    expect(result!.description).toBeUndefined();
    expect(result!.dateTaken).toEqual(new Date(1_609_459_200_000));
    expect(result!.latitude).toBeUndefined();
    expect(result!.longitude).toBeUndefined();
    expect(result!.isFavorite).toBe(false);
    expect(result!.isArchived).toBe(false);
  });

  it('should filter GPS (0,0) as no-location', () => {
    const json = JSON.stringify({
      title: 'IMG_9999.jpg',
      photoTakenTime: { timestamp: '1609459200' },
      geoData: { latitude: 0, longitude: 0 },
    });

    const result = parseGoogleTakeoutSidecar(json);

    expect(result).not.toBeNull();
    expect(result!.latitude).toBeUndefined();
    expect(result!.longitude).toBeUndefined();
  });

  it('should fall back to creationTime when photoTakenTime is missing', () => {
    const json = JSON.stringify({
      title: 'IMG_0001.jpg',
      creationTime: { timestamp: '1609545600' },
    });

    const result = parseGoogleTakeoutSidecar(json);

    expect(result).not.toBeNull();
    expect(result!.dateTaken).toEqual(new Date(1_609_545_600_000));
  });

  it('should fall back to geoDataExif when geoData is missing', () => {
    const json = JSON.stringify({
      title: 'IMG_0002.jpg',
      photoTakenTime: { timestamp: '1609459200' },
      geoDataExif: { latitude: 40.7128, longitude: -74.006 },
    });

    const result = parseGoogleTakeoutSidecar(json);

    expect(result).not.toBeNull();
    expect(result!.latitude).toBe(40.7128);
    expect(result!.longitude).toBe(-74.006);
  });

  it('should filter invalid GPS ranges', () => {
    const json = JSON.stringify({
      title: 'IMG_0003.jpg',
      photoTakenTime: { timestamp: '1609459200' },
      geoData: { latitude: 100, longitude: 200 },
    });

    const result = parseGoogleTakeoutSidecar(json);

    expect(result).not.toBeNull();
    expect(result!.latitude).toBeUndefined();
    expect(result!.longitude).toBeUndefined();
  });

  it('should trim whitespace-only descriptions to undefined', () => {
    const json = JSON.stringify({
      title: 'IMG_0004.jpg',
      description: '   \n\t  ',
      photoTakenTime: { timestamp: '1609459200' },
    });

    const result = parseGoogleTakeoutSidecar(json);

    expect(result).not.toBeNull();
    expect(result!.description).toBeUndefined();
  });
});

describe('matchSidecarToMedia', () => {
  const validSidecar = JSON.stringify({
    title: 'IMG_1234.jpg',
    photoTakenTime: { timestamp: '1609459200' },
  });

  it('should match sidecar to media by exact filename', () => {
    const result = matchSidecarToMedia('Takeout/Google Photos/Trip/IMG_1234.jpg.json', validSidecar, [
      'Takeout/Google Photos/Trip/IMG_1234.jpg',
      'Takeout/Google Photos/Trip/IMG_5678.jpg',
    ]);
    expect(result).toBe('Takeout/Google Photos/Trip/IMG_1234.jpg');
  });

  it('should return undefined when no media matches', () => {
    const result = matchSidecarToMedia('Takeout/Google Photos/Trip/IMG_9999.jpg.json', validSidecar, [
      'Takeout/Google Photos/Trip/IMG_1234.jpg',
    ]);
    expect(result).toBeUndefined();
  });

  it('should match truncated filenames (47-char Google limit)', () => {
    // Google truncates long filenames to 47 characters before appending .json
    const longName = 'this_is_a_really_long_filename_that_exceeds_47_chars_total.jpg';
    const truncated = longName.slice(0, 47);
    const result = matchSidecarToMedia(`Takeout/Google Photos/Album/${truncated}.json`, validSidecar, [
      `Takeout/Google Photos/Album/${longName}`,
    ]);
    expect(result).toBe(`Takeout/Google Photos/Album/${longName}`);
  });

  it('should return undefined for non-Takeout JSON sidecar', () => {
    const nonTakeout = JSON.stringify({ name: 'not takeout' });
    const result = matchSidecarToMedia('Takeout/Google Photos/Trip/IMG_1234.jpg.json', nonTakeout, [
      'Takeout/Google Photos/Trip/IMG_1234.jpg',
    ]);
    expect(result).toBeUndefined();
  });

  // 2024+ Google Takeout format: sidecar file is <photo>.<ext>.supplemental-metadata.json.
  // Google truncates the .supplemental-metadata segment to stay under a total filename
  // budget (~51 chars), so any prefix of "supplemental-metadata" may appear.
  it('should match new supplemental-metadata.json suffix', () => {
    const result = matchSidecarToMedia(
      'Takeout/Google Photos/Trip/IMG_1234.jpg.supplemental-metadata.json',
      validSidecar,
      ['Takeout/Google Photos/Trip/IMG_1234.jpg'],
    );
    expect(result).toBe('Takeout/Google Photos/Trip/IMG_1234.jpg');
  });

  it('should match truncated supplemental-metadata suffix', () => {
    // Google truncates the suffix at various points to fit the filename budget.
    const truncations = ['supplemental-metadat', 'supplemental-me', 'supple', 's'];
    for (const suffix of truncations) {
      const result = matchSidecarToMedia(
        `Takeout/Google Photos/Trip/IMG_1234.jpg.${suffix}.json`,
        validSidecar,
        ['Takeout/Google Photos/Trip/IMG_1234.jpg'],
      );
      expect(result, `suffix=${suffix}`).toBe('Takeout/Google Photos/Trip/IMG_1234.jpg');
    }
  });

  it('should not misinterpret a non-supplemental middle segment as the new suffix', () => {
    // "jpeg" is not a prefix of "supplemental-metadata" — must not be stripped as if it were.
    const result = matchSidecarToMedia('Takeout/Google Photos/Trip/IMG.jpeg.json', validSidecar, [
      'Takeout/Google Photos/Trip/IMG.jpeg',
    ]);
    expect(result).toBe('Takeout/Google Photos/Trip/IMG.jpeg');
  });
});

describe('isAutoGeneratedAlbum', () => {
  it('should detect "Photos from YYYY" as auto-generated', () => {
    expect(isAutoGeneratedAlbum('Photos from 2023')).toBe(true);
    expect(isAutoGeneratedAlbum('Photos from 2019')).toBe(true);
  });

  it('should not flag real album names', () => {
    expect(isAutoGeneratedAlbum('Summer Vacation')).toBe(false);
    expect(isAutoGeneratedAlbum('Family Photos')).toBe(false);
    expect(isAutoGeneratedAlbum('Photos from Paris')).toBe(false);
  });
});

describe('detectAlbums', () => {
  it('should extract albums from folder structure', () => {
    const items: TakeoutMediaItem[] = [
      { path: 'Takeout/Google Photos/Summer Trip/IMG_001.jpg', file: new File([], 'IMG_001.jpg') },
      { path: 'Takeout/Google Photos/Summer Trip/IMG_002.jpg', file: new File([], 'IMG_002.jpg') },
      { path: 'Takeout/Google Photos/Birthday/IMG_003.jpg', file: new File([], 'IMG_003.jpg') },
    ];

    const albums = detectAlbums(items);

    expect(albums).toHaveLength(2);
    const summerTrip = albums.find((a) => a.name === 'Summer Trip');
    expect(summerTrip).toBeDefined();
    expect(summerTrip!.itemCount).toBe(2);
    expect(summerTrip!.isAutoGenerated).toBe(false);
    expect(summerTrip!.itemPaths).toEqual([
      'Takeout/Google Photos/Summer Trip/IMG_001.jpg',
      'Takeout/Google Photos/Summer Trip/IMG_002.jpg',
    ]);

    const birthday = albums.find((a) => a.name === 'Birthday');
    expect(birthday).toBeDefined();
    expect(birthday!.itemCount).toBe(1);
  });

  it('should mark auto-generated albums', () => {
    const items: TakeoutMediaItem[] = [
      { path: 'Takeout/Google Photos/Photos from 2023/IMG_001.jpg', file: new File([], 'IMG_001.jpg') },
    ];

    const albums = detectAlbums(items);

    expect(albums).toHaveLength(1);
    expect(albums[0].name).toBe('Photos from 2023');
    expect(albums[0].isAutoGenerated).toBe(true);
  });

  it('should return empty array for flat files', () => {
    const items: TakeoutMediaItem[] = [{ path: 'IMG_001.jpg', file: new File([], 'IMG_001.jpg') }];

    const albums = detectAlbums(items);

    expect(albums).toHaveLength(0);
  });
});

describe('extractFileIndex', () => {
  it('returns empty index when no (N) present', () => {
    expect(extractFileIndex('IMG_1234.jpg')).toEqual({ name: 'IMG_1234.jpg', index: '' });
  });

  it('extracts (N) before an extension', () => {
    expect(extractFileIndex('IMG_1234(1).jpg')).toEqual({ name: 'IMG_1234.jpg', index: '1' });
  });

  it('extracts (N) at end of name (no extension)', () => {
    expect(extractFileIndex('IMG_1234(1)')).toEqual({ name: 'IMG_1234', index: '1' });
  });

  it('extracts multi-digit (N)', () => {
    expect(extractFileIndex('file(42).json')).toEqual({ name: 'file.json', index: '42' });
  });

  it('returns empty index for a bare trailing ()', () => {
    expect(extractFileIndex('file().jpg')).toEqual({ name: 'file().jpg', index: '' });
  });

  it('returns empty index when (N) is in the middle, not at end of basename', () => {
    expect(extractFileIndex('file(1)-edited.jpg')).toEqual({ name: 'file(1)-edited.jpg', index: '' });
  });
});

describe('matchFastTrack', () => {
  it('matches when jsonName is fileName + .json', () => {
    expect(matchFastTrack('IMG_1234.jpg.json', 'IMG_1234.jpg')).toBe(true);
  });

  it('does not match when stems differ', () => {
    expect(matchFastTrack('IMG_1234.jpg.json', 'IMG_5678.jpg')).toBe(false);
  });

  it('does not match when jsonName lacks .json extension', () => {
    expect(matchFastTrack('IMG_1234.jpg', 'IMG_1234.jpg')).toBe(false);
  });

  it('does not match for supplemental-metadata style sidecar', () => {
    expect(matchFastTrack('IMG_1234.jpg.supplemental-metadata.json', 'IMG_1234.jpg')).toBe(false);
  });
});

describe('matchNormal', () => {
  it('matches basic supplemental-metadata sidecar', () => {
    expect(matchNormal('IMG_1234.jpg.supplemental-metadata.json', 'IMG_1234.jpg')).toBe(true);
  });

  it('matches when (N) is in the basename on both sides', () => {
    expect(matchNormal('IMG(1).jpg.supplemental-metadata.json', 'IMG(1).jpg')).toBe(true);
  });

  it('matches when (N) is after supplemental-metadata on the sidecar side only', () => {
    expect(matchNormal('IMG.jpg.supplemental-metadata(1).json', 'IMG(1).jpg')).toBe(true);
  });

  it('matches legacy position (N).json sidecar', () => {
    expect(matchNormal('IMG.jpg(1).json', 'IMG(1).jpg')).toBe(true);
  });

  it('does not match when indexes differ', () => {
    expect(matchNormal('IMG.jpg.supplemental-metadata(1).json', 'IMG(2).jpg')).toBe(false);
  });

  it('does not match when one side has index and other does not', () => {
    expect(matchNormal('IMG.jpg.json', 'IMG(1).jpg')).toBe(false);
  });

  it('tolerates Google basename truncation (sidecar stem is prefix of media basename)', () => {
    // When Google's ~51-char filename budget is exceeded, the sidecar stem
    // drops the trailing media extension and becomes a strict prefix of the
    // media basename. This is the shape the existing PR #405 truncation test
    // covers.
    const longMedia = 'A'.repeat(40) + 'suffix.jpg';
    const truncatedStem = 'A'.repeat(40) + 'suffi';
    expect(matchNormal(`${truncatedStem}.supplemental-metadata.json`, longMedia)).toBe(true);
  });

  it('handles surrogate-pair emoji in the truncation prefix', () => {
    // 🌟 = 2 UTF-16 units, 1 code point. Prefix-matching must survive that.
    const mediaBase = '🌟'.repeat(10) + '.jpg';
    const truncStem = '🌟'.repeat(10);
    expect(matchNormal(`${truncStem}.supplemental-metadata.json`, mediaBase)).toBe(true);
  });
});

describe('matchForgottenDuplicates', () => {
  it('matches UUID-style forgotten duplicate', () => {
    expect(matchForgottenDuplicates('original_abc123_.json', 'original_abc123_P(1).jpg')).toBe(true);
  });

  it('matches Gap #4 missing-ext shape', () => {
    // Peanut Butter Balls.supplemental-metadata.json -> Peanut Butter Balls.jpg
    expect(matchForgottenDuplicates('Peanut Butter Balls.supplemental-metadata.json', 'Peanut Butter Balls.jpg')).toBe(
      true,
    );
  });

  it('matches at boundary diff of 9 code points', () => {
    expect(matchForgottenDuplicates('abc.json', 'abc12345.jpg')).toBe(true);
  });

  it('rejects at boundary diff of 10 code points', () => {
    expect(matchForgottenDuplicates('abc.json', 'abc123456.jpg')).toBe(false);
  });

  it('rejects when diff is much larger than 10', () => {
    expect(matchForgottenDuplicates('short.json', 'short_with_too_many_extra_chars.jpg')).toBe(false);
  });

  it('rejects when fileName does not start with jsonStem', () => {
    expect(matchForgottenDuplicates('abc.json', 'xyz.jpg')).toBe(false);
  });

  it('counts code points, not UTF-16 units, in the diff', () => {
    // 🌟 = 1 code point, 2 UTF-16 units. 5 emoji + ".jpg" extension = 9 code points diff from empty stem. < 10, match.
    expect(matchForgottenDuplicates('.json', '🌟🌟🌟🌟🌟.jpg')).toBe(true);
  });
});

describe('stripSupplementalSuffix', () => {
  it('leaves paths without a supplemental segment untouched', () => {
    expect(stripSupplementalSuffix('IMG_1234.jpg')).toBe('IMG_1234.jpg');
  });

  it('strips full .supplemental-metadata suffix', () => {
    expect(stripSupplementalSuffix('IMG_1234.jpg.supplemental-metadata')).toBe('IMG_1234.jpg');
  });

  it('strips truncated prefix of supplemental-metadata', () => {
    expect(stripSupplementalSuffix('IMG_1234.jpg.supple')).toBe('IMG_1234.jpg');
    expect(stripSupplementalSuffix('IMG_1234.jpg.s')).toBe('IMG_1234.jpg');
  });

  it('does not strip a segment that is not a prefix of supplemental-metadata', () => {
    expect(stripSupplementalSuffix('IMG_1234.jpg.zzz')).toBe('IMG_1234.jpg.zzz');
  });

  it('does not strip anything before the last /', () => {
    expect(stripSupplementalSuffix('supple/IMG_1234.jpg')).toBe('supple/IMG_1234.jpg');
  });
});
