export interface TakeoutMetadata {
  title: string;
  description: string | undefined;
  dateTaken: Date | undefined;
  latitude: number | undefined;
  longitude: number | undefined;
  isFavorite: boolean;
  isArchived: boolean;
}

export interface TakeoutMediaItem {
  path: string;
  file: File;
  metadata?: TakeoutMetadata;
  albumName?: string;
}

export interface TakeoutAlbum {
  name: string;
  itemCount: number;
  isAutoGenerated: boolean;
  itemPaths: string[];
}

function parseTimestamp(obj: { timestamp?: string } | undefined): Date | undefined {
  if (!obj?.timestamp) {
    return undefined;
  }
  const seconds = Number(obj.timestamp);
  if (Number.isNaN(seconds) || seconds <= 0) {
    return undefined;
  }
  return new Date(seconds * 1000);
}

function parseGps(
  geoData: { latitude?: number; longitude?: number } | undefined,
  geoDataExif: { latitude?: number; longitude?: number } | undefined,
): { latitude: number | undefined; longitude: number | undefined } {
  const geo = geoData ?? geoDataExif;
  if (!geo || geo.latitude === undefined || geo.longitude === undefined) {
    return { latitude: undefined, longitude: undefined };
  }

  const { latitude, longitude } = geo;

  // Filter (0,0) as no-location
  if (latitude === 0 && longitude === 0) {
    return { latitude: undefined, longitude: undefined };
  }

  // Filter invalid GPS ranges
  if (latitude < -90 || latitude > 90 || longitude < -180 || longitude > 180) {
    return { latitude: undefined, longitude: undefined };
  }

  // If primary source has (0,0) or invalid, try fallback
  if (geoData && geoDataExif && geoData !== geoDataExif) {
    const primary = geoData;
    if (
      (primary.latitude === 0 && primary.longitude === 0) ||
      primary.latitude === undefined ||
      primary.longitude === undefined
    ) {
      return parseGps(geoDataExif, undefined);
    }
  }

  return { latitude, longitude };
}

export function parseGoogleTakeoutSidecar(jsonString: string): TakeoutMetadata | null {
  if (!jsonString || jsonString.trim().length === 0) {
    return null;
  }

  let data: Record<string, unknown>;
  try {
    data = JSON.parse(jsonString);
  } catch {
    return null;
  }

  if (typeof data !== 'object' || data === null) {
    return null;
  }

  // Must have at least photoTakenTime or creationTime to be a Takeout sidecar
  const photoTakenTime = data.photoTakenTime as { timestamp?: string } | undefined;
  const creationTime = data.creationTime as { timestamp?: string } | undefined;

  if (!photoTakenTime && !creationTime) {
    return null;
  }

  const title = (data.title as string) || '';
  const rawDescription = data.description as string | undefined;
  const description = rawDescription?.trim() ? rawDescription.trim() : undefined;

  const dateTaken = parseTimestamp(photoTakenTime) ?? parseTimestamp(creationTime);

  const geoData = data.geoData as { latitude?: number; longitude?: number } | undefined;
  const geoDataExif = data.geoDataExif as { latitude?: number; longitude?: number } | undefined;
  const { latitude, longitude } = parseGps(geoData, geoDataExif);

  const isFavorite = data.favorited === true;
  const isArchived = data.archived === true;

  return {
    title,
    description,
    dateTaken,
    latitude,
    longitude,
    isFavorite,
    isArchived,
  };
}
