import { Injectable } from '@nestjs/common';
import { AgentOperationPlanToolRequestSchemas } from 'src/dtos/agent-operation.dto';
import { AgentReadToolRequestSchemas } from 'src/dtos/agent-tool.dto';
import { AgentToolName } from 'src/enum';
import { renderAgentMcpPromptPlaceholders } from 'src/services/agent-mcp-prompt-placeholders';
import { AgentMcpToolContractService } from 'src/services/agent-mcp-tool-contract.service';
import type { AgentMcpToolContract, AgentMcpToolExample } from 'src/types/agent-mcp-contract.types';

export const AGENT_MCP_GENERATED_DOC_RELATIVE_PATH = 'docs/superpowers/generated/pi-agent-mcp-tools.md';

type AgentMcpDocumentedToolArgumentExample = {
  toolName: AgentToolName;
  toolTitle: string;
  exampleName: string;
  description: string;
  arguments: Record<string, unknown>;
};

type AgentMcpJsonRpcExample = {
  name: string;
  description: string;
  request: Record<string, unknown>;
};

const compactShortStringArrays = (value: string): string =>
  value.replaceAll(/\[\n((?:\s{2,}"[^"\n]*",?\n)+)(\s*)\]/g, (match, entries: string, indent: string) => {
    const values = [...entries.matchAll(/"[^"\n]*"/g)].map(([entry]) => entry);
    const compact = `[${values.join(', ')}]`;
    return indent.length + compact.length <= 100 ? compact : match;
  });

const json = (value: unknown): string => `${compactShortStringArrays(JSON.stringify(value, null, 2))}\n`;

const markdownJson = (value: unknown): string => `\`\`\`json\n${json(renderAgentMcpPromptPlaceholders(value))}\`\`\``;

const sanitizeText = (value: string): string =>
  value
    .replaceAll(/bearer\s+[a-z0-9._-]+/gi, 'Bearer <redacted>')
    .replaceAll(/\/(?:srv|home|tmp|var|etc|opt|mnt|Users)\/[^\s`)]*/gi, '<redacted-path>')
    .replaceAll(/provider[- ]?key/gi, 'provider credential')
    .replaceAll(/stack trace/gi, 'error details');

const toolArgumentsSchemaFor = (toolName: AgentToolName) =>
  Object.hasOwn(AgentReadToolRequestSchemas, toolName)
    ? AgentReadToolRequestSchemas[toolName as keyof typeof AgentReadToolRequestSchemas]
    : AgentOperationPlanToolRequestSchemas[toolName as keyof typeof AgentOperationPlanToolRequestSchemas];

@Injectable()
export class AgentMcpDocsService {
  constructor(private readonly contractService: AgentMcpToolContractService) {}

  listDocumentedToolArgumentExamples(): AgentMcpDocumentedToolArgumentExample[] {
    return this.contractService.listToolContracts().flatMap((contract) =>
      contract.examples.map((example) => ({
        toolName: contract.name,
        toolTitle: contract.title,
        exampleName: example.name,
        description: example.description,
        arguments: structuredClone(example.arguments),
      })),
    );
  }

  listJsonRpcExamples(): AgentMcpJsonRpcExample[] {
    const examples = this.listDocumentedToolArgumentExamples();
    const readExample = examples.find((example) => example.toolName === AgentToolName.ReadAssetMetadata);
    const planExample = examples.find((example) => example.toolName === AgentToolName.ProposeAlbumOperations);

    if (!readExample || !planExample) {
      throw new Error('Missing required MCP docs examples');
    }

    return [
      {
        name: 'initialize',
        description: 'Initialize the MCP session.',
        request: {
          jsonrpc: '2.0',
          id: 'init-1',
          method: 'initialize',
          params: {
            protocolVersion: '2025-11-25',
            capabilities: {},
            clientInfo: { name: 'pi-agent-runner', version: '0.1.0' },
          },
        },
      },
      {
        name: 'tools-list',
        description: 'List available Gallery MCP tools.',
        request: { jsonrpc: '2.0', id: 'tools-1', method: 'tools/list' },
      },
      {
        name: 'tools-call-read',
        description: 'Call a read tool with params.arguments.',
        request: {
          jsonrpc: '2.0',
          id: 'read-1',
          method: 'tools/call',
          params: { name: readExample.toolName, arguments: readExample.arguments },
        },
      },
      {
        name: 'tools-call-plan',
        description: 'Create a reviewable operation plan with params.arguments.',
        request: {
          jsonrpc: '2.0',
          id: 'plan-1',
          method: 'tools/call',
          params: { name: planExample.toolName, arguments: planExample.arguments },
        },
      },
    ];
  }

  generateMarkdown(): string {
    const contracts = this.contractService.listToolContracts();
    const lines: string[] = [
      '# Pi Agent MCP Tools',
      '',
      '> Generated from `AgentMcpToolContractService`. Do not edit this file by hand.',
      '',
      '## Endpoint And Authentication',
      '',
      'Use `POST /agent/internal/mcp/sessions/{sessionId}` with `Authorization: Bearer <agent-runner-token>`.',
      'The token is issued for the first-party Pi runner session. Do not use a normal Gallery user API key here.',
      '',
      'Bare MCP tool names are used in JSON-RPC requests. Pi-visible names may be shown with an `mcp_gallery_` prefix; for example `searchAssets` may appear to Pi as `mcp_gallery_searchAssets`.',
      '',
      '## JSON-RPC Wrappers',
      '',
      ...this.listJsonRpcExamples().flatMap((example) => [
        `### ${example.name}`,
        '',
        sanitizeText(example.description),
        '',
        markdownJson(example.request),
        '',
      ]),
      '## Approval Flow',
      '',
      'Read tools may return `status: "approval-required"` with a `toolCall.id`. Stop that turn and let Gallery show the approval UI.',
      'If Gallery resumes the runner with an approved result, use that result. If Gallery resumes without the result, retry the same read tool with only `{ "toolCallId": "<id>" }`.',
      'Do not ask the user to approve in chat and do not create a new read request with the old fields.',
      '',
      '## Progressive Detail Workflow',
      '',
      'Use the smallest useful payload first. Resolve names before search. Search for a handle/sourceRef first. Use `readSelectionMetadata` for search-handle metadata inspection and `readAssetMetadata` is legacy exact non-search ID usage. Propose a plan only after the selected asset set is clear.',
      '',
      '- Broad search: use `searchAssets` with handle detail or omit `detail`. Bounded handle-first searches may use `limit` up to 1000 when policy allows; samples remain 10-25. If `hasMore` or `resultSize.truncated` is true, page with `nextPage` or ask a narrowing question; when hasMore is true, keep the same mode, query, filters, order, and limit.',
      '- Curation: use `curateSelection` with `selectionHandleId`, `targetCount`, and a metadata-only strategy. It returns a derived `selectionHandle` plus `criteriaSummary`; it does not return selected asset IDs. Quality constraints use stored objective scores only.',
      '- Selection-backed plans: Use proposeAlbumFromSelection and proposeAssetBatchFromSelection after curateSelection returns a final selectionHandle.id. For operations those helpers do not support, such as recoverable trash, use proposeAlbumOperations with assetSource.selectionHandle.',
      '- Visual curation: search for a handle/sourceRef first and use `readSelectionMetadata` itemRef samples to narrow. Call preview reads only for exact non-search `assetIds` from a small inspected set when visual inspection is needed.',
      '- Technical metadata: search for a handle first, then call `readSelectionMetadata` with exact `fields` such as `camera`, `dates`, and `filename`; use `readAssetMetadata` only for legacy exact non-search asset IDs.',
      '- Large album: page bounded handle results and propose operations from `selectionHandle.id` or `sourceRef`. Do not request full metadata for every candidate.',
      '- All photos: avoid loading the whole library. Ask for a narrower date, album, tag, person, space, rating, or media-type filter when the task does not require every asset.',
      '',
      '### Resolver-to-search fidelity',
      '',
      '- After `resolveAssetSearchFilters`, copy `resolvedFilters` into `searchAssets.filters` exactly. Do not drop returned `personIds`, `spaceId`, `spacePersonIds`, `tagIds`, `albumIds`, or camera fields.',
      '- For people OR language such as `Pierre OR Aurelia`, resolve both names and search with one `personIds` array containing every resolved person id.',
      '- For shared-space people, send `spaceId` and `spacePersonIds` together. `spacePersonIds` without `spaceId` is invalid.',
      '- If a requested person, album, tag, space, camera make, camera model, or lens cannot be resolved unambiguously, ask a clarifying question instead of running a broad unfiltered search.',
      '',
      '### Large selections',
      '',
      '- Search compactly first and use the returned `selectionHandle.id` for the current bounded page.',
      '- Use `selectionHandle.id` as `assetSelectionHandleId` in the plan. Provider planning rejects raw `assetIds`.',
      '- If `hasMore` is true, page or narrow before claiming the handle covers every matching photo.',
      '- Plan review still shows counts and samples; Gallery applies only after user approval.',
      '',
      '## Source-Backed Planning Defaults',
      '',
      'Use high-level workflow tools first for album, space, and asset batch requests. provider planning rejects raw assetIds; use `assetSelectionHandleId`, `assetSource.selectionHandle`, `assetSource.previousSearch`, or `assetSource.search` so Gallery materializes IDs server-side. `assetSource.explicitAssets` is internal-only and rejected for provider-facing planning.',
      'Use proposeAlbumFromSelection and proposeAssetBatchFromSelection after curateSelection returns a final selectionHandle.id.',
      '',
      'Treat `wrong_id_domain` as recoverable: retry with `assetSource.selectionHandle`, `assetSource.search`, or `previousSearch.sourceRef` from the correct tool domain. Treat `needs_clarification` as recoverable: ask the user to choose one Gallery-provided option, then pass the selected `choiceRefs` in the next declarative named filter.',
      '',
      ...this.renderSourceBackedWorkflowExamples(),
      '## Tools',
      '',
      ...contracts.flatMap((contract) => this.renderTool(contract)),
      '## Common Mistakes',
      '',
      ...contracts.flatMap((contract) => this.renderMistakes(contract)),
      '## Safety',
      '',
      'No MCP apply tool is exposed. Final writes happen only through Gallery plan review UI after the user reviews and applies a proposed plan.',
      '',
    ];

    return `${lines.join('\n').replaceAll(/\n{3,}/g, '\n\n')}`;
  }

  private renderTool(contract: AgentMcpToolContract): string[] {
    return [
      `### ${contract.title}`,
      '',
      `MCP tool name: \`${contract.name}\``,
      '',
      sanitizeText(contract.description),
      '',
      sanitizeText(contract.usage),
      '',
      'Argument modes:',
      '',
      ...contract.argumentModes.flatMap((mode) => [
        `- \`${mode.name}\`: ${sanitizeText(mode.whenToUse)}`,
        `  Required fields: ${mode.requiredFields.length > 0 ? mode.requiredFields.map((field) => `\`${field}\``).join(', ') : 'none'}.`,
        `  Forbidden fields: ${mode.forbiddenFields.length > 0 ? mode.forbiddenFields.map((field) => `\`${field}\``).join(', ') : 'none'}.`,
      ]),
      '',
      ...contract.examples.flatMap((example) => this.renderExample(contract, example)),
    ];
  }

  private renderExample(contract: AgentMcpToolContract, example: AgentMcpToolExample): string[] {
    const schema = toolArgumentsSchemaFor(contract.name);
    const result = schema.safeParse(example.arguments);
    if (!result.success) {
      throw new Error(`Invalid generated MCP docs example: ${contract.name} ${example.name}`);
    }

    return [
      `#### ${example.name}`,
      '',
      sanitizeText(example.description),
      '',
      `<!-- mcp-docs:tool-arguments tool="${contract.name}" example="${example.name}" -->`,
      '',
      markdownJson(example.arguments),
      '',
    ];
  }

  private renderSourceBackedWorkflowExamples(): string[] {
    const examples = this.listDocumentedToolArgumentExamples();
    const pick = (toolName: AgentToolName, exampleName: string) => {
      const example = examples.find(
        (candidate) => candidate.toolName === toolName && candidate.exampleName === exampleName,
      );
      if (!example) {
        throw new Error(`Missing source-backed workflow docs example ${toolName} ${exampleName}`);
      }

      return example;
    };

    const selected = [
      pick(AgentToolName.ProposeAlbumFromSearch, 'create-south-africa-pierre-aurelia-album'),
      pick(AgentToolName.ProposeAlbumFromSearch, 'create-album-from-previous-search'),
      pick(AgentToolName.ProposeSpaceFromSearch, 'create-space-from-declarative-search'),
      pick(AgentToolName.ProposeAssetBatchFromSearch, 'favorite-search-results'),
    ];

    return selected.flatMap((example) => [
      `### ${example.description}`,
      '',
      `MCP tool name: \`${example.toolName}\``,
      '',
      `Example: \`${example.exampleName}\``,
      '',
      markdownJson(example.arguments),
      '',
    ]);
  }

  private renderMistakes(contract: AgentMcpToolContract): string[] {
    return [
      `### ${contract.title}`,
      '',
      ...contract.commonMistakes.flatMap((mistake) => [`- \`${mistake.id}\`: ${sanitizeText(mistake.hint)}`]),
      '',
    ];
  }
}
