import { AssetRepository } from 'src/repositories/asset.repository';
import { RepositoryInterface } from 'src/types';
import { Mocked, vitest } from 'vitest';

export const newAssetRepositoryMock = (): Mocked<RepositoryInterface<AssetRepository>> => {
  return {
    create: vitest.fn(),
    createAll: vitest.fn(),
    upsertExif: vitest.fn(),
    updateAllExif: vitest.fn(),
    updateDateTimeOriginal: vitest.fn().mockResolvedValue([]),
    unlockProperties: vitest.fn().mockResolvedValue([]),
    upsertJobStatus: vitest.fn(),
    getForCopy: vitest.fn(),
    getByDayOfYear: vitest.fn(),
    getMemoryAssetsForPerson: vitest.fn(),
    getMemoryLocationClusters: vitest.fn(),
    getMemoryAssetsForLocation: vitest.fn(),
    getMemoryAssetsForPeriod: vitest.fn().mockResolvedValue([]),
    getMemoryFacesForPeriod: vitest.fn().mockResolvedValue([]),
    getMemoryPersonDailyCounts: vitest.fn().mockResolvedValue([]),
    getMemoryAssetsForPersonWindow: vitest.fn().mockResolvedValue([]),
    getByIds: vitest.fn().mockResolvedValue([]),
    getByIdsWithAllRelationsButStacks: vitest.fn().mockResolvedValue([]),
    getOwnedManifestAssets: vitest.fn().mockResolvedValue([]),
    getById: vitest.fn(),
    getByChecksum: vitest.fn(),
    getByChecksums: vitest.fn(),
    getUploadAssetIdByChecksum: vitest.fn(),
    getLivePhotoCount: vitest.fn(),
    getLibraryAssetCount: vitest.fn(),
    updateAll: vitest.fn(),
    getByLibraryIdWithFaces: vitest.fn(),
    getByAlbumIdWithFaces: vitest.fn(),
    getByLibraryIdAndOriginalPath: vitest.fn(),
    deleteAll: vitest.fn(),
    update: vitest.fn(),
    remove: vitest.fn(),
    findLivePhotoMatch: vitest.fn(),
    getStatistics: vitest.fn(),
    getCalendarHeatmap: vitest.fn(),
    getTimeBucket: vitest.fn(),
    getTimeBuckets: vitest.fn(),
    getTimeBucketCovers: vitest.fn(),
    getAssetIdByCity: vitest.fn(),
    getRecentlyCreatedAssetIds: vitest.fn(),
    upsertFile: vitest.fn(),
    upsertFiles: vitest.fn(),
    deleteFile: vitest.fn(),
    deleteFiles: vitest.fn(),
    detectOfflineExternalAssets: vitest.fn(),
    filterNewExternalAssetPaths: vitest.fn(),
    updateByLibraryId: vitest.fn(),
    getFileSamples: vitest.fn(),
    getMetadata: vitest.fn(),
    getMetadataByKey: vitest.fn(),
    upsertMetadata: vitest.fn(),
    upsertBulkMetadata: vitest.fn(),
    deleteMetadataByKey: vitest.fn(),
    deleteBulkMetadata: vitest.fn(),
    getChecksumsByIds: vitest.fn(),
    getForOriginal: vitest.fn(),
    getForOriginals: vitest.fn(),
    getForThumbnail: vitest.fn(),
    getForVideo: vitest.fn(),
    getEditedEncodedVideo: vitest.fn(),
    getForEdit: vitest.fn(),
    getForOcr: vitest.fn(),
    getForMetadataExtractionTags: vitest.fn(),
    getForFaces: vitest.fn(),
    getForUpdateTags: vitest.fn(),
    getExternalAssetIds: vitest.fn().mockResolvedValue(new Set<string>()),
  };
};
