name: Update Immich SDK

on:
  release:
    types: [published]

permissions: {}

jobs:
  publish:
    name: Publish `@immich/sdk`
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          token: ${{ github.token }}

      - name: Setup Mise
        uses: immich-app/devtools/actions/use-mise@cf6e190bacde3d7bda59372a786b36ac7d01536a # use-mise-action-v2.0.1
        with:
          github_token: ${{ github.token }}

      - name: Install deps
        run: pnpm --filter @immich/sdk install --frozen-lockfile

      - name: Build
        run: pnpm --filter @immich/sdk build

      - name: Publish
        run: pnpm --filter @immich/sdk publish --provenance --no-git-checks
