name: Update Immich SDK

on:
  release:
    types: [published]

permissions: {}

jobs:
  publish:
    name: Publish `@immich/sdk`
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          token: ${{ github.token }}

      - name: Setup Mise
        uses: immich-app/devtools/actions/use-mise@06a9ef925332c91be647d6256642b86b398592c8 # use-mise-action-v3.2.1
        with:
          github_token: ${{ github.token }}

      - name: Install deps
        run: pnpm --filter @immich/sdk install --frozen-lockfile

      - name: Build
        run: pnpm --filter @immich/sdk build

      - name: Publish
        env:
          NPM_TAG: ${{ github.event.release.prerelease && 'rc' || 'latest' }}
        run: pnpm --filter @immich/sdk publish --provenance --no-git-checks --tag "$NPM_TAG"
